### ISSUE TITLE
Tool does not upgrade apps which are installed in user context

### ISSUE THREAD

**Issue by rawIce** [Romanitho/Winget-AutoUpdate#1]
I have been experimenting with this awesome tool for a while now at it seems like it only checks for apps which are installed in a machine wide context. I checked the log at `C:\ProgramData\winget-update\logs\updates.log` and it also does not list any upgradeable apps from user context. 

Therefore I think there might be an issue with the scope the scheduled task or `winget` is running at, because if I run `winget upgrade` manually from an administrator PowerShell, it shows me all upgradeable apps from both machine and logged on user context and is also able to upgrade all of them. 

In case this behavior is intended, is there a way to also upgrade apps from User scope automatically with this tool? 

Thanks!

**Comment by Romanitho** [comment]
Hi,

I think this is "normal" behaviour. Winget is run with system context via scheduled task. So it cannot update user context apps.

In my mind, apps would always have been installed with "admin" context in our setup. That's why I don't have any scenario to get it working in user context. But it can be something we could imagine and work on.

Thanks for your post.

**Comment by Romanitho** [comment]
By the way, you can run the "winget-upgrade.ps1" script in the user context (maybe with admin rights). Like this, it can see your user installed apps.
Let me know if that helps.

Thanks.

**Comment by rawIce** [comment]
Thanks for your assistance so far. 

Running the script or task as regular user does not work because the tool is located at `%ProgramData%` where you need admin privileges to write the log. Indeed running the script manually as Admin (UAC prompt) works fine. 

Interestingly I could not find any way to run the scheduled task under these permissions. If I set it to run as the logged on user, it is not sufficient. Running with `highest privileges` means running under `SYSTEM `again which is already happening and loses the user's scope... 

I might test creating a second scheduled task which is running fully in user context and move the log file to a different location.

**Comment by Romanitho** [comment]
> Running the script or task as regular user does not work because the tool is located at `%ProgramData%` where you need admin privileges to write the log. Indeed running the script manually as Admin (UAC prompt) works fine.

You can install script somewhere else if you want. Or even run directly "winget-upgrade.ps1" in the Winget-AutoUpdate folder.

> Interestingly I could not find any way to run the scheduled task under these permissions. If I set it to run as the logged on user, it is not sufficient. Running with `highest privileges` means running under `SYSTEM `again which is already happening and loses the user's scope...

try to just download project zip, extract it and run with user context the script I mentioned earlier. It should work and install user context apps.

Let me know if that helps.

Of course, you can create similar scheduled task with user context
