### ISSUE TITLE
Feature Request - include date in logfile name

### ISSUE THREAD

**Issue by domwhite93** [Romanitho/Winget-AutoUpdate#111]
Hi Romanitho
Thanks for your amazing work!

We'd like to centrally collect the installation logs from Winget-AutoUpdate to investigate failed installations. Therefore it would be more comfortable to create a log file per day, and grab that log file each day with a scheduled task / some other way.

What about a -DateInLogfileName Switch, which would be checked in Start-Init.ps1 for example as following?:

`$date = $(Get-Date -UFormat "%d-%m-%Y")`
`Script:LogFile = "$LogPath\$date-updates.log"`

Kind regards,
Dom

**Comment by Romanitho** [comment]
Hi
Thanks 😊

It is more confortable for me to have all under one log file to be honest. As this is something I don't check everyday, I can open one log file and have a look on previous runs at once.

I was thinking about a feature that can centralize install errors. (Sending an email with computer name and failed updates to an IT mailbox for instance).

But create a daily log can be easy to purge as well. We need to think about that 😅

**Comment by domwhite93** [comment]
We're planning to use a combination of Winget-AutoUpdate and Winget-Install to manage all commonly used App Installations and Updates :) we're designing our own reporting functions by analyzing the Winget-AutoUpdate Logfile - for now - but we'd sure appreciate any form of central logging, if you ever implement it ;).

Thanks for your work! Kind regards,
Dom

**Comment by Romanitho** [comment]
We are also looking for a central logging solution. We need to think about it, but for now, no clue :)
