### ISSUE TITLE
Winget-AutoUpdate takes a lot of time to check if winget is installed

### ISSUE THREAD

**Issue by soredake** [Romanitho/Winget-AutoUpdate#112]
![image](https://user-images.githubusercontent.com/5204968/176516189-24d228b2-fbcd-4b9a-baa8-fd82befa6bc7.png)

Two minutes to check this is too much.

**Comment by soredake** [comment]
I found why this is happening, it's because i've installed powershell from msstore, running install with `powershell` instead of `pwsh` makes checking very fast.

**Comment by soredake** [comment]
https://github.com/PowerShell/PowerShell/issues/17232

**Comment by Romanitho** [comment]
ok, nice. Thanks for feedback
