### ISSUE TITLE
Check for installed winget fails on windows 11

### ISSUE THREAD

**Issue by soredake** [Romanitho/Winget-AutoUpdate#113]
![image](https://user-images.githubusercontent.com/5204968/176516611-b734b462-c512-45eb-8667-2e9eae8b83ec.png)
![image](https://user-images.githubusercontent.com/5204968/176516644-16ef6881-cc8e-4ea5-850f-0505225ab816.png)

**Comment by Romanitho** [comment]
works on my Win11. what's written ?

**Comment by soredake** [comment]
"Class not registred"

**Comment by soredake** [comment]
Can winget existence be checked with `winget --version` or something like this?

**Comment by soredake** [comment]
I found why this is happening, it's because i've installed powershell from msstore, running install with `powershell` instead of `pwsh` fixes detection.

**Comment by soredake** [comment]
Seems like it can't detect if winget is installed because powershell is partially sandboxed.

**Comment by soredake** [comment]
https://github.com/PowerShell/PowerShell/issues/17232

**Comment by soredake** [comment]
> You cannot have any info with `winget --version` or `--info`

Maybe i'm understanding it wrong, but i've put `winget --version` into Winget-AutoUpdate-Install.ps1 and it outputted version just fine.
