### ISSUE TITLE
Doesn't work on my Win 11

### ISSUE THREAD

**Issue by Dhowti** [Romanitho/Winget-AutoUpdate#117]
Applications update does not work on Win 11. Win 10 ok. If I change the user in the task from SYSTEM to my account, then it works well, but then I see a powershell window. When running task with SYSTEM, an empty version of winget is in the log file. SYSTEM doesn't have access to winget?

10:18:29 - Notification Level: Full. Notification Language: English
10:18:29 - Checking internet connection...
10:18:31 - Connected !
10:18:31 - Winget Version: 
10:18:31 - WAU current version: 1.11.5
10:18:31 - WAU AutoUpdate is Enabled.
10:18:32 - WAU is up to date.
10:18:32 - WAU uses Black List config
10:18:32 - Checking application updates on Winget Repository...
10:18:33 - No new update.
10:18:33 - End of process!

But there are some updates.

**Comment by Dhowti** [comment]
Temporary solution - parameter "-windowStyle hidden" for powershell in the task.

**Comment by Romanitho** [comment]
Hi. probably linked issue: https://github.com/Romanitho/Winget-AutoUpdate/issues/113

**Comment by Gumbyohson** [comment]
> Temporary solution - parameter "-windowStyle hidden" for powershell in the task.

This doesn't seem to have helped in my case.

![image](https://user-images.githubusercontent.com/1866263/177899521-8a2f0de1-d9ee-4335-8c2e-cbb68e5e5bd8.png)

![image](https://user-images.githubusercontent.com/1866263/177899570-dccc6df1-8e3a-4c2c-8dbf-e2d57dd525e2.png)

![image](https://user-images.githubusercontent.com/1866263/177899601-a04fa3af-059e-43f9-871e-9ae220fe9ed8.png)

**Comment by Gumbyohson** [comment]
> > > Temporary solution - parameter "-windowStyle hidden" for powershell in the task.
> > 
> > 
> > This doesn't seem to have helped in my case.
> 
> This doesn't make winget work, it makes the script window invisible if the task is running with non-System privileges. I have it run with the my account, and so update works.

That makes way more sense now :\
Yeah so Windows 11 running as NT\system not working.

**Comment by Romanitho** [comment]
Hi. WindowStyle hidden make sense when it is run with an user account. For system, it is not necessary. 
On my several windows 11 it works great. You might have something wrong on your side. Have you had a look here https://github.com/Romanitho/Winget-AutoUpdate/issues/113 ?

**Comment by Dhowti** [comment]
> On my several windows 11 it works great. You might have something wrong on your side. Have you had a look here #113 ?

Yes. But I've not installed powershell from msstore.
I'm fine with running the task as admin with "-windowStyle hidden" parameter. But then on WAU self-update I see the script window with "Running Post Update actions"

**Comment by Romanitho** [comment]
If MsStore PS is not installed, it might be an interesting case 😅

If you run under system, you don't have any dialog box displayed, exactly.
