### ISSUE TITLE
Test-Network Metered Connection Test Fails on PS7

### ISSUE THREAD

**Issue by SuperJC710e** [Romanitho/Winget-AutoUpdate#121]
So I have both the system PS and PS 7+ installed on my system. My Windows Terminal defaults to opening PS7. When `Test-Network` runs, it fails with these errors:

```
[void][Windows.Networking.Connectivity.NetworkInformation, Windows, ContentType = WindowsRuntime]

InvalidOperation: Unable to find type [Windows.Networking.Connectivity.NetworkInformation,Windows, ContentType=WindowsRuntime].

[Windows.Networking.Connectivity.NetworkInformation]::GetInternetConnectionProfile().GetConnectionCost()

InvalidOperation: Unable to find type [Windows.Networking.Connectivity.NetworkInformation].
```

I guess that functionality is not available there. I guess the scheduled task runs in the system version which has the functionality so far, but this might be something to consider modifying for the future.

**Comment by Romanitho** [comment]
Haven't had time to investigate yet.
