### ISSUE TITLE
Do not automatically update but only notify if an update is available

### ISSUE THREAD

**Issue by sitiom** [Romanitho/Winget-AutoUpdate#129]
There is already `excluded_apps.txt` to exclude apps from updating, but I want to get notified for some of those apps so I can decide to update them for myself.

**Comment by Romanitho** [comment]
It will not be easy to implement. You want to have another list ? You want to get all notifications ? you'll be spammed everyday til you update thoses apps.

**Comment by sitiom** [comment]
> You want to have another list ?

The existing excluded apps list can be expanded to provide additional info.

**Comment by Romanitho** [comment]
That's true. We wanted to keep it as simple as possible, but this is something that can be discussed of course :)

**Comment by sitiom** [comment]
bump

**Comment by sitiom** [comment]
Bump

**Comment by sitiom** [comment]
Bump
