### ISSUE TITLE
Don't install winget 1.4 for now

### ISSUE THREAD

**Issue by soredake** [Romanitho/Winget-AutoUpdate#132]
Winget 1.4 is bugged for now https://github.com/microsoft/winget-cli/issues/2365

**Comment by Romanitho** [comment]
Thanks for sharing :)

**Comment by xixifaha** [comment]
I upgraded the version and I can't upgrade now. What should i do?

**Comment by xixifaha** [comment]
I upgraded the version and I can't upgrade now. What should i do?

**Comment by Romanitho** [comment]
Uninstall and reinstall from the MS Store

**Comment by xixifaha** [comment]
I can't find a way to uninstall it.

**Comment by Romanitho** [comment]
Install directly the [Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle](https://github.com/microsoft/winget-cli/releases/download/v1.3.2091/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle) from https://github.com/microsoft/winget-cli/releases/tag/v1.3.2091

**Comment by soredake** [comment]
1.4 is fixed now **https://github.com/microsoft/winget-cli/pull/2370**
