### ISSUE TITLE
Blacklist seems broken for MS Store installed apps

### ISSUE THREAD

**Issue by carlosvsilva** [Romanitho/Winget-AutoUpdate#148]
Case in point: oh-my-posh, despite adding its ID to excluded_apps.txt:

ClickUp.ClickUp
XP8K0HKJFRXGCK

That project makes new releases almost every day, so your auto-updater just keeps sending notifications about updates, and even updates the MS Store app to the external daily releases from github, instead of just updating when the MS Store version updates as it should be.

Any way to fix this ?
Thanks

**Comment by Romanitho** [comment]
Hi, can you share your log file please ? I think you may exclude the wrong app ID.

**Comment by Romanitho** [comment]
https://github.com/microsoft/winget-pkgs/tree/8d7a2ef71417ba09414920e802e0eef029df96e1/manifests/j/JanDeDobbeleer/OhMyPosh

**Comment by carlosvsilva** [comment]
Hi, I'm pretty confident I blacklisted the correct ID, as reported by winget.

Here are the logs:
[updates.log](https://github.com/Romanitho/Winget-AutoUpdate/files/9359102/updates.log)

**Comment by Romanitho** [comment]
in your log I clearly see that the `JanDeDobbeleer.OhMyPosh` is not in your black list txt file...

**Comment by carlosvsilva** [comment]
yes, because I never installed any standalone random version, otherwise winget would update it everyday or otherwise not update it at all stalling it. It's like being on a stable (Windows Store) or beta/alpha channel (github constant releases for this particular installer).
So I just installed the Windows Store version and blacklisted its correct ID (XP8K0HKJFRXGCK). I shouldnt have to deal with continuous random standalone updates to this package from github, overwriting my Store stable version, don't know what's that all about.

Now I am workarounding it by also blacklisting the standalone ID (JanDeDobbeleer.OhMyPosh) but since I never installed the standalone version, this workaround is a complete hack but with useful side effects.

**Comment by Romanitho** [comment]
basically, your problem seems to be related to Winget itself, as you have installed an app that is detected by Winget. Then, WAU take the lead if Winget detect an app... :/
