### ISSUE TITLE
Tray Application

### ISSUE THREAD

**Issue by sitiom** [Romanitho/Winget-AutoUpdate#15]
See https://github.com/microsoft/winget-cli/issues/212#issuecomment-1052889052. It looks like you already have a base application to start. You may also want to see how [ChocoButler](https://github.com/cokelid/ChocoButler) does it, as it is also written in PowerShell.

**Comment by yevon** [comment]
I was about to post this issue, it would be awesome having a tray icon and being able to search for the update command in the start menu, like "Winget update".

**Comment by Romanitho** [comment]
We are trying to have a good basis before implementing more feature. But if you have ideas and want to implement new features, feel free to try :)

**Comment by sitiom** [comment]
bump

**Comment by sitiom** [comment]
bump

**Comment by sitiom** [comment]
Bump

**Comment by sitiom** [comment]
Bump
