### ISSUE TITLE
Update included_apps.txt from remote location

### ISSUE THREAD

**Issue by doludizgin** [Romanitho/Winget-AutoUpdate#151]
Hi,

If you want to update the included_apps.txt with new apps it would be nice if you could specify a remote location of this file, like a http repo so you could update this file without deploying the app again with intune.

**Comment by doludizgin** [comment]
Example to retrieve a whitelist from a github repo in the Get-IncludedApps.ps1

#Function to get White List apps

function Get-IncludedApps {

    if (Test-Path "$WorkingDir\included_apps.txt") {
        $webclient = new-object System.Net.WebClient
        $includedapps = 
        $webclient.DownloadString("https://raw.githubusercontent.com/userrepo/winget/main/included_apps.txt")
        return Get-Content $includedapps
    
    }

}

**Comment by doludizgin** [comment]
I am using this example for Get-includedApps.ps1

`#Function to get White List apps

function Get-IncludedApps {

    if (Test-Path "$WorkingDir\included_apps.txt") {

        Invoke-WebRequest -URI https://gitcdn.link/cdn/user/winget/main/included_apps.txt -OutFile "$WorkingDir\included_apps.txt"
        return Get-Content -Path "$WorkingDir\included_apps.txt"
    
    }

}
`

**Comment by KnifMelti** [comment]
#147

**Comment by Romanitho** [comment]
I'm not very active at the moment, sorry, but yes, definitely a good idea as already discussed :)

I was thinking to add another parameter on installation with `-OnlineList` or something. And use a similar function as yours to update White and/or Black lists. In this way, default install remains without this feature as it is used for enterprise purpose.
Then, we can add a reg value that contains the server link if `-OnlinList` is used, or 0 if not.
