### ISSUE TITLE
included_apps.txt bug

### ISSUE THREAD

**Issue by mtengmo** [Romanitho/Winget-AutoUpdate#153]
It´s a small bug reinstalling the app with a new included_apps.txt, it doesn´t replace the included_apps.txt if it exists before.

line 206
            elseif (!(Test-Path "$WingetUpdatePath\included_apps.txt")) {

Solved with removing the !
            elseif ((Test-Path "$WingetUpdatePath\included_apps.txt")) {

**Comment by Romanitho** [comment]
@KnifMelti could you check ? I cannot atm 😅
@mtengmo thanks for your help

**Comment by KnifMelti** [comment]
On it, checking...

**Comment by Romanitho** [comment]
Thanks 😊

**Comment by KnifMelti** [comment]
@mtengmo 
If the script has reached **line 206** it suggests you have started it with the parameters **-UseWhiteList -NoClean**
_(Keep critical files when installing/uninstalling. This setting will keep "excluded_apps.txt", "included_apps.txt", "mods" and "logs" as they were.)_
Then an "**included_apps.txt**" will not be overwritten.
Could you please check again?

**Comment by KnifMelti** [comment]
Bump.
