### ISSUE TITLE
Network check from China

### ISSUE THREAD

**Issue by mtengmo** [Romanitho/Winget-AutoUpdate#156]
I see some issues with the network check from China. My feeling is that the ipv4 8.8.8.8 doesn´t work in China. 
        $TestNetwork = Test-NetConnection google.com -Port 443 -InformationLevel Quiet  

I will see if this will help.

**Comment by Romanitho** [comment]
In fact, sometimes behind a captive portal (on Gust WiFi for instance) google.com responds (but with the captive portal IP).
There is probably a better way to check connectivity even behind a captive portal, but I don't have a better way to do it currently :/

**Comment by Knud3** [comment]
Also some companies blocks known public DNS server IP's to ensure that all DNS requests goes through their own DNS server. In that case 8.8.8.8 is not usable to check internet connection.

**Comment by Romanitho** [comment]
I see. As a workaround, before installing WAU, you could change this settings in the script and block WAU Slef Update.  
I don't really know how to optimize this part, because pinging ghitub.com for instance could success behind a captive portal. And you might not be connected in fact.

**Comment by Knud3** [comment]
Just dummy idea, but what about if you add simple text file to this repo and connection test would try to read that file and if output is right connection is working.

**Comment by Romanitho** [comment]
brilliant ! Initially I wanted to use Github API, but do to [limitations](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-personal-accounts) I wanted to have something else. But your idea is simple and efficient. Thanks 😅

**Comment by Romanitho** [comment]
https://github.com/Romanitho/Winget-AutoUpdate/tree/review-testnetwork
