### ISSUE TITLE
Polish localization and English typo fix

### ISSUE THREAD

**Issue by Rafii2198** [Romanitho/Winget-AutoUpdate#161]
I don't know how to implement it into the program, so I'll just leave it [here](https://drive.google.com/file/d/1AuoafQ-k4d6KBuQ9hG45D2STtThyoO6C/view?usp=sharing) for someone to implement it.
Also, I fixed a typo in English locale. The word `connection` was missing an `e`. Again I'll leave it [here](https://drive.google.com/file/d/1DCV5VXjz8MJuzJJSJf5T1s3SC7d4Md6b/view?usp=sharing).

**Comment by Romanitho** [comment]
Thanks for your work.

To implement in the project (and get credited automatically 😅) you just need to fork the project, edit/change/add your contributions in your forked project, and then submit a pull request to get your changes submitted in this project. Hope it helps

**Comment by Rafii2198** [comment]
I could do this for the typo in English, but when I just put the Polish file in, it didn't do anything, so I assumed I had to change some code for it to work, and I rather not mess with that up, unless it should work, and I just did something wrong with the file itself.

**Comment by Rafii2198** [comment]
Oh wait, I just reinstalled the whole program, and it started working! I'll make pull request shortly!

**Comment by Romanitho** [comment]
Thank you for your help and feedback 👍

**Comment by Rafii2198** [comment]
You're welcome!
