### ISSUE TITLE
Not all apps are discovered

### ISSUE THREAD

**Issue by mmelkersen** [Romanitho/Winget-AutoUpdate#167]
![image](https://user-images.githubusercontent.com/77377683/191914098-b9ad7d93-fc22-41f4-b6b3-288752b023f3.png)

I see that the manual winget upgrade see more programs than Winget-AutoUpdate. 
Anyone else see this?

**Comment by Romanitho** [comment]
WAU runs in system context. If the apps are installed for user, WAU cannot manage them.

**Comment by mmelkersen** [comment]
Makes sense. Thanks!

**Comment by Romanitho** [comment]
you can try to reinstall your app with winget and the `--scope machine` argument

**Comment by ppvnf** [comment]
> you can try to reinstall your app with winget and the `--scope machine` argument

I explained my problem in https://github.com/Romanitho/Winget-AutoUpdate/issues/158#issuecomment-1262200561. This didn't work:

PS C:\WINDOWS\system32> winget install Playnite.Playnite --scope machine
Nenhum instalador aplicável encontrado; consulte os logs para obter mais detalhes.
PS C:\WINDOWS\system32>

**Comment by Romanitho** [comment]
That's because this app doesn't have Machine install scope:  
https://github.com/microsoft/winget-pkgs/blob/master/manifests/p/Playnite/Playnite/10.3/Playnite.Playnite.installer.yaml

**Comment by ppvnf** [comment]
@Romanitho Is there any plan to make Winget-AutoUpdate update apps installed to the user or another workaround?

**Comment by Romanitho** [comment]
At the moment, Winget doesn't support a way to detect the apps installed for system or for users. So we do not have any easy way to implement an auto update feature for users apps as users may not have admin right to update all the apps, depending or not the way apps are installed (system or users)

**Comment by Romanitho** [comment]
We could have a way to run WAU for system and get all available updates for system in a temp location (like `winget upgrade`). Then, we could run the same command under user context and get the delta between "system" apps and all apps (returned by user context command). This delta is indeed the user context apps. We just need to run WAU under user context with that "delta" apps.
This can also be something part of the "User" action with the shortcut https://github.com/Romanitho/Winget-AutoUpdate/discussions/135#discussioncomment-3779086
