### ISSUE TITLE
AutoUpdate detecting upgrade for some applications that are not detected when running winget manually

### ISSUE THREAD

**Issue by ppvnf** [Romanitho/Winget-AutoUpdate#170]
This issue is the exact opposite of https://github.com/Romanitho/Winget-AutoUpdate/issues/158 (I am also facing it). While checking the logs I found  Winget-AutoUpdate is detecting a package that isn't detected by `winget upgrade`: Microsoft Visual C++ 2013 Redist update from 12.0.21005.1 to 12.0.40664.0.

By the way, I know Microsoft really screwed up with Visual C++ version numeration and hopefully this will be fixed by them. 

However, I don't understand how Winget-Autoupdate is able to find an update while Winget isn't. I also checked on control panel and I have both 12.0.21005.1 and 12.0.40664.0 versions of Microsoft Visual C++ 2013 installed somehow! Sure, as a workaround I will blacklist this package.

![Captura de tela 2022-09-29 083853](https://user-images.githubusercontent.com/73800734/193025894-e11266a3-5085-44e7-99ed-ea652e906711.png)

![Captura de tela 2022-09-29 084747](https://user-images.githubusercontent.com/73800734/193025920-ab350ce1-54a1-4ef9-b5fa-6afc7bb0a381.png)

[updates.log](https://github.com/Romanitho/Winget-AutoUpdate/files/9674361/updates.log)

**Comment by ppvnf** [comment]
I've managed to fix it by uninstalling and then reinstalling all Microsoft Visual C++ packages. I guess this bug was mostly Microsoft's fault

**Comment by Romanitho** [comment]
Thanks for your feedback ;)
