### ISSUE TITLE
1.15.0 upgrade

### ISSUE THREAD

**Issue by KnifMelti** [Romanitho/Winget-AutoUpdate#182]
Maybe it's nothing but when installed over an older WAU the user task just writes to the log:
`Running in User context`

Then nothing happens but it finds user installed apps and tries to upgrade them, but fails (the toasts pop up).
Not until an uninstall and then an install it behaves correctly, but then boy it works! 👏💕🌹

This is now my second upgrade.
On this I ran the install with (on the other  with default blacklist:
`-UpdatesAtLogon -Silent -UseWhiteList -BypassListForUsers -StartMenuShortcut -DoNotUpdate`

**Comment by Romanitho** [comment]
I need to check what happens when upgraded "manually"

**Comment by Romanitho** [comment]
and on your second upgrade, everything works as expected ?

**Comment by KnifMelti** [comment]
Uninstall/Install - then it's perfect! 👌✌👏

**Comment by Romanitho** [comment]
Oh, I think I know why... If the log file exists, the ACL are not overwritten. I handled that for the auto-update, but not for reinstall.
