### ISSUE TITLE
Microsoft.DotNet.DesktopRuntime.X

### ISSUE THREAD

**Issue by ppvnf** [Romanitho/Winget-AutoUpdate#196]
Packages:

Microsoft.DotNet.DesktopRuntime.6
Microsoft.DotNet.DesktopRuntime.5
Microsoft.DotNet.DesktopRuntime.3_1

Both fail to update. I had to blacklist them to make WAU stop trying to update them. Who is at fault here: Microsoft, Winget-AutoUpdate or myself?

![Captura de tela 2022-10-19 204048](https://user-images.githubusercontent.com/73800734/196824873-f03200dc-4a2f-4988-992d-751ae595e8ed.png)
![Captura de tela 2022-10-19 204220](https://user-images.githubusercontent.com/73800734/196824879-138d1fb8-25a5-44df-8110-f199d0558a32.png)
[updates.log](https://github.com/Romanitho/Winget-AutoUpdate/files/9825021/updates.log)

For some crazy reason I have the latest version of all x86 and x64 DesktopRuntimes. Winget doesn't detect any update (correctly), but WAU does (incorrectly). I also know that Microsoft.DotNet.DesktopRuntime is a problematic package for Winget, so I don't know who to blame...

**Comment by Romanitho** [comment]
I have the same problem and I had to blacklist that package. In fact, if you look at your installed apps, you might have different version for the same package. Winget running under system gets confused.

**Comment by ppvnf** [comment]
I have the exactly same versions for x86 and x64. I know that if they are outdated Winget is only able to update the x64 version for some weird reason but when they are updated `winget upgrade` correctly doesn't detect any update for it and even so WAU tries to update

**Comment by Romanitho** [comment]
WAU using this command to get outdated apps:  
`Winget upgrade --source winget`
The only thing is, it is run under system context.

What you can try to do is to run the `"C:\ProgramData\Winget-AutoUpdate\winget-upgrade.ps1"` script from an admin user account and compare with system output.

**Comment by ppvnf** [comment]
> WAU using this command to get outdated apps: `Winget upgrade --source winget` The only thing is, it is run under system context.
> 
> What you can try to do is to run the `"C:\ProgramData\Winget-AutoUpdate\winget-upgrade.ps1"` script from an admin user account and compare with system output.

I guess it is simply not possible, then
