### ISSUE TITLE
Add WAU to Scoop

### ISSUE THREAD

**Issue by ppvnf** [Romanitho/Winget-AutoUpdate#197]
https://github.com/ScoopInstaller/Extras/issues/9522

**Comment by Romanitho** [comment]
Does someone using Scoop could use WAU as well ?

**Comment by ppvnf** [comment]
> Does someone using Scoop could use WAU as well ?

Yes, I do that. Scoop packages are portable, so there's no conflict when updating Winget packages.

It's possible to auto-update Scoop packages by simply creating a task with the following commands:
```
scoop update
scoop update *
scoop cache rm *
scoop cleanup *
```

**Comment by ppvnf** [comment]
Since Wigui is available on Scoop I don't think it's necessary to also have WAU there https://github.com/ScoopInstaller/Extras/issues/9475#issuecomment-1283234789
