### ISSUE TITLE
Allow installation through winget

### ISSUE THREAD

**Issue by lackovic** [Romanitho/Winget-AutoUpdate#215]
Would you consider allowing the application to be installed via [winget](https://winget.run/search?query=Winget-AutoUpdate)?

**Comment by Romanitho** [comment]
If someone wants to manage it, why not :) but what would be the default config ?

**Comment by KnifMelti** [comment]
...and it have to be constantly repackaged.
Note: At this time installers must either be MSIX, MSI or .exe application installers. Compressed .zip files and fonts are not currently supported
https://github.com/microsoft/winget-pkgs

**Comment by KnifMelti** [comment]
@Romanitho do you have a packaging certificate (I had until a year ago)?
One could make a wrapper that downloads your latest zip and installs it like you do in the WAU update solution and host the MSI on your GitHub and point to it in a manifest.
But, what parameters should it install with?

**Comment by KnifMelti** [comment]
One could buy a cert for a year just to do this wrapper as it never needs to be repackaged if the paths on GitHub never changes

**Comment by Romanitho** [comment]
The thing with an MSI or EXE is that it is not in the spirit of what I wanted, and as you said, we need certificate and stuff (what we don't have with WiGui). Full open source Powershell project can be easily understandable. So no extra thing than just few scripts and scheduled tasks 😊
But once again, it is a community project and if this is the best for all, let's create a winget package

**Comment by KnifMelti** [comment]
Better wait until the native PS support is in place for Winget packages (if it doesn't require certificate)
