### ISSUE TITLE
It will not work on ARM64 (Windows on ARM)

### ISSUE THREAD

**Issue by jhochwald** [Romanitho/Winget-AutoUpdate#216]
Windows on ARM is a bit different to the regular version.
Issue One: If `Invoke-WebRestrequest` runs elevated, or as System (therefore also elevated) you get an error message (Access Denied).
Issue Two: The Path the systemwide WinGet installation does NOT contain **x64**, Windows on ARM use **arm64** within the directory.

**Comment by Romanitho** [comment]
For the Issue One, does it mean it fails when run as system ? Do your changes bypass the internet connexion check ?
And thanks for Issue Two for your PR ;)

**Comment by jhochwald** [comment]
> For the Issue One, does it mean it fails when run as system ? Do your changes bypass the internet connexion check ?
> And thanks for Issue Two for your PR ;)

It failed. This is something that can happen on an ARM based system. I had that a couple of times. If you suppress it, it will work just fine.
The suppression will not bypass the check, and the issue is not related to your code. It’s a Windows on ARM problem… I have no real solution for it, just the workaround with suppressing it. It happens to all Invoke-WebRequest calls that run as System.
And I saw that you are using the suppression in other parts of your code, therefore I decide to use it here as well.
