### ISSUE TITLE
Update notification, but no auto-update possible?

### ISSUE THREAD

**Issue by Trollwut** [Romanitho/Winget-AutoUpdate#220]
Hey there!

Currently I'm using Chocolatey and winget. For choco, I have a plugin that - after booting - shows a notificiation that n updates are available. And then it does nothing (while I could do an auto-update).

Is this also possible with this piece of software?

I'd like to know about updates, but also have the choice on when to do them. :)

**Comment by Romanitho** [comment]
Hi,

At the moment, there is no option like this yet. But we are working on it. Stay tuned :)

**Comment by KnifMelti** [comment]
https://github.com/rupor-github/wsl-ssh-agent/issues/36#issuecomment-1241224420
This `this piece of software` is gaining traction... 😁

**Comment by Trollwut** [comment]
> Hi,
> 
> At the moment, there is no option like this yet. But we are working on it. Stay tuned :)

nice, very glad to hear! :)

is there already an issue/PR open for me to follow or will it be announced in this thread?

**Comment by Romanitho** [comment]
will be announced here, and link to PR when done

**Comment by Trollwut** [comment]
Any progress on this? :)

**Comment by Romanitho** [comment]
Not really. Not a lot of free time to improve things on that right now ^^ but, soon
