### ISSUE TITLE
No user logged on - UserContext

### ISSUE THREAD

**Issue by KnifMelti** [Romanitho/Winget-AutoUpdate#230]
```
07:16:55 - Get list of installed Winget apps in System context...
07:17:15 - Starting WAU in User context
```

Then nothing in the log and task **Winget-Autoupdate** Ready (last run 07:16:37), **Winget-Autoupdate-UserContext** Ready (last run yesterday - then it was a manual start) -UpdatesInterval Weekly

**Comment by Romanitho** [comment]
Normal behaviour. System task tries to run user task. No one is connected... interactive task cannot run. Nothing more in the logs.
Maybe we can add a check to see if someone is connected and put something in the logs

**Comment by KnifMelti** [comment]
Ah, then normal!

**Comment by Romanitho** [comment]
yup. But i agree, logs need to be clarified. If no user, then no user context run possible :) That's why I like to run the system task when a user logs on.
