### ISSUE TITLE
Upgrade from unknown to known version

### ISSUE THREAD

**Issue by ppvnf** [Romanitho/Winget-AutoUpdate#234]
I believe `--include-unknown` should be used in order to upgrade packages missing version number 
![Captura de tela 2022-11-09 084529](https://user-images.githubusercontent.com/73800734/200822258-e5cb0bb5-b3f4-4518-95cb-e35657417883.png)

**Comment by ppvnf** [comment]
This seems to be a problem with the package actually

**Comment by Romanitho** [comment]
Thanks for your feeedback. We encountered few problems with unknown, that's why it is out of scope at the moment
