### ISSUE TITLE
Auto-closing apps before update?

### ISSUE THREAD

**Issue by Dhowti** [Romanitho/Winget-AutoUpdate#239]
Some installers cannot close applications before updating. For example, Qbittorrent, Crow Translate. This causes a corrupted installation. Is it possible to automate this via WAU?

I imagine a new users config file with something like this:
qBittorrent.qBittorrent; qbittorrent

And

```
$qbt = Get-Process qbittorrent -ErrorAction SilentlyContinue
if ($qbt) {
    $qbt.CloseMainWindow()
    Start-Sleep -Milliseconds 5000
    if (!$qbt.HasExited) {
      $qbt | Stop-Process -Force
    }
}
winget upgrade --id qBittorrent.qBittorrent --silent
```

Code by Vadim Sterkin

**Comment by AgentSaint** [comment]
After updating, if the application has been run, it should be run again with normal permissions.

`Start-Process explorer "C:\Program Files\qBittorrent\qbittorrent.exe"`

Code by Vadim Sterkin
[www.outsidethebox.ms](https://www.outsidethebox.ms/21757/)

**Comment by KnifMelti** [comment]
You could use the mods-feature for all things **after** an upgrade.

Place an `AppID-upgrade.ps1` / `AppID-install.ps1`  under:

![image](https://user-images.githubusercontent.com/102996177/204090156-2cfc6af2-9a6c-4d09-b600-c2b5fbb2b684.png)
WAU uses `AppID-upgrade.ps1` / `AppID-install.ps1` when upgrading an app.
Custom scripts ex. remove the **Awake** module in **Microsoft Powertoys**:

```
Stop-Process -Name "powertoys*" -Force -ErrorAction SilentlyContinue
Start-sleep 3
Get-ChildItem -Path "${env:ProgramFiles}\PowerToys\modules\Awake" -Exclude PowerToys.AwakeModuleInterface.dll, Images | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
```

But, all this is **after** `winget `has done the upgrade, so at the moment, that doesn't function to stop a process before upgrading.
One could code a function so it could use `AppID-preinstall.ps1`, but I think it's the app developers own responsibility to make sure an upgrade can be performed correctly!

**Comment by KnifMelti** [comment]
After reading https://www.outsidethebox.ms/21757/ I've decided to implement a possibility to use `mods\AppID-preinstall.ps1`
So that the possibility exists and can be used when developers don't meet our expectations...
...stay tuned (my current/live PR mentioned above)!

**Comment by KnifMelti** [comment]
Have a solution, but I can't test it further because the manifests doesn't respond at all:
`https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.4.5/qbittorrent_4.4.5_setup.exe/download`

https://github.com/microsoft/winget-pkgs/blob/master/manifests/q/qBittorrent/qBittorrent/4.4.5/qBittorrent.qBittorrent.installer.yaml

**Comment by KnifMelti** [comment]
PR done (#232) - used **Crow Translate** for testing (rename to ***.ps1** and place them under **mods** - ***-uninstall** is for managing via https://github.com/Romanitho/Winget-Install):

[CrowTranslate.CrowTranslate-preinstall.txt](https://github.com/Romanitho/Winget-AutoUpdate/files/10097038/CrowTranslate.CrowTranslate-preinstall.txt)
[CrowTranslate.CrowTranslate-uninstall.txt](https://github.com/Romanitho/Winget-AutoUpdate/files/10097040/CrowTranslate.CrowTranslate-uninstall.txt)

@Romanitho needs to implement my **PR** in the **main branch**...

**Comment by KnifMelti** [comment]
If you want to test my solution (before @Romanitho implements it in the main branch), you could download:

- https://github.com/KnifMelti/Winget-AutoUpdate/blob/1244374c34fa8dc49f8465080592541252aba9fa/Winget-AutoUpdate/functions/Test-Mods.ps1
- https://github.com/KnifMelti/Winget-AutoUpdate/blob/1244374c34fa8dc49f8465080592541252aba9fa/Winget-AutoUpdate/functions/Update-App.ps1

They're the only ones needed for this to work in **WAU**

**Comment by Dhowti** [comment]
![Снимок экрана 2022-11-29 132936](https://user-images.githubusercontent.com/108597329/204439357-efebd3ff-6e9a-41cf-92ee-b4dc27b4092e.jpg)
Tested, it works.
