### ISSUE TITLE
Sporadic admin prompts for application updates

### ISSUE THREAD

**Issue by Tratino** [Romanitho/Winget-AutoUpdate#251]
We have rolled out Winget-AutoUpdate to our estate of roughly 350 AutoPilot & InTune managed devices. While it works for most of the clients flawless, on some of the client devices, an admin prompt to enter admin credentials was raised to update the application.
This does not work, as our users do not have admin rights. This dialog will show up again and again on this devices, while everything worked flawless on many other devices. Devices are all setup the same way and have the same OS level and winget version.

We could not single out one app that is causing this, but have a few app updates that show this behavior:
- Microsoft Visual C++ 2015-2022 Redistributable - 14.30.30704 both x86 and x64
- Java 8 Update 341 (64-bit) - [Version 8.0.3510.10 is also already installed]
- 7-zip 21.01

Why is this happening? The scheduled task is running with SYSTEM privileges (as per default).

Log extracts:
**_Updater.log_**
`##################################################
#     CHECK FOR APP UPDATES - 21.12.2022
##################################################
09:32:39 - Running in System context
09:32:40 - Notification Level: SuccessOnly. Notification Language: Deutsch
09:32:40 - Checking internet connection...
09:32:40 - Connected !
09:32:43 - Winget Version: v1.3.0
09:32:43 - WAU current version: 1.15.3
09:32:43 - WAU AutoUpdate is Enabled.
09:32:43 - WAU is up to date.
09:32:43 - WAU uses Black List config
09:32:43 - Checking application updates on Winget Repository...
-> Available update : Java 8 Update 341 (64-bit). Current version : 8.0.3410.31. Available version : 8.0.3510.10.
09:32:44 - Updating Java 8 Update 341 (64-bit) from 8.0.3410.31 to 8.0.3510.10...
09:32:44 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Oracle.JavaRuntimeEnvironment'   ##########
09:32:44 - -> Running: Winget upgrade --id Oracle.JavaRuntimeEnvironment --accept-package-agreements --accept-source-agreements -h
...                                                              
No applicable update found.
09:32:45 - Checking application updates on Winget Repository...
09:32:46 - -> An upgrade for Java 8 Update 341 (64-bit) failed, now trying an install instead...
09:32:46 - -> Running: Winget install --id Oracle.JavaRuntimeEnvironment --accept-package-agreements --accept-source-agreements -h 
...                                                              
Found Java 8 [Oracle.JavaRuntimeEnvironment] Version 8.0.3510.10
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://javadl.oracle.com/webapps/download/AutoDL?BundleId=247136_10e8cce67c7843478f41411b7003171c
...
Successfully verified installer hash
Starting package install...
...
Successfully installed
09:33:37 - Checking application updates on Winget Repository...
09:33:38 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Oracle.JavaRuntimeEnvironment'   ##########
09:33:38 - Java 8 Update 341 (64-bit) update failed.`

**_Winget-XYZ.log_**
`...
2022-12-21 09:24:46.190 [REPO] Examining ARP entries for Machine | X64
2022-12-21 09:24:46.201 [REPO] Examining ARP entries for Machine | X86
2022-12-21 09:24:46.207 [REPO] Examining ARP entries for User | X64
2022-12-21 09:24:46.281 [CLI ] Installer args: /s REBOOT=0 SPONSORS=0 AUTO_UPDATE=0
2022-12-21 09:24:46.281 [CLI ] Starting: 'C:\Users\USER1\AppData\Local\Temp\WinGet\Oracle.JavaRuntimeEnvironment.8.0.3510.10\AutoDL.exe' with arguments '/s REBOOT=0 SPONSORS=0 AUTO_UPDATE=0'
2022-12-21 09:24:59.482 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\ShellExecuteInstallerHandler.cpp(38)\WindowsPackageManager.dll!00007FFD15940351: (caller: 00007FFD15941399) Exception(1) tid(5bb8) 800704C7 The operation was canceled by the user.

2022-12-21 09:24:59.742 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\ShellExecuteInstallerHandler.cpp(38)\WindowsPackageManager.dll!00007FFD15940351: (caller: 00007FFD15941399) Exception(1) tid(5bb8) 800704C7 The operation was canceled by the user.`

**Comment by KnifMelti** [comment]
Hmm, I don't know why, but from the winget log (from `C:\Windows\Temp\WinGet\defaultState`?) I see `Examining ARP entries for User | X64` and `C:\Users\USER1\AppData\Local\Temp\WinGet` indicating that winget is running under user context.

**Comment by Tratino** [comment]
All Clients are x86 Intel systems.
Scheduled Task is running as SYSTEM (just checked again). 
Install command line in Intune includes updates of apps in user context as well:
"%systemroot%\sysnative\WindowsPowerShell\v1.0\powershell.exe" -noprofile -executionpolicy bypass -file "Winget-AutoUpdate-Install.ps1" -Silent -UpdatesAtLogon -UpdatesInterval Daily -InstallUserContext -NotificationLevel SuccessOnly

**Comment by KnifMelti** [comment]
I see.
- From where did you pull the **Winget-XYZ.log** (System/User)?
- Anything under the **Running in User context** entry in` C:\ProgramData\Winget-AutoUpdate\logs\updates.log`)

The curious thing is the evidence (from UAC admin prompts/logs) that **winget.exe** actually executes under **User** context even if the Schedule Task is running as **SYSTEM**...
...what happens if you do a **Fresh Start** (not retaining user data - default OOBE) on the failing clients in **Intune**?

**Comment by Tratino** [comment]
Hi,

sorry for the delay. Christmas holidays took its toll :)

The Winget-XYZ.logs are from 
C:\Users\<Username>\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\

I have one more example from updates.log (in the directory you mentioned), it is about the failing installation of VCRedist.
The script tries to update both in User and System context, both fails. I redacted the username and replaced progress indicators with "...".

`##################################################
#     CHECK FOR APP UPDATES - 12/5/2022
##################################################
09:33:49 - Running in User context
09:33:49 - Notification Level: SuccessOnly. Notification Language: English
09:33:49 - Checking internet connection...
09:33:49 - Connected !
09:33:54 - Winget Version: v1.3.2691
09:33:54 - WAU current version: 1.15.3
09:33:54 - WAU uses Black List config
09:33:54 - Checking application updates on Winget Repository...
-> Available update : Microsoft Visual C++ 2015-2022 Redistributable (x86) -…. Current version : 14.30.30704.0. Available version : 14.34.31931.0.
09:33:57 - Updating Microsoft Visual C++ 2015-2022 Redistributable (x86) -… from 14.30.30704.0 to 14.34.31931.0...
09:33:57 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.VCRedist.2015+.x86'   ##########
09:33:57 - -> Running: Winget upgrade --id Microsoft.VCRedist.2015+.x86 --accept-package-agreements --accept-source-agreements -h
... 
Found Microsoft Visual C++ 2015-2022 Redistributable (x86) [Microsoft.VCRedist.2015+.x86] Version 14.34.31931.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
...
Installer failed with exit code: 1602
Installer log is available at: C:\Users\<Username>\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.VCRedist.2015+.x86.14.34.31931.0-2022-12-05-09-33-58.712.log
You cancelled the installation.
11:14:41 - -> An upgrade for Microsoft Visual C++ 2015-2022 Redistributable (x86) -… failed, now trying an install instead...
11:14:41 - -> Running: Winget install --id Microsoft.VCRedist.2015+.x86 --accept-package-agreements --accept-source-agreements -h
...
Found Microsoft Visual C++ 2015-2022 Redistributable (x86) [Microsoft.VCRedist.2015+.x86] Version 14.34.31931.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
...
Installer failed with exit code: 1602
Installer log is available at: C:\Users\<Username>\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.VCRedist.2015+.x86.14.34.31931.0-2022-12-05-11-14-43.291.log
You cancelled the installation.
11:24:38 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Microsoft.VCRedist.2015+.x86'   ##########
11:24:38 - Microsoft Visual C++ 2015-2022 Redistributable (x86) -… update failed.
11:24:38 - No new update.
11:24:41 - End of process!

##################################################
#     CHECK FOR APP UPDATES - 06.12.2022
##################################################
16:29:21 - Running in System context
16:29:22 - Notification Level: SuccessOnly. Notification Language: Deutsch
16:29:22 - Checking internet connection...
16:29:23 - Connected !
16:29:26 - Winget Version: v1.3.0
16:29:26 - WAU current version: 1.15.3
16:29:26 - WAU AutoUpdate is Enabled.
16:29:26 - WAU is up to date.
16:29:26 - WAU uses Black List config
16:29:26 - Checking application updates on Winget Repository...
-> Available update : Microsoft 365 Apps for enterprise - en-us. Current version : 16.0.15629.20258. Available version : 16.0.15726.20188.
-> Available update : Microsoft Visual C++ 2015-2022 Redistributable (x86) -…. Current version : 14.30.30704.0. Available version : 14.34.31931.0.
-> Available update : Java 8 Update 341 (64-bit). Current version : 8.0.3410.31. Available version : 8.0.3510.10.
-> Available update : Teams Machine-Wide Installer. Current version : 1.5.0.8070. Available version : 1.5.00.28361.
-> Available update : Microsoft 365 Apps for Enterprise - de-de. Current version : 16.0.15629.20258. Available version : 16.0.15726.20188.
16:29:28 - Microsoft 365 Apps for enterprise - en-us : Skipped upgrade because it is in the excluded app list
16:29:29 - Updating Microsoft Visual C++ 2015-2022 Redistributable (x86) -… from 14.30.30704.0 to 14.34.31931.0...
16:29:29 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.VCRedist.2015+.x64'   ##########
16:29:29 - -> Running: Winget upgrade --id Microsoft.VCRedist.2015+.x64 --accept-package-agreements --accept-source-agreements -h
...
No applicable update found.
16:29:32 - -> An upgrade for Microsoft Visual C++ 2015-2022 Redistributable (x86) -… failed, now trying an install instead...
16:29:33 - -> Running: Winget install --id Microsoft.VCRedist.2015+.x64 --accept-package-agreements --accept-source-agreements -h
...
                                                              
Found Microsoft Visual C++ 2015-2022 Redistributable (x64) [Microsoft.VCRedist.2015+.x64] Version 14.34.31931.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/bcb0cef1-f8cb-4311-8a5c-650a5b694eab/2257B3FBE3C7559DE8B31170155A433FAF5B83829E67C589D5674FF086B868B9/VC_redist.x64.exe
...
Successfully verified installer hash
...
Starting package install...
...
Successfully installed
...
16:29:41 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Microsoft.VCRedist.2015+.x64'   ##########
16:29:41 - Microsoft Visual C++ 2015-2022 Redistributable (x86) -… update failed.`

**Comment by KnifMelti** [comment]
Those always fail.
Our **excluded_apps.txt** (when running with Black List):

Brave.Brave
Dropbox.Dropbox
ElectronicArts.EADesktop
Google.Chrome
Google.Drive
Microsoft.dotnet
Microsoft.DotNet.AspNetCore.6
Microsoft.DotNet.Runtime.3_1
Microsoft.DotNet.SDK.3_1
Microsoft.DotNet.SDK.6
Microsoft.Edge
Microsoft.EdgeWebView2Runtime
Microsoft.Office
Microsoft.OneDrive
Microsoft.Teams
Microsoft.VC++2013Redist-x64
Microsoft.VC++2013Redist-x86
Microsoft.VC++2015-2019Redist-x64
Microsoft.VC++2015-2019Redist-x86
Microsoft.VC++2015-2022Redist-x64
Microsoft.VC++2015-2022Redist-x86
Microsoft.VCRedist.2013.x64
Microsoft.VCRedist.2013.x86
Microsoft.WindowsSDK
Mozilla.Firefox
Mozilla.Firefox.ESR
TeamViewer.TeamViewer
TeamViewer.TeamViewer.Host
VideoLAN.VLC.Nightly

**Comment by Tratino** [comment]
Funny enough, for at least 80%+ of our systems the VCRedist Upgrade worked flawless :-/
I guess we have to work with an updated exclude list....
