### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by sschmocker** [Romanitho/Winget-AutoUpdate#26]
I Searched for some other Icons, i found those, if you want you can add them.

Error:
![error](https://user-images.githubusercontent.com/96051818/158992898-b3a3d84a-68ab-44b0-99bb-3eedbc37774e.png)

Warning:
![warning](https://user-images.githubusercontent.com/96051818/158992921-c322171d-2958-4bae-b05d-d4f2de349115.png)

Info:
![info](https://user-images.githubusercontent.com/96051818/158992910-6c2569d9-d6ef-46c1-8093-d0355840ce31.png)

Success:
![success](https://user-images.githubusercontent.com/96051818/158992918-c8ab48eb-ee5f-4d26-8af5-6a5b0f4c9c80.png)

**Comment by Romanitho** [comment]
Hello. Thanks for your contribution.
You can change them by yours in the "C:\ProgramData\Winget-AutoUpdate\icons" folder if you left the default installation path.

**Comment by sschmocker** [comment]
yes, i tried that and it works but they will get replaced if you push a new version of your script. 
btw. good work!

**Comment by Romanitho** [comment]
thanks for your comment :)
It's a good idea to be able to customize the icons... I will work on that on next releases.
