### ISSUE TITLE
ADMX file referenced not found [Microsoft365/Intune]

### ISSUE THREAD

**Issue by oxygen50** [Romanitho/Winget-AutoUpdate#265]
Hello,

I'm trying to deploy the ADMX/ADML Files to Intune. The following error keeps popping up. Version is 1.16.0.
Seems the ADMX file with the "main" namespace `Romanitho.Policies` is missing.

![grafik](https://user-images.githubusercontent.com/95914791/214057592-32e2fee8-7ae4-4f1d-999f-fe4bdf485a99.png)

The corresponding xml file with the missing namespace
[https://github.com/Romanitho/Winget-AutoUpdate/blob/v1.16.0/Policies/WAU.admx](url)

```
<?xml version="1.0" encoding="utf-8"?>
<policyDefinitions revision="4.4" schemaVersion="1.0">
  <policyNamespaces>
    <target prefix="WAU" namespace="Romanitho.Policies.WAU"/>
    **<using prefix="Romanitho" namespace="Romanitho.Policies"/>**
  </policyNamespaces>
```

Anyone else using Intune has this Issue?

Best regards

**Comment by KnifMelti** [comment]
Hi!
What happens if you in **WAU.adml** adds:
```
    <stringTable >
      <string id="WAU">Winget-AutoUpdate</string>
      <string id="Configuration">Winget-AutoUpdate</string>
...

```
And, then in **WAU.admx** edit it to:
```
  <policyNamespaces>
    <target prefix="WAU" namespace="Winget-AutoUpdate.Configuration.Policies"/>
  </policyNamespaces>

```
I don't run Intune and in domain GPO it hasn't been a problem...

**Comment by KnifMelti** [comment]
Ah, I see now.. ..you just have to delete the  **<using prefix="Romanitho" namespace="Romanitho.Policies"/>** (which I've already done in #263)

**Comment by oxygen50** [comment]
> Hi! [EDIT: not necessary] Could you first rename the files to **Winget-AutoUpdate.*** And then in **Winget-AutoUpdate.adml** adds:
> 
> ```
>     <stringTable >
>       <string id="WAU">Winget-AutoUpdate</string>
>       <string id="Configuration">Winget-AutoUpdate</string>
> ...
> ```
> 
> And, then in **Winget-AutoUpdate.admx** edit it to just:
> 
> ```
>   <policyNamespaces>
>     <target prefix="WAU" namespace="Winget-AutoUpdate.Configuration.Policies"/>
>   </policyNamespaces>
> ```
> 
> [/EDIT]
> 
> I don't run Intune and in domain GPO it hasn't been a problem... ...please tell me if it worked or not!

Workaround No.1:
Error keeps getting up. Seems to be connected with the internal naming of the namespace. `Romanitho`

![grafik](https://user-images.githubusercontent.com/95914791/214238628-6616e3bf-3778-419c-9ab8-33eb86c882bc.png)

**Comment by oxygen50** [comment]
> Ah, I see now.. ..you'll just have to delete the `<using prefix="Romanitho" namespace="Romanitho.Policies"/>` (which I've already done in #263) Current ADML/ADMX development revision is **4.7** - I reckon @Romanitho will release **1.16.1** with my fixes in #263... ...a new feature in that **PR** is:
> 
> **-ListPath** Get Black/White List from external Path (**URL/UNC/GPO/Local**) - download/copy to Winget-AutoUpdate installation location if external list is newer. If `-ListPath` is set to **GPO** the Black/White List can be managed from within the GPO itself under **Application GPO Blacklist**/**Application GPO Whitelist**. Thanks to [Weatherlights](https://github.com/Weatherlights) in [#256 (reply in thread)](https://github.com/Romanitho/Winget-AutoUpdate/discussions/256#discussioncomment-4710599)!

Sadly. Same Error as above

**Comment by oxygen50** [comment]
You can fix the error when removing the line following lines from the admx file:

`<using prefix="Romanitho" namespace="Romanitho.Policies"/>`

`<parentCategory ref="Romanitho:Cat_Romanitho"/>`

this works:
```
<?xml version="1.0" encoding="utf-8"?>
<policyDefinitions revision="4.4" schemaVersion="1.0">
  <policyNamespaces>
    <target prefix="WAU" namespace="Winget-AutoUpdate.Configuration.Policies"/>
  </policyNamespaces>
  <resources minRequiredRevision="4.4"/>
  <supportedOn>
    <definitions>
      <definition name="SUPPORTED_WAU_1_15_3" displayName="$(string.SUPPORTED_WAU_1_15_3)"/>
    </definitions>
  </supportedOn>
  <categories>
    <category displayName="$(string.WAU)" name="WAU">
    </category>
  </categories>
  <policies>
```

Thanks for the help. Can you create a PR?

**Comment by KnifMelti** [comment]
Could you test with in WAU.adml:
```
<?xml version="1.0" encoding="utf-8"?>
<policyDefinitionResources xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" revision="4.7" schemaVersion="1.0" xmlns="http://schemas.microsoft.com/GroupPolicy/2006/07/PolicyDefinitions">
  <displayName>WinGet-AutoUpdate</displayName>
  <description>WinGet-AutoUpdate GPO Management</description>
  <resources >
    <stringTable >
      <string id="WAU">Winget-AutoUpdate</string>
      <string id="SUPPORTED_WAU_1_16_0">Winget-AutoUpdate version 1.16.0 or later</string>
```
Search an Replace to `SUPPORTED_WAU_1_15_3` to `SUPPORTED_WAU_1_16_0`

And then in WAU.admx:
```
<?xml version="1.0" encoding="utf-8"?>
<policyDefinitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" revision="4.7" xsi:schemaLocation="" schemaVersion="1.0" xmlns="http://www.microsoft.com/GroupPolicy/PolicyDefinitions">
  <policyNamespaces>
    <target prefix="WAU" namespace="Romanitho.Policies.WAU"/>
  </policyNamespaces>
  <resources minRequiredRevision="4.7" fallbackCulture="en-us"/>
  <supportedOn>
    <definitions>
      <definition name="SUPPORTED_WAU_1_16_0" displayName="$(string.SUPPORTED_WAU_1_16_0)"/>
    </definitions>
  </supportedOn>
  <categories><category displayName="$(string.WAU)" name="WAU"/></categories>
```
That's how my current PR #263 looks like, and if that works it's already done...
...thanks for the feedback/report!

**Comment by KnifMelti** [comment]
Take them from here:
https://github.com/KnifMelti/Winget-AutoUpdate/blob/SmallBits/Policies/en-US/WAU.adml
https://github.com/KnifMelti/Winget-AutoUpdate/blob/SmallBits/Policies/WAU.admx

**Comment by KnifMelti** [comment]
With the above revison 4.7 from #263 there's no problem at all (bat that revison incorporates settings gor Lists saved in GPO, not released yet.:
![image](https://user-images.githubusercontent.com/102996177/214278500-ffb34b6a-9306-4b27-9066-4f5f9040e138.png)

**Comment by Romanitho** [comment]
I have a strange behavior on my side. It has been working this morning, but from then, it doesn't work anymore, no policy applied or edited. Very odd.

**Comment by KnifMelti** [comment]
Doesn't se that at all, neither in our company domain or local at home (yes, I manage via local GPO at home)

**Comment by Romanitho** [comment]
yes.
This morning policies was pushed to the computer successfully. But I made few changes and nothing happen anymore. I restarted all the process and policies. I think the problem comes from Intune.

**Comment by KnifMelti** [comment]
...and, so do I; everyting in it is always preview (=beta) 😁

**Comment by Romanitho** [comment]
Totally ! And ADMX thing is preview of course haha
