### ISSUE TITLE
Exclude specific version of apps

### ISSUE THREAD

**Issue by sitiom** [Romanitho/Winget-AutoUpdate#27]
[`excluded_apps.txt`](https://github.com/Romanitho/Winget-AutoUpdate/blob/main/excluded_apps.txt) already has the ability to exclude apps, but not apps of a specific version. This is useful for something like managing multiple python installations.
```console
$ winget list python
Name            Id                                     Version     Available   Source
-------------------------------------------------------------------------------------
Python 3        Python.Python.3                        3.9.7150.0  3.10.2150.0 winget
Python Launcher {0CD41B07-EDF9-4B77-8C7C-CCCA1C435970} 3.10.7686.0
Python 3        Python.Python.3                        3.10.2150.0             winget
$ winget upgrade
Name                         Id                                    Version     Available   Source
-------------------------------------------------------------------------------------------------
Python 3                     Python.Python.3                       3.9.7150.0  3.10.3150.0 winget
Python 3                     Python.Python.3                       3.10.2150.0 3.10.3150.0 winget
```
Now, trying to do `winget upgrade --all` will try to reinstall Python 3.10 everytime, thus the need for this feature. Related discussion: https://github.com/microsoft/winget-cli/discussions/794

**Comment by sitiom** [comment]
As you can see in the list above, I have two installations of python installed. I want to be able to autoupdate the `3.10` version of python while keeping `3.9` python excluded.

**Comment by Romanitho** [comment]
Unfortunately at the moment it's not possible to do that. And i think there is winget limit here.
If someone else have an idea to implement that, it would be nice, but not sure.

**Comment by sitiom** [comment]
Not possible in Winget, but I think it can be implemented here. One solution would be to check for duplicates in the list of upgrades and check which versions are excluded. If there is no specified version in the exclusions, exclude all versions instead.

**Comment by Romanitho** [comment]
But what will happen when you want winget to upgrade only one ? Not sure it can handles multiple versions at the moment.

**Comment by sitiom** [comment]
`No installed package found matching input criteria.` It seems like Winget just ignores it.

**Comment by Romanitho** [comment]
So I don't have any idea how to handle this :/

**Comment by Romanitho** [comment]
I think Winget team is forking on this kind of subject. But for us, it is probably not possible to handle. Or I cannot see how. Closing this for now :)
