### ISSUE TITLE
[Feature Request]: Defer an upgrade

### ISSUE THREAD

**Issue by ElianeMegert** [Romanitho/Winget-AutoUpdate#271]
### The request

Hi all

It would be nice if an upgrade could be defered by the user.

Thanks!
Eliane

### Is your feature request related to a problem?

```txt
No
```

**Comment by KnifMelti** [comment]
Hello!
@Romanitho is working on it in #228

**Comment by Romanitho** [comment]
#220

**Comment by Frederick-G764** [comment]
Would it be possible to set a general deferral period, like for Windows Updates to create update rings?

**Comment by Romanitho** [comment]
we need to think about how to implement that 😇

**Comment by Frederick-G764** [comment]
I also thought about this, I think the only way is to cache the available update list, because as far as I now there is no date delivered with the updates.

**Comment by KnifMelti** [comment]
Bump!

**Comment by ElianeMegert** [comment]
> I also thought about this, I think the only way is to cache the available update list, because as far as I now there is no date delivered with the updates.

I think I would not cache the list or enable defer for dedicated apps but defer the whole process. I just think it gets messy when storing  list thats already old again (i am sure those situation will follow up close). I'd rather work with a deferal history (registry) and another scheduled task - or even the same one - just hitting the same process again. Until deathline reached.

**Comment by ElianeMegert** [comment]
btw: I hope https://github.com/microsoft/winget-cli/tree/master/src/PowerShell/Microsoft.WinGet.Client#quick-start-guide will make it easier at some point.

**Comment by KnifMelti** [comment]
"_../To run the module, make sure you are using the latest version of PowerShell (not Windows PowerShell)./.._" but...
...https://github.com/Romanitho/Winget-AutoUpdate#known-issues (only **Windows Powershell** (if I'm not mistaken...)

**Comment by ElianeMegert** [comment]
> "_../To run the module, make sure you are using the latest version of PowerShell (not Windows PowerShell)./.._" but... ...https://github.com/Romanitho/Winget-AutoUpdate#known-issues - only **Windows Powershell** (if I'm not mistaken...)

yeah and right now its quite messy to get it running  - at least the last time i tried. but its obviously very much needed and pressure will get up on the matter.
