### ISSUE TITLE
[Bug]: v1.16.1 is not working for me

### ISSUE THREAD

**Issue by Dhowti** [Romanitho/Winget-AutoUpdate#273]
### The problem

Hi!
Updated and stopped working. Uninstalled and reinstalled twice, no luck.

### What version of WAU has the issue?

v1.16.1

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 22H2

### What version of winget are you using?

1.4.10173

### Log information

```txt
##################################################
#     CHECK FOR APP UPDATES - 03.02.2023
##################################################
11:26:44 - Running in System context
11:26:44 - Notification Level: Full. Notification Language: Русский
11:26:44 - Checking internet connection...
11:26:45 - Connected !
11:26:45 - Winget Version: 
11:26:45 - WAU current version: 1.16.1
11:26:45 - WAU AutoUpdate is Enabled.
11:26:46 - WAU is up to date.
11:26:46 - WAU uses Black List config
11:26:46 - Checking application updates on Winget Repository...
11:26:46 - Critical: An error occured, exiting...
11:26:46 - Problem:
```

### Additional information

Winget log I did not find for this event

**Comment by Dhowti** [comment]
This WAU error leaves no trace in the winget log files

**Comment by KnifMelti** [comment]
Good morning!
This is not a **WAU** error but a **winget repository** error.
Should have thought of that too (if there's no string in the error from winget), so that's the error/bug of **WAU**...
...could you open an command prompt and run:
`winget upgrade --source winget`, please?

What is the result?

**Comment by KnifMelti** [comment]
Ah, now I see it: `11:26:45 - Winget Version: ` - it don't find your winget in System context...

**Comment by Dhowti** [comment]
> `winget upgrade --source winget`, please?
> 
> What is the result?

winget upgrade --source winget
No installed packages were found that match the conditions you entered.

(output is translated from Russian)

**Comment by KnifMelti** [comment]
This is a strange one.. ..can't replicate your problem on any machine (upgrading/reinstalling/uninstall or install)...

...could you make a backup of your ` C:\ProgramData\Winget-AutoUpdate\excluded_apps.txt` (if you added anything) and then run an uninstall via the included `uninstall.bat`  (run as admin - this will delete everything under `C:\ProgramData\Winget-AutoUpdate`) and then install it again via `install.bat` (edit the install parameters to your like - run as admin)
Then you can replace `excluded_apps.txt` with your backup again and run WAU.

**Comment by Dhowti** [comment]
@KnifMelti Done, same error.

**Comment by KnifMelti** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/winget-gives-no-installed-package-found-matching/a05f281f-b82a-4556-af04-b197e225cb62

**Comment by KnifMelti** [comment]
https://github.com/Romanitho/Winget-AutoUpdate/issues/246 now I'll have to go to work...

**Comment by Romanitho** [comment]
no problem on my machine as well.

**Comment by Dhowti** [comment]
Tested winget in command line, normally searches, installs, updates applications.

**Comment by Dhowti** [comment]
The task Winget-AutoUpdate-UserContext sees the winget version but throws the same error.

**Comment by KnifMelti** [comment]
https://github.com/microsoft/winget-cli/issues/2426#issuecomment-1346471510

**Comment by Dhowti** [comment]
@KnifMelti Did many times. Winget works, WAU not.

**Comment by Romanitho** [comment]
could it be due to special characters ?

**Comment by KnifMelti** [comment]
@Dhowti  your system winget logs?

**Comment by Dhowti** [comment]
@Romanitho In the output of winget? I don't know, the previous version of WAU worked.

**Comment by Dhowti** [comment]
@KnifMelti No new winget logs after running WAU. It looks like there is no contact between them.

**Comment by KnifMelti** [comment]
As if winget isn't started at all...

**Comment by Dhowti** [comment]
If I am alone, I will return to the previous version. @Romanitho where to insert -DisableWAUAutoUpdate parameter? Can't understand.

**Comment by KnifMelti** [comment]
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Winget-AutoUpdate
WAU_DisableAutoUpdate=1 (DWord)

Or when installing: -DisableWAUAutoUpdate

**Comment by Dhowti** [comment]
Ok, thanks, rolled back.

**Comment by KnifMelti** [comment]
And, now it's working? Really odd...

**Comment by KnifMelti** [comment]
I have it rolled out to 5000+ clients, no problem...

**Comment by Dhowti** [comment]
Yep :)
Maybe someone else will chime in with the same problem.

**Comment by Romanitho** [comment]
@KnifMelti I think it comes from your error check if no update is available at all:
```
    #Get list of available upgrades on winget format
    $upgradeResult = & $Winget upgrade --source winget | Out-String

    #Start Convertion of winget format to an array. Check if "-----" exists (Winget Error Handling)
    if (!($upgradeResult -match "-----")) {
        return "Problem:`n$upgradeResult"
    }
```
If `$upgradeResult` is empty, there is no `------` so fails. (I guess)

**Comment by Dhowti** [comment]
@Romanitho Why then does winget not write a log during this operation?

**Comment by KnifMelti** [comment]
Is it so @Dhowti, isn't there any upgrades at all on your computer?

**Comment by Dhowti** [comment]
@KnifMelti There were updates in the morning when the error occurred, but not now.

**Comment by KnifMelti** [comment]
@Dhowti 
Could you try to in under functions in 1.16.1 edit the Get-WingetOutdatedApps.ps1:
From Line 11:
```
   #Get list of available upgrades on winget format
    $upgradeResult = & $Winget upgrade --source winget | Out-String
    if (!$upgradeResult) {
        $upgradeResult = "-----"
    }

```

**Comment by Dhowti** [comment]
`##################################################
#     CHECK FOR APP UPDATES - 03.02.2023
##################################################
20:25:55 - Running in System context
20:25:55 - Activated WAU GPO Management detected, comparing...
20:25:55 - No Changed settings detected
20:25:55 - Notification Level: Full. Notification Language: Русский
20:25:55 - Checking internet connection...
20:25:56 - Connected !
20:25:56 - Winget Version: 
20:25:56 - WAU current version: 1.16.1
20:25:56 - WAU AutoUpdate is Enabled.
20:25:57 - WAU is up to date.
20:25:57 - WAU uses Black List config
20:25:57 - Checking application updates on Winget Repository...
-> Available update : . Current version : . Available version : .
-> Available update : . Current version : . Available version : .
-> Available update : . Current version : . Available version : .
20:25:58 - Updating  from  to ...
20:26:02 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID ''   ##########
20:26:02 - -> Running: Winget upgrade --id  --accept-package-agreements --accept-source-agreements -h
20:26:02 - -> An upgrade for  failed, now trying an install instead...
20:26:02 - -> Running: Winget install --id  --accept-package-agreements --accept-source-agreements -h
20:26:02 - -> An upgrade for  failed, now trying an install instead...
20:26:02 - -> Running: Winget install --id  --accept-package-agreements --accept-source-agreements -h
20:26:03 - -> An upgrade for  failed, now trying an install instead...
20:26:03 - -> Running: Winget install --id  --accept-package-agreements --accept-source-agreements -h
20:26:03 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID ''   ##########
20:26:03 -  update failed.
20:26:07 - Updating  from  to ...
20:26:10 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID ''   ##########
20:26:10 - -> Running: Winget upgrade --id  --accept-package-agreements --accept-source-agreements -h
20:26:11 - -> An upgrade for  failed, now trying an install instead...
20:26:11 - -> Running: Winget install --id  --accept-package-agreements --accept-source-agreements -h
20:26:12 - -> An upgrade for  failed, now trying an install instead...
20:26:12 - -> Running: Winget install --id  --accept-package-agreements --accept-source-agreements -h
20:26:12 - -> An upgrade for  failed, now trying an install instead...
20:26:12 - -> Running: Winget install --id  --accept-package-agreements --accept-source-agreements -h
20:26:12 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID ''   ##########
20:26:12 -  update failed.
20:26:16 - Updating  from  to ...
20:26:20 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID ''   ##########
20:26:20 - -> Running: Winget upgrade --id  --accept-package-agreements --accept-source-agreements -h
20:26:20 - -> An upgrade for  failed, now trying an install instead...
20:26:20 - -> Running: Winget install --id  --accept-package-agreements --accept-source-agreements -h
20:26:21 - -> An upgrade for  failed, now trying an install instead...
20:26:21 - -> Running: Winget install --id  --accept-package-agreements --accept-source-agreements -h
20:26:21 - -> An upgrade for  failed, now trying an install instead...
20:26:21 - -> Running: Winget install --id  --accept-package-agreements --accept-source-agreements -h
20:26:21 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID ''   ##########
20:26:21 -  update failed.
20:26:25 - No new update.
20:26:26 - User logged on, get a list of installed Winget apps in System context...
20:26:26 - Starting WAU in User context

##################################################
#     CHECK FOR APP UPDATES - 03.02.2023
##################################################
20:26:26 - Running in User context
20:26:26 - Notification Level: Full. Notification Language: Русский
20:26:26 - Checking internet connection...
20:26:27 - Connected !
20:26:31 - Winget Version: v1.4.10173
20:26:31 - WAU current version: 1.16.1
20:26:31 - WAU uses Black List config
20:26:31 - Checking application updates on Winget Repository...
20:26:33 - Critical: An error occured, exiting...
20:26:33 - Problem:
   -\ 
Не найдены установленные пакеты, соответствующие введенным условиям.`

**Comment by KnifMelti** [comment]
Yup, @Romanitho was right - came to the same result when my client was fully updated  (never happens because we're running whitelist and on private blacklist theres a lot of vc redist etc thats blocked)
Will try to make a bugfix

**Comment by Dhowti** [comment]
Installed the application is not the latest version, winget upgrade sees the update, but WAU also gives an error.

**Comment by KnifMelti** [comment]
What, now it's double weird.. ...1.15.3 then?
Totally Uninstaller and deleted wau directory?

**Comment by Dhowti** [comment]
No, 1.16.1 again! :)

**Comment by Dhowti** [comment]
I'll test to the end

**Comment by KnifMelti** [comment]
I'll have to rewrite the error handling

**Comment by KnifMelti** [comment]
Now reverted to @Romanitho version, but a run of the app updating routine only if there's apps to upgrade:
![image](https://user-images.githubusercontent.com/102996177/216665735-b5b3c7a5-3cf8-4859-b48c-c339642e0a54.png)

**Comment by KnifMelti** [comment]
Thanks, @Dhowti !

**Comment by Dhowti** [comment]
> Ah, now I see it: `11:26:45 - Winget Version: ` - it doesn't find your winget version in System context...

This is an old problem. [#962](https://github.com/microsoft/winget-cli/discussions/962) Nobody found a solution?
For WAU, I solve this by setting the highest privileges in the Winget-AutoUpdate-UserContext task.

**Comment by KnifMelti** [comment]
I don't follow you...
Winget is definitely run by SYSTEM via the task scheduler.
The reason for your error was that ALL of your apps were up to date and my error checking didn't take that in account (with the fix #275 it does). 
The phrasing from winget "No installed packages were found that match the conditions you entered." is their way of saying that all is up to date. 
Why your winget version doesn't show I don't know, but WAU is already using winget from System account in that moment.
If it don't find it it breaks off before.
So, you don't have to raise the rights on the user context task.
If you want to use 1.16, my fix is rolling out when @Romanitho releases it.

**Comment by Dhowti** [comment]
I'm talking about another error. There is an old problem with running winget in system context. Therefore, my WAU does not show the winget version. I've attached a link, but it's irrelevant to the current thread.

**Comment by KnifMelti** [comment]
Ok
