### ISSUE TITLE
Not working as SYSTEM?

### ISSUE THREAD

**Issue by bebeidon** [Romanitho/Winget-AutoUpdate#28]
hi i'm trying out your script and it seems to work well for a admin user if i start it manually.
but it does not work as SYSTEM-user as intended. the scheduled task also does nothing if i start it.
what i found out so far, the "winget upgrade" command does not work as system-user. when i try to run it with psexec as system, after entering "winget upgrade" it will load for a second and then show the current path in blue and stops. no list or anything as output in the terminal.
it is not possible for me to do anything with the upgrade command even when i install all apps through intune as system and the "winget install" command works with no problem.

**Comment by Romanitho** [comment]
Hello,

What is the Winget version and how did you install the script ?

**Comment by bebeidon** [comment]
it's version 1.17.10271.
i installed by starting install.bat as admin. like i said when i run the script in admin powershell as user it works, but for system the upgrade command seems broken.

**Comment by Romanitho** [comment]
It works for me, I've just retried now.
Is MS Visual C++ 2015-2019 installed on the targeted machine ?

**Comment by bebeidon** [comment]
no, but 2015-2022 is installed

**Comment by bebeidon** [comment]
yes, i will try.
here you can see the different output of winget upgrade for me:
https://imgur.com/a/AJN18cp

**Comment by Romanitho** [comment]
https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by bebeidon** [comment]
it's still the same behaviour.
have you tested it like in my screenshots? so for you if you are in a cmd with SYSTEM you can do "winget upgrade"?

**Comment by bebeidon** [comment]
i tried this now on a total unrelated computer and have the exact same result, "winget upgrade" as SYSTEM will just show the working directory in blue/green color.

**Comment by bebeidon** [comment]
it works with preview version 1.18.431.0
but now i have all these directories:

22.03.2022  11:50    <DIR>          Microsoft.DesktopAppInstaller_1.17.10271.0_x64__8wekyb3d8bbwe
22.03.2022  11:50    <DIR>          Microsoft.DesktopAppInstaller_1.18.431.0_neutral_split.language-de_8wekyb3d8bbwe
22.03.2022  11:50    <DIR>          Microsoft.DesktopAppInstaller_1.18.431.0_neutral_split.scale-100_8wekyb3d8bbwe
22.03.2022  11:50    <DIR>          Microsoft.DesktopAppInstaller_1.18.431.0_neutral_split.scale-125_8wekyb3d8bbwe
22.03.2022  11:50    <DIR>          Microsoft.DesktopAppInstaller_1.18.431.0_x64__8wekyb3d8bbwe
22.03.2022  11:50    <DIR>          Microsoft.DesktopAppInstaller_2022.213.605.0_neutral_~_8wekyb3d8bbwe

now i just have to make sure it picks the new one

**Comment by Romanitho** [comment]
![image](https://user-images.githubusercontent.com/96626929/159468137-d389a72a-be09-4c60-a0a1-3fb82538ba0e.png)

**Comment by bebeidon** [comment]
hm weird that i need the new version for it to work. but we are on different windows version, maybe this is important.

**Comment by Romanitho** [comment]
nope, it works on Win11 and Win10, I have a lot of machines I work with ;)

**Comment by bebeidon** [comment]
still, it's different win10 versions. and there has to be a reason for it not to work with 1.17.10271.0

**Comment by bebeidon** [comment]
list will leave me with the same result as upgrade but install works fine that's the thing i don't get at all.

**Comment by Romanitho** [comment]
Any news about your issue ?

**Comment by Matt-13** [comment]
This may be a similar issue, or the same thing:

I have seen this issue on one of my machines where running the scheduled task in taskschd.msc as the SYSTEM user gets:


updates.log:
```
##################################################
#     CHECK FOR APP UPDATES - 7/04/2022
##################################################
14:30:22 - Notification Langugage : English
14:30:22 - Checking internet connection...
14:30:23 - Connected !
14:30:23 - WAU AutoUpdate is Enabled. Current version : 1.7.0
14:30:24 - WAU is up to date.
14:30:24 - WAU uses Black List config
14:30:24 - Checking application updates on Winget Repository...
14:30:43 - No new update.
14:30:43 - End of process!
```

After manually running winget-upgrade.ps1 in an elevated prompt (as a local Administrator) a few minutes later, this is the result:

updates.log:
```
##################################################
#     CHECK FOR APP UPDATES - 7/04/2022
##################################################
14:35:26 - Notification Langugage : English
14:35:26 - Checking internet connection...
14:35:27 - Connected !
14:35:27 - WAU AutoUpdate is Enabled. Current version : 1.7.0
14:35:27 - WAU is up to date.
14:35:27 - WAU uses Black List config
14:35:28 - Checking application updates on Winget Repository...
Available update : Logitech Camera Settings. Current version : 2.5.17.0. Available version : 2.12.8.0.
Available update : Microsoft Teams. Current version : 1.4.00.32771. Available version : 1.5.00.8070.
Available update : WinRAR. Current version : 5.91.0. Available version : 6.11.0.
Available update : Microsoft Teams. Current version : 1.2.0.34161. Available version : 1.5.00.8070.
Available update : Cisco Webex Meetings. Current version : 39.9.2.116. Available version : 42.3.1.12.
Available update : Adobe Acrobat DC (64-bit). Current version : 21.011.20039. Available version : 22.001.20085.
Available update : Microsoft Visual C++ 2015 Redistributable (x86). Current version : 14.0.24215.1. Available version : 14.0.24516.0.
Available update : Microsoft Visual C++ 2013 Redistributable (x86). Current version : 12.0.30501.0. Available version : 12.0.40664.0.
```

OS: Windows 10
Edition: 21H2
Build: 19044.1526

C++ 2015-2019 installed, with 2015 and 2013 standalone packages as well.

**Comment by Romanitho** [comment]
Are you sure the apps are not installed on user profile ? that's weird.
Could you do a test for me please ? Install as admin an old version of 7zip (even 21.06). Try to run scheduled task as system and check if the script update the app to 21.07.
Thanks for that.

**Comment by Matt-13** [comment]
Seems to do the same thing unfortunately. Installed an older 7-zip (19.00)
`20:37:12 - No new update.`

**Comment by Romanitho** [comment]
It may have a link with this issue #39

**Comment by bebeidon** [comment]
> Any news about your issue ?

i did deploy the 1.18 preview and fixed it like that, no idea why the winget was broken before, i think it's a winget / micorsoft issue no bug in your script.

**Comment by Romanitho** [comment]
Could you try with WAU 1.7.1 please ? It might be fixed

**Comment by bebeidon** [comment]
there is no easy way to test it now in my environment as it is aleady fixed but thank you.
