### ISSUE TITLE
[Bug]: Install argument -UpdatesAtLogon and GPO setting

### ISSUE THREAD

**Issue by thenktor** [Romanitho/Winget-AutoUpdate#288]
### The problem

Hi,

after installing Winget-AutoUpdate with argument `-UpdatesAtLogon` the logon trigger is set as expected in the task scheduler.
But if GPO setting "Update at Logon" is also set, the logon trigger is set twice on next Winget-AutoUpdate run.

### What version of WAU has the issue?

1.16.1

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 22H2

### What version of winget are you using?

v1.4.10173

### Log information

```txt
11:32:44 - Activated WAU GPO Management detected, comparing...
11:32:44 - Changed settings detected and applied
```

**Comment by KnifMelti** [comment]
Can you in the task see a logon trigger twice?

**Comment by thenktor** [comment]
Yes, this is where I've noticed it.

**Comment by KnifMelti** [comment]
The `Changed settings detected and applied` in the log is when the WAU registry is compared to the Policy registry the first time WAU runs after installation and gets populated with all the correct values.

**Comment by KnifMelti** [comment]
https://github.com/Romanitho/Winget-AutoUpdate/releases/tag/v1.16.3
