### ISSUE TITLE
[Feature Request]: -ListPath is a directory

### ISSUE THREAD

**Issue by lazynooblet** [Romanitho/Winget-AutoUpdate#289]
### The request

I got confused and pointed -listpath to a url that ended in [..]/installed_apps.txt
Which failed. The error log just says it can't reach that URL, and I internally reply "why?"
I ended up tracing the code to find Test-ListPath appends the name of the file... ah so it wants a directory!

My feature request is to update the documentation with something like

> -ListPath is expecting a folder, and will append the needed file on the end for each request

**Comment by KnifMelti** [comment]
Sure, why not.
For me **ListPath**/**ModsPath** are paths, not files.. ..but documentation is good 👍
One also could build in an error handling stripping a leaf from the path...
