### ISSUE TITLE
[Feature Request]: Log file location

### ISSUE THREAD

**Issue by RonBartsch** [Romanitho/Winget-AutoUpdate#291]
### The request

Is it possible to add a parameter for the log file location?
I would like to have the log files in the C:\Programdata\Microsoft\Intune Management Extension\Logs folder

### Is your feature request related to a problem?

```txt
For troubleshooting it would be nice if I can easily gather the log files when needed from a device.

From Intune I can run the "Collect Diagnostics" and it would collect the log file(s) from the device for further investigation.
```

**Comment by KnifMelti** [comment]
Hi!
It's been proposed, and now it's requested.
https://github.com/Romanitho/Winget-AutoUpdate/discussions/256#discussioncomment-4710599

My own take on it would be a symlink creation based on the parameter for log file path (too many dependencies in the code and to keep third parts already defined collectors working)

**Comment by KnifMelti** [comment]
Maybe automatically create the symlink if `C:\Programdata\Microsoft\Intune Management Extension\Logs` exist...

**Comment by KnifMelti** [comment]
BTW: is the PATH  "IntuneManagementExtension" or "Intune Management Extension"?

**Comment by RonBartsch** [comment]
Thank you and you are right the correct path is:
C:\Programdata\Microsoft\IntuneManagementExtension\Logs

**Comment by KnifMelti** [comment]
https://github.com/Romanitho/Winget-AutoUpdate/releases/tag/v1.16.4

**Comment by RonBartsch** [comment]
Thank you very much works perfect now.
