### ISSUE TITLE
Wrong input for foregroundColor 

### ISSUE THREAD

**Issue by ElianeMegert** [Romanitho/Winget-AutoUpdate#295]
Hi

Just a very little bug but reporting anyway...in your write-log function you set the foregroundColor. At line Line 90 of Winget-Upgrade.ps1 you use a wrong color for the enum which causes an exception. (strangly) 'grey' needs to be 'gray' as per definition:
https://learn.microsoft.com/en-us/dotnet/api/system.consolecolor?view=net-7.0

![image](https://user-images.githubusercontent.com/50202255/224928378-611bf88b-9266-4754-85da-b514fdbbeb7e.png)

Just correct it to gray and and it will act as expected.

**Comment by KnifMelti** [comment]
In progress by #294

**Comment by Romanitho** [comment]
Thanks :)

**Comment by KnifMelti** [comment]
Now out:
https://github.com/Romanitho/Winget-AutoUpdate/releases/tag/v1.17.0
