### ISSUE TITLE
[Feature Request]: Installation timeout

### ISSUE THREAD

**Issue by FaserF** [Romanitho/Winget-AutoUpdate#300]
### The request

Currently on one client I have an issue with installing the latest Visual Studio Code Update via winget. The installation starts but never ends (killing the installer.exe works for WAU to get the exit code 1) Unless the machine gets restarted and then it starts over. This prevents other apps from getting updated.

I think the installation failed as VSCode still was running, but it should then not keep running forever.

if I find the time I will submit a PR, but for now something like this maybe could work (This is a part from my Intune App Install script):

```
function Start-Process-Function {
    param(
        [Parameter(Mandatory = $False, Position = 0, ValueFromPipeline = $false)]
        [System.String]
        $FilePath,

        [Parameter(Mandatory = $False, Position = 1, ValueFromPipeline = $false)]
        [System.String]
        $ArgumentList
    )

    $timeoutMinutes = 6
    $timeout = $timeoutMinutes * 60

    Write-ToLog -Warning 1 -LogText "Starting File $InstallMode of $FilePath with $ArgumentList with timeout of $timeoutMinutes Minutes."
    try {
        $proc = Start-Process -filePath $FilePath -ArgumentList $ArgumentList -PassThru -WindowStyle hidden
    }
    Catch {
        Write-ToLog -Warning 3 -LogText "Error $_ while starting $InstallMode process of $FilePath"
    }
    # wait up to $timeout seconds for normal termination
    $proc | Wait-Process -Timeout $timeout -ErrorAction SilentlyContinue -ErrorVariable timeouted
    $ExitCode = $proc.ExitCode

    if ($timeouted) {
        # terminate the process
        if (-not ([String]::IsNullOrEmpty($proc))) {
            $proc | Stop-Process
        }
        # Set ExitCode to TimeOut
        Write-ToLog -Warning 3 -LogText "$InstallMode went into timeout - Return Code $ExitCode of $FilePath"
        return "timeout"
    }
    elseif (($ExitCode -eq 0) -or ($ExitCode -eq 3010) -or ($ExitCode -eq 1641) -or ($ExitCode -eq 1707)) {
        Write-ToLog -Warning 1 -LogText "$InstallMode successful - Return Code $ExitCode of $FilePath"
        return $ExitCode
    }
    else {
        Write-ToLog -Warning 3 -LogText "$InstallMode failed - Return Code $ExitCode of $FilePath"
        return $ExitCode
    }
}

```

### Is your feature request related to a problem?

```txt
This issue prevents other apps from getting updated.
```

**Comment by Romanitho** [comment]
Hi,
Thanks for your support.
To workaround this, we implemented a random part in the list of apps to update. This wait, if an app fails to update, on next run the apps to update will get mixed. Not the best approach for sure, but it does the trick after few runs :)
The reason why we didn't use timeout is that we cannot really estimate the time for apps to "timeout" as it depends on apps, computers,...
in the meantime, @KnifMelti implemented a feature to run customized script regarding specific apps. This way, you can have a small powershell script that can kill visual studio before WAU tries to update the app for instance. You can find some example and share yours here: https://github.com/Romanitho/Winget-AutoUpdate/discussions/categories/mods 😊

**Comment by FaserF** [comment]
Thanks for the info, this explains why it worked on the next run for other apps but still was stuck at VSCode

I understand that WAU doesn’t know when an app update should finish, but wouldn’t it help to implement a timeout for example with 60 minutes? Haven’t found any app that took more than 25 minutes to update/install, so with this we should be on a safe side?

for the VSCode issue: thanks, with a mod it should fix this specific issue :)

**Comment by Romanitho** [comment]
In most scenarios 60 min timeout can be disadvantageous, because WAU runs at startup or at logon. This way, updates should run before users start their apps (in theory). In the queue, you could have other apps waiting that 60 min timeout and sometimes, with an autoupdate process, some apps can kill themselves on update.

**Comment by FaserF** [comment]
Yes, understood. From my side I can tell you, that WAU runs most of time time after most of my programs have already started. Due to Win11, a recent notebook and the feature that Win11 auto reloads Apps used before the last shutdown.

But still I understand the disadvantage, when using an app for 1 hour and then it suddenly gets killed.
Thanks for clearing me up

**Comment by Romanitho** [comment]
no worries, thanks for your feedback.
I think, the @KnifMelti mods feature could suit your needs
