### ISSUE TITLE
[Bug]: Winget-AutoUpdate Parameter "ListPath" URL Not Pulling

### ISSUE THREAD

**Issue by jbeck71380** [Romanitho/Winget-AutoUpdate#304]
### The problem

Hello!

I've been trying to get the parameter "ListPath" to work and I am running into some trouble. The logs say that WAU couldn't reach/find copies from XXX URL. I am hosting the list on GitHub and gave the directory (not the file) URL to GitHub. 

For example:
"https://raw.githubusercontent.com/MyGitHubRepo/Windows_Auto_Update/main"

the full URL is:
"https://raw.githubusercontent.com/MyGitHubRepo/Windows_Auto_Update/main/excluded_apps.txt"

I have also tried the non-raw URL for my GitHub repository and that failed too. 

What I would expect:
The script to append either "excluded_apps.txt" or "included_apps.txt" to the end of the URL and download/compare the file. But it fails. My GitHub repository is public and can be accessed by anyone.

Has anyone had any success in using GitHub to host the file?

### What version of WAU has the issue?

1.71.1

### What version of winget are you using?

1.4.10173

### Log information

```txt
10:31:09 - Running in System context
10:31:09 - Notification Level: SuccessOnly. Notification Language: English
10:31:09 - Checking internet connection...
10:31:09 - Connected !
10:31:11 - Winget Version: v1.4.10173
10:31:11 - WAU current version: 1.17.1
10:31:11 - WAU AutoUpdate is Enabled.
10:31:11 - WAU is up to date.
10:31:11 - WAU uses External Lists from: https://raw.githubusercontent.com/MyGitHubRepository/Windows_Auto_Update/main
10:31:11 - Couldn't reach/find/compare/copy from https://raw.githubusercontent.com/MyGitHubRepository/Windows_Auto_Update/main...
10:31:11 - List (black) is up to date.
10:31:11 - WAU uses Black List config
10:31:11 - Checking application updates on Winget Repository...
```

**Comment by KnifMelti** [comment]
Hi!
If you try (in a browser) to reach
https://raw.githubusercontent.com/MyGitHubRepo/Windows_Auto_Update/main/excluded_apps.txt
It will tell you 404 - the file doesn't exist

For this to work the returned header must contain the date/time stamp of the file etc, and I don't think GitHub acts like a regular web server.

**Comment by KnifMelti** [comment]
If I instead try https://raw.githubusercontent.com/McCownGordon/Windows_Auto_Update/main/excluded_apps.txt it reaches the file, but it doesn't return the time/date stamp in the header (thus not a standard web server):
```
$wc.OpenRead("https://raw.githubusercontent.com/McCownGordon/Windows_Auto_Update/main/excluded_apps.txt").Close()
$dateExternal = ([DateTime]$wc.ResponseHeaders['Last-Modified']).ToString("yyyy-MM-dd HH:mm:ss")
Cannot convert null to type "System.DateTime".
```
And without a  time/date stamp it can not be compared to the local file.

**Comment by KnifMelti** [comment]
One could try a different approach, if the date/time header doesn't exist then download it anyway...

**Comment by KnifMelti** [comment]
Should I try?

**Comment by jbeck71380** [comment]
It is an easy enough to move the file to another location such as OneDrive. I just thought it would be nice to host it on GitHub for easy version control. If it's not to difficult it might be worth the time to try, otherwise I'll just host it in a different location.

**Comment by KnifMelti** [comment]
#306

**Comment by KnifMelti** [comment]
https://github.com/Romanitho/Winget-AutoUpdate/releases/tag/v1.17.2

**Comment by jbeck71380** [comment]
@KnifMelti Thank you for updating the app - and so quickly. I downloaded the latest source code and it seems to be working beautifully. I appreciate your assistance! I'll be closing out this issue now :)
