### ISSUE TITLE
[Feature Request]: Make WAU available on winget

### ISSUE THREAD

**Issue by vguttmann** [Romanitho/Winget-AutoUpdate#318]
### The request

Automatically installing updates is cool and all, but it'd be even cooler if I could install this via winget so I knew this was up to date as well.

**Comment by FaserF** [comment]
Unfortunatly winget does not support deploying powershell Apps yet. We would need to convert the ps1 file to a exe

https://learn.microsoft.com/en-us/windows/package-manager/winget/#supported-installer-formats

**Comment by vguttmann** [comment]
Oh well, then this seems like more hassle than it's worth, didn't know Winget had that limitation

**Comment by Romanitho** [comment]
and WAU got its own auto-update job ;) so, install once with default settings and that's it.
