### ISSUE TITLE
Install itself and update over winget

### ISSUE THREAD

**Issue by iMonZ** [Romanitho/Winget-AutoUpdate#33]
Is it possible to add this package to winget so that it can update and install itself from it.

It would be really handy to just install and uninstall this package combined over this tool: 
https://github.com/Romanitho/Winget-Install

Thanks!

**Comment by Romanitho** [comment]
on latest version, the tool update itself by default ;)
If someone wants to package it in Winget Package, why not. Never tried to package a Winget package.

**Comment by iMonZ** [comment]
> on latest version, the tool update itself by default ;) If someone wants to package it in Winget Package, why not. Never tried to package a Winget package.

Sounds like a great idea.
If we use winget here so why aren't we installing this tool over it? (And update it as well.)
Then we only have one update check on the system a day and not 2-90

**Comment by Romanitho** [comment]
not sure powershell scripts are supported natively by Winget.

**Comment by Snakeulescu** [comment]
> > not enough skilled for that :/ by the way, if you had troubble with WAU update, try to reinstall it from the install script. Might resolve issues if you installed pre-release versions.
> 
> Thanks! Now I need to figure out how I can force reinstalling an app haha

Have you had any luck with this man? Now I saw your post :)

**Comment by Romanitho** [comment]
Maybe we can close this issue, as I guess will note be possible to manage PowerShell through Winget. And this project has an auto-update feature.
