### ISSUE TITLE
[Bug]: MegaLinter reports error.

### ISSUE THREAD

**Issue by Romanitho** [Romanitho/Winget-AutoUpdate#336]
### The problem

![image](https://user-images.githubusercontent.com/96626929/236148293-58b8d8fb-2e0a-42f2-971b-8a42803249ef.png)
@FaserF any idea ?

### What version of WAU has the issue?

N/A

### What version of winget are you using?

N/A

**Comment by Romanitho** [comment]
https://github.com/peter-evans/create-pull-request/issues/707 ?

**Comment by FaserF** [comment]
I will have a look into it, unfortunatly I dont think that the issue 707 you mentioned is the reason for it failing here, as we have already removed running on pushes and specified branches for PR runs
https://github.com/Romanitho/Winget-AutoUpdate/blob/main/.github/workflows/mega-linter.yml#L6

**Comment by nvuillam** [comment]
If you want to avoid this issue, you have 2 choices:
- Give write permissions by defining a Personal Access Token and store it in a PAT secret variable (see last note [here](https://megalinter.io/latest/configuration/#apply-fixes))
- Set APPLY_FIXES to `none` so it won't try to push a new commit with fixes :)

**Comment by Romanitho** [comment]
Thanks for your help.
Created a PAT secret variable as described in the link you shared. Nothing else to do? 😅

**Comment by nvuillam** [comment]
@Romanitho just run again MegaLinter job from an internal branch PR :)

Note: be careful who you give access to internal contributions, as they can have access to PAT value :)

**Comment by Romanitho** [comment]
Thanks for the note. I'm alone on the internal contributions. But as I'm not an GitHub expert, maybe I'll change for the second choice you gave :)

**Comment by nvuillam** [comment]
There is probably even a safer way , without using PAT: GitHub permissions ^^

We've not migrated ML scripts yet but that's worth the look:)

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by Romanitho** [comment]
merci.
So we need to adapt this a bit:
```
permissions:
  contents: write
  pull-requests: write
```

**Comment by nvuillam** [comment]
I ma currently trying that in MegaLinter internal MegaLinting

If it works it will be the default for the v7 to come :)

```yaml
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push, comment issues & post new PR
      # Remove the ones you do not need
      contents: write
      issues: write
      pull-requests: write
```

**Comment by Romanitho** [comment]
Will see if it does the thing :)

**Comment by nvuillam** [comment]
It works, but... after the new commit the workflows are not run again >_<

**Comment by Romanitho** [comment]
I had the same problem on my latest changes on #331

**Comment by nvuillam** [comment]
@Romanitho I found the way on MegaLinter own repo :)

Posted PR https://github.com/Romanitho/Winget-AutoUpdate/pull/351 with instructions !

**Comment by Romanitho** [comment]
Now, I have this 😅
![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/96626929/cf9d6598-874d-45fe-a95b-db410c382c73)

**Comment by nvuillam** [comment]
Seems you have hardcoded credentials 😅
You can either remove it or disable the linter ^^

**Comment by Romanitho** [comment]
Not sure. Don't even know how to troubleshoot that 😅
saying file .git\config Line 11...

**Comment by FaserF** [comment]
@Romanitho I just had a look into it and it looks like somewhere local on your machine are credentials stored in plain text.
So the good thing is, no credentials have been leaked to github, the bad one is I cant fix it for you.

You may want to have a look into your local Git folder, where you are working, there should be a (hidden) .git folder containing a config file. Thats were your credentials are. You may want to delete your local git files and then do a git pull again to get the latest files, which hopefully then should not safe your credentials in plain text.

If this does not work I will be deactivating that linter for you.

**Comment by Romanitho** [comment]
Hi, thanks for your help.
I've done that, here is what I have, and no creds or anything:
![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/96626929/140a7fbb-6976-4add-b166-19e1bbd16810)

**Comment by nvuillam** [comment]
You can also conssider this issue as a false positive and define the linter to be blocking after 2 issues found , by adding the following in your .mega-linter.yml

`REPOSITORY_TRUFFLEHOG_DISABLE_ERRORS_IF_LESS_THAN: 2`

**Comment by Romanitho** [comment]
Thanks, this is probably what I'll do.

**Comment by Romanitho** [comment]
https://github.com/Romanitho/Winget-AutoUpdate/commit/dcec8882ea2345383ed48f3b9d00e55ff72d9d26
