### ISSUE TITLE
[Feature Request]: Review the Winget update part in case of fail

### ISSUE THREAD

**Issue by Romanitho** [Romanitho/Winget-AutoUpdate#337]
### The request

When we started to implement WAU, we have added a feature to run a `Winget install [AppID]` in case `Winget upgrade [AppID]` fails to try to install the update in another way.
The latest Winget versions detect if the AppID is already installed and try to update the app even with the `install` command.
- Should we use `Winget install [AppID] --force`?
- Should we remove this part and only keep the `Winget upgrade [AppID]` command?
- Is there any security risk with `--force`?
- Should we add an argument option like `-ForceInstallOnFail` to let people choose the behavior they want?

**Comment by Romanitho** [comment]
@KnifMelti as you're from the beginning 😅

**Comment by Romanitho** [comment]
Maybe we could just remove that part, as i'm not sure it really helps anyway

**Comment by KnifMelti** [comment]
I'm recovering from a stomach illness in the moment, don't have the energy to activate my brain. Sorry!

**Comment by Romanitho** [comment]
No problem, take care ;)

**Comment by KnifMelti** [comment]
The less we affect the winget process, the better!
Failed installs/upgrades is a common thing with the defined manifests of an app, something we can't do anything about.
`-UninstallOnFail` is a thing to consider (even if it can be done with mods), but if uninstalled before it can't be upgraded `No installed package found matching input criteria.`
Example: `EclipseAdoptium.Temurin.11.JRE` (wrong upgrade code in manifest)

**Comment by Romanitho** [comment]
I agree. But doing it with mods would mean to create mods for each app, no ?
And the `-UninstallOnFail` is only to configure the retry way of the update part (upgrade first, and if it fails, uninstall and install new) so no issue with the upgrade command.

**Comment by Romanitho** [comment]
Anyway, I had few apps that failed to update recently and the `--force` argument on the install command on retry worked perfectly... So for me, this is the workaround I guess.

**Comment by KnifMelti** [comment]
Excellent! Implement.
