### ISSUE TITLE
Packaging as a win32 app? - Intune deployment

### ISSUE THREAD

**Issue by Snakeulescu** [Romanitho/Winget-AutoUpdate#34]
Hi I was wondering if you might have used this to deploy it through Intune/SCCM and am wondering what you used for a detection method or uninstall script.

From what I gather I can package the script and use the install.bat as an installation command. 

Thanks for this btw, I have been struggling to find a way to use winget in a corp environment.

**Comment by iMonZ** [comment]
Duplicate: https://github.com/Romanitho/Winget-AutoUpdate/issues/33

**Comment by Romanitho** [comment]
hi. you can put whatever you want as detection method, for example the about config file, or poershell script to get the installed version.
for uninstall, just remove the folder in programdata and the scheduled tasks. I'll try to create unintaller when i got time.
