### ISSUE TITLE
[Bug]: Internet connectivity test is randomly failing

### ISSUE THREAD

**Issue by MBstatsara** [Romanitho/Winget-AutoUpdate#344]
### The problem

We seem to get multiple reports of users with the no internet connectivity pop up.
Yet they are most definitely online as they are accessing the PCs over the internet!

Seems to happen randomly, and this prevents apps updating, is there anything I can diagnose for the network issues?

### What version of WAU has the issue?

1.15.1

### What version of Windows are you using (ex. Windows 11 22H2)?

Microsoft Windows 10 Enterprise 10.0.19045

### What version of winget are you using?

v1.4.10173

##################################################
#     CHECK FOR APP UPDATES - 09/05/2023
##################################################
13:09:04 - Running in User context
13:09:04 - Notification Level: Full. Notification Language: English
13:09:04 - Checking internet connection...
13:14:05 - Notify 'No connection' sent.
13:39:13 - Timeout. No internet connection !
13:39:16 - End of process!

##################################################
#     CHECK FOR APP UPDATES - 09/05/2023
##################################################
15:50:05 - Running in System context
15:50:05 - Notification Level: Full. Notification Language: English
15:50:05 - Checking internet connection...
15:55:41 - Notify 'No connection' sent.
16:20:51 - Timeout. No internet connection !
16:20:56 - Starting WAU in User context

##################################################
#     CHECK FOR APP UPDATES - 09/05/2023
##################################################
16:20:57 - Running in User context
16:20:57 - Notification Level: Full. Notification Language: English
16:20:57 - Checking internet connection...
16:25:59 - Notify 'No connection' sent.
16:51:07 - Timeout. No internet connection !
16:51:10 - End of process!

**Comment by Romanitho** [comment]
> https://github.com/Romanitho/Winget-AutoUpdate/blob/v1.15.1/Winget-AutoUpdate/functions/Test-Network.ps1

this function is used to test network connectivity to GitHub:
```
$URLtoTest = "https://raw.githubusercontent.com/Romanitho/Winget-AutoUpdate/main/LICENSE"
```
it checks the content of the license file

**Comment by KnifMelti** [comment]
Maybe `$URLcontent = ((Invoke-WebRequest -URI $URLtoTest).content)` should have `-UseBasicParsing` as a parameter?
