### ISSUE TITLE
[Bug]: GPO overwrite all settings

### ISSUE THREAD

**Issue by Romanitho** [Romanitho/Winget-AutoUpdate#346]
### The problem

There is a problem with GPO management. It overwrite ALL configs. For instance, I install WAU like this:
`Winget-AutoUpdate-Install.ps1 -Silent -DoNotUpdate -DisableWAUAutoUpdate -UpdatesAtLogon`

I select this GPOs for testing:
```
Activate WAU GPO Management: Enabled
User context execution: Enabled
```

On next run, WAU get updated, even if I installed it with `-DisableWAUAutoUpdate`. GPO is not set, so it should not change the way I installed WAU the first time.

### What version of WAU has the issue?

1.17.3

### What version of Windows are you using (ex. Windows 11 22H2)?

Win10/11 latest

### What version of winget are you using?

v1.4.10173

### Log information

```txt
##################################################
#     CHECK FOR APP UPDATES - 10/05/2023
##################################################
14:01:39 - Running in System context
14:01:39 - Activated WAU GPO Management detected, comparing...
14:01:39 - No Changed settings detected
14:01:39 - Notification Level: Full. Notification Language: Français
14:01:39 - Checking internet connection...
14:01:39 - Connected !
14:01:48 - Winget Version: v1.4.10173
14:01:48 - WAU current version: 1.17.3
14:01:48 - WAU AutoUpdate is Enabled.
14:01:48 - WAU Available version: 1.17.4
14:01:54 - Downloading the GitHub Repository version 1.17.4
14:01:54 - Unzipping the WAU Update package
14:01:56 - Updating WAU...
14:01:56 - Done. Cleaning temp files...
14:01:56 - WAU Update completed.
14:02:01 - Re-run WAU
```

**Comment by Romanitho** [comment]
@KnifMelti 
I'm working on another approach to handle GPO that might cover this issue.

**Comment by KnifMelti** [comment]
Bug confirmed (workaround - Enable **Disable WAU AutoUpdate** in GPO), waiting @Romanitho

**Comment by Romanitho** [comment]
Still on it, but busy atm

**Comment by Romanitho** [comment]
Time is missing, but still on it, sorry for the delay

**Comment by Romanitho** [comment]
Still needed. For me GPO should override settings without changing the config in the WAU regestry

**Comment by Romanitho** [comment]
We should prioritize this case.
Then, start a talk about ServiceUI as some apps fails without it (lke dotPDNLLC.paintdotnet) and decide if we should try to implement it, as it should not be complicated.

**Comment by KnifMelti** [comment]
I've developed a better routine in https://github.com/KnifMelti/Winget-AutoUpdate/tree/GPO-enhancements
But, I need some time, not really there yet (funerals etc...)

**Comment by Romanitho** [comment]
yes, i've seen. But not sure to understand why you save it to an XML

**Comment by KnifMelti** [comment]
For later comparing in `Get-Policies.ps1`:

```
foreach ($Key in $WAUPolicies_HashTable.Keys)
{
    switch ($Key)
    {
        # AzureBlobSASURL
        "WAU_AzureBlobSASURL"
        {
            if ($null -eq $($WAUPolicies_HashTable[$Key]) -and ($($WAUPolicies_HashTable[$Key]) -ne $($WAUConfigDefault_HashTable[$Key])))
            {
                Write-Host "$Key = Not Configured in GPO and different from installation | $($WAUConfigDefault_HashTable[$Key]) - Reset to Default"
            }
            elseif ($($WAUPolicies_HashTable[$Key]) -ne $($WAUConfig_HashTable[$Key]))
            {
                Write-Host "$Key = $($WAUPolicies_HashTable[$Key]) | $($WAUConfig_HashTable[$Key]) - Changing Value"
            }
            else
            {
                Write-Host "$Key = Values are the same ($($WAUPolicies_HashTable[$Key]))"
            }
        }

```

**Comment by Romanitho** [comment]
I think we can do that much simpler. I'll draft something today to show you my idea.
