### ISSUE TITLE
[Bug]: installed with machine scope but updates run in user context only

### ISSUE THREAD

**Issue by bandizsolt** [Romanitho/Winget-AutoUpdate#362]
### The problem

Hi!

When I install ungoogled chromium with this:

`winget install -e --id eloston.ungoogled-chromium --interactive --scope machine --architecture x64`

then it install to the program files, but Winget-AutoUpdate only update in user context only, I do not know, where to start to debug, how to check, can you please guide, how to analyze this problem?

Thank you!

### What version of WAU has the issue?

latest

### What version of Windows are you using (ex. Windows 11 22H2)?

windows 10 / 11 latest (22H2)

### What version of winget are you using?

latest stable (v1.5.1881)

**Comment by Romanitho** [comment]
yes sorry, haven't seen you've put it ^^ tired at the moment, need holidays 😅

WAU system scope detection is realized by this function (running in system context):
https://github.com/Romanitho/Winget-AutoUpdate/blob/main/Winget-AutoUpdate/functions/Get-WingetSystemApps.ps1

**Comment by Romanitho** [comment]
Hello.
The problem comes directly from Winget itself. Running in system context is not the same as running with admin user.
Then, the function `Get-WingetSystemApps` simply lists the apps that can be detected under the context it is executed from.
So, the issue here is not part of WAU.

**Comment by Romanitho** [comment]
create a scheduled task that run with system rights. Use the Winget path from `get-wingetcmd` function

**Comment by AndrewDemski-ad-gmail-com** [comment]
> Thank you for clarifying things. So, there is a system context that is completely different from the user and admin contexts. How could this system context be tested?

Please use psexec, that tool can launch processes in system context.
https://learn.microsoft.com/en-us/sysinternals/downloads/psexec

Enjoy testing @bandizsolt

**Comment by KnifMelti** [comment]
> Please use psexec

A more modern tool:
https://www.nirsoft.net/utils/advanced_run.html
