### ISSUE TITLE
[Feature Request]: Add "Run with highest priviledges" to user context

### ISSUE THREAD

**Issue by drtomasso** [Romanitho/Winget-AutoUpdate#364]
### The request

Is it possible to add "Run with highest priviledges" on the scheduled task running in user context? This would allow apps installed in user context which requires admin priviledges to update, to install the update without UAC prompt.

**Comment by Romanitho** [comment]
Not sure it will help for users that don't have admin rights.

**Comment by drtomasso** [comment]
You're right, it would only help for users having admin right. The goal would be to avoid any user prompts, so if there's a way to skip packages that requires admin rights, that too would be an option. Unfortunatelly, I can't find anything like that with winget.

**Comment by Romanitho** [comment]
This is why we have created WAU ^^
normally, no user prompt, apps are updated in system context.

**Comment by Romanitho** [comment]
exactly.

**Comment by drtomasso** [comment]
Ok, then there may be little use for this feature. It appeared when I startet WAU manually. It found some apps in user context which required admin rights to update, causing a couple of prompts. If the task was run with highest rights (as this user is also admin), it wouldn't have prompt for UAC.

This would only solve a small case and not a universal solution, so feel free to either close the request or, if you see the use case, add this in a future update.

Anyways, thank you for your work and for swift response

**Comment by Romanitho** [comment]
You could reinstall apps in system context with winget, then they should be updated with WAU :)

You could also adapt script or scheduled tasks to match your needs.

Thanks for your comments ;)
