### ISSUE TITLE
WAU repeatedly updates Microsoft.VCRedist.2012.x64

### ISSUE THREAD

**Issue by t0m5k1** [Romanitho/Winget-AutoUpdate#373]
### The problem

Since yesterday it seems WAU keeps trying to upgrade Microsoft.VCRedist.2012.x64 even though it is reporting a successful upgrade/install.

Log: [updates.log](https://github.com/Romanitho/Winget-AutoUpdate/files/12206741/updates.log)

### What version of WAU has the issue?

1.17.6

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 10 22H2 19045.3271

### What version of winget are you using?

1.5.1881

### Log information

```txt
Log extract from yesterday:
23:07:46 - Updating Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.50727 from 11.0.50727.1 to 11.0.61030.0...
23:07:50 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.VCRedist.2012.x86'   ##########


Log extract from this morning:
10:05:36 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Microsoft.VCRedist.2012.x86'   ##########
10:05:36 - Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.50727 updated to 11.0.61030.0 !
```

### Additional information

Foxit reader seems to fail but that doesn't really bother me

**Comment by Romanitho** [comment]
Hi,
Can you have a look on you installed program ? you should have 2 versions of the same apps. WAU detects that Winget reports an available update and try to update apps, and of course WAU detects that the update succeed

**Comment by t0m5k1** [comment]
So I need to remove the duplicates manually?
or should I just keep collecting these?

Seems odd that the old version is left when all other apps only has 1 version installed.

I've gone through and uninstalled the duplicates

**Comment by Romanitho** [comment]
i agree, odd to have multiple version, but this is either Winget issue or problem with the application itself. WAU doesn't handle replacement or previous uninstall. Just using winget to upgrade apps.

**Comment by KnifMelti** [comment]
You could also use the `mod`-function.
In this case create a `Microsoft.VCRedist.2012.x86-preinstall.ps1` (copy `_AppID-template.ps1`) under `mods` and therein add the name of the version that should be uninstalled in `$AppUninst = @("Microsoft Visual C++ 2012 Redistributable (x86) - 11.0*")` - uninstalling all v11 versions of x86.
https://github.com/abbodi1406/vcredist/blob/master/source_links/README.md#microsoft-visual-c-2012-redistributables---v11

I tested with `Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.50727` installed and it uninstalled before installing the latest correctly.

**Comment by KnifMelti** [comment]
I often find that the different VCRedist leaves an registry entry under:
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall`
And, that even if the manifests say: `UpgradeBehavior: uninstallPrevious`
In those cases you have to delete the reg entry manually.
Hence, my exclusion list in **excluded_apps.txt**:
```
Microsoft.dotnet
Microsoft.DotNet.AspNetCore.6
Microsoft.DotNet.Runtime.3_1
Microsoft.DotNet.SDK.3_1
Microsoft.DotNet.SDK.6
Microsoft.Edge
Microsoft.EdgeWebView2Runtime
Microsoft.Office
Microsoft.OneDrive
Microsoft.Teams
Microsoft.VCRedist.2005.x64
Microsoft.VCRedist.2005.x86
Microsoft.VCRedist.2012.x64
Microsoft.VCRedist.2012.x86
Microsoft.VCRedist.2013.x64
Microsoft.VCRedist.2013.x86
Microsoft.VC++2013Redist-x64
Microsoft.VC++2013Redist-x86
Microsoft.VCRedist.2015+.x64
Microsoft.VCRedist.2015+.x86
Microsoft.VC++2015-2019Redist-x64
Microsoft.VC++2015-2019Redist-x86
Microsoft.VC++2015-2022Redist-x64
Microsoft.VC++2015-2022Redist-x86
Microsoft.WindowsSDK
```

**Comment by Romanitho** [comment]
Thanks @KnifMelti for your details
