### ISSUE TITLE
[Bug]: Random closeup/crash

### ISSUE THREAD

**Issue by Pocokk** [Romanitho/Winget-AutoUpdate#375]
### The problem

It started the update process, manage to download a few files and then just out of nowhere without warning message or issue, the .bat installer just crashed.

### What version of WAU has the issue?

1.17.6

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 10 22H2

### What version of winget are you using?

 1.5.1881

### Log information

```txt
##################################################
#     CHECK FOR APP UPDATES - 2023-07-29
##################################################
20:28:41 - Running in User context
20:28:41 - Notification Level: Full. Notification Language: English
20:28:41 - Checking internet connection...
20:28:41 - Connected !
20:28:44 - Winget Version: v1.5.1881
20:28:44 - WAU current version: 1.17.6
20:28:44 - WAU uses Black List config
20:28:44 - Checking application updates on Winget Repository...
20:28:47 - An unusual thing happened (maybe all apps are upgraded):

   - 
   \ 
   | 
   / 
   - 
   \ 
   | 
   / 
   - 
                                                                                                                        
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command: 
0x8a15000f : Data required by the source is missing

20:28:47 - No new update.
20:28:47 - End of process!
```

**Comment by Romanitho** [comment]
Not sure it comes from WAU.
Try reinstall. You could even try the v1.17.5 that will update to 1.17.6 and reset sources.

**Comment by Pocokk** [comment]
Alright. 

Also side-question: it it possible to somehow know IN ADVANCE in the CMD window what apps will be updated? It just starts the process and then finishes without any acknowledgment, I can only look at the log file afterwards.

**Comment by Romanitho** [comment]
It's in the pipe. But time is missing.
