### ISSUE TITLE
[Bug]: WAU never starts in user context

### ISSUE THREAD

**Issue by CodingColibri** [Romanitho/Winget-AutoUpdate#378]
### The problem

Hello! 

I am using WAU with a Whitelist and reinstalled it today using the -InstallUserContext Command. It started logging "Starting WAU in User context" which is new but nothing happens after that and the application that is installed in user context and on the whitelist does not receive any updates (Zoom). Also no changes after multiple reboots. 

 I do not know, where to start to debug, how to check, can you please guide, how to analyze this problem?

Thanks! 

### What version of WAU has the issue?

1.17.7

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 10 22H2

### What version of winget are you using?

v1.5.2201

### Log information

```txt
**Out of the log:** 
06:00:21 - No new update.
06:00:24 - User logged on, get a list of installed Winget apps in System context...
06:00:30 - Starting WAU in User context
```

**Comment by Romanitho** [comment]
Hi,
Can you check in your scheduled tasks that "Winget-AutoUpdate-UserContext" correctly created ?
