### ISSUE TITLE
[Bug]: PowerShell Core Incompatibility

### ISSUE THREAD

**Issue by gabriel-vanca** [Romanitho/Winget-AutoUpdate#379]
### The problem

(This is further to the problem at https://github.com/Romanitho/Winget-AutoUpdate/issues/113)

I cannot install WAU using PowerShell Core because of a certain incompatible command.

This is what is causing the problem:

```
	$TestWinGet = Get-AppxProvisionedPackage -Online | Where-Object { $_.DisplayName -eq "Microsoft.DesktopAppInstaller" }

    #Current: v1.5.1881 = 1.20.1881.0 = 2023.707.2257.0
    If ([Version]$TestWinGet.Version -ge "2023.707.2257.0") {
```

To be compatible, this should be replaced with:

```
	$TestWinGet = Get-AppPackage -name "Microsoft.DesktopAppInstaller"

    #Current: v1.5.1881 = 1.20.1881.0 = 2023.707.2257.0
    If ([Version]$TestWinGet.Version -ge "1.20.1881.0") {
```

### What version of WAU has the issue?

latest

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 22H2

### What version of winget are you using?

latest

**Comment by KnifMelti** [comment]
Incompatible? Just installed in MSB after installing PowerShell Core 7...

![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/102996177/b85a09f4-6a8b-4a55-a8ba-63d253eac77b)
