### ISSUE TITLE
[Bug]Get-WingetCmd can return winget from a user while running from the system context

### ISSUE THREAD

**Issue by SirBeredan** [Romanitho/Winget-AutoUpdate#387]
### The problem

Recently installed WAU and tried running it under the system context via the schedule task created. 
This was however not working when reviewing the log, however while executing it under the user context was working as intended.

When run from system context it was unable to execute the file winget.exe that had been set by the $Script:Winget
On closer inspection it was due to Get-command returning the normal users Winget instance and being the first item in the if statement.

![get-commandUnderSystemContext](https://github.com/Romanitho/Winget-AutoUpdate/assets/12568092/a40b6375-bde5-44ff-a4e2-ec38aa4e4d85)

I would like to suggest something like the below to avoid this being a possible issue in the future.

```powershell
#Function to get the winget command regarding execution context (User, System...)

Function Get-WingetCmd {

    #Get WinGet Path (if admin context)
    # Includes Workaround for ARM64 (removed X64 and replaces it with a wildcard)
    $ResolveWingetPath = Resolve-Path "$env:ProgramFiles\WindowsApps\Microsoft.DesktopAppInstaller_*_*__8wekyb3d8bbwe" | Sort-Object { [version]($_.Path -replace '^[^\d]+_((\d+\.)*\d+)_.*', '$1') }
    if ($ResolveWingetPath) {
        #If multiple version, pick last one
        $WingetPath = $ResolveWingetPath[-1].Path
    }

    #If Running under System or Admin context obtain Winget from Program Files
    if((([System.Security.Principal.WindowsIdentity]::GetCurrent().User) -eq "S-1-5-18") -or ($WingetPath)){
        if (Test-Path "$WingetPath\winget.exe") {
            $Script:Winget = "$WingetPath\winget.exe"
        }
    }else{
        #Get Winget Location in User context
        $WingetCmd = Get-Command winget.exe -ErrorAction SilentlyContinue
        if ($WingetCmd) {
            $Script:Winget = $WingetCmd.Source
        }
    }

    If(!($Script:Winget)){
        Write-ToLog "Winget not installed or detected !" "Red"
        return $false
    }

    #Run winget to list apps and accept source agrements (necessary on first run)
    & $Winget list --accept-source-agreements -s winget | Out-Null

    #Log Winget installed version
    $WingetVer = & $Winget --version
    Write-ToLog "Winget Version: $WingetVer"

    return $true

}
```

### What version of WAU has the issue?

1.17.7

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 22H2

### What version of winget are you using?

v1.5.2201

### Log information

```txt
##################################################
#     CHECK FOR APP UPDATES - 7/09/2023
##################################################
22:07:30 - Running in System context
22:07:30 - Running Post Update actions:
22:07:30 - -> Checking prerequisites...
22:07:31 - -> Prerequisites checked. OK
22:07:31 - -> Checking if Winget is installed/up to date
22:07:31 - -> WinGet is Installed/up to date
22:07:31 - -> Winget sources reseted.
22:07:31 - -> ListPath setting was missing. Fixed with empty string.
22:07:31 - -> ModsPath setting was missing. Fixed with empty string.
22:07:31 - -> Checking Mods Directory:
22:07:31 - -> The mods directory was already secured!
22:07:31 - -> C:\ProgramData\Winget-AutoUpdate\Version.txt removed.
22:07:31 - Post Update actions finished
22:07:31 - Notification Level: Full. Notification Language: English
22:07:31 - Checking internet connection...
22:07:31 - Connected !
22:07:32 - Winget Version: 
22:07:32 - WAU current version: 1.17.7
22:07:32 - WAU AutoUpdate is Enabled.
22:07:32 - WAU is up to date.
22:07:32 - WAU uses Black List config
22:07:32 - Checking application updates on Winget Repository...
22:07:32 - An unusual thing happened (maybe all apps are upgraded):

22:07:32 - No new update.
22:07:33 - User context execution not installed...
22:07:33 - End of process!

VS

##################################################
#     CHECK FOR APP UPDATES - 7/09/2023
##################################################
21:42:19 - Running in User context
21:42:19 - Notification Level: Full. Notification Language: English
21:42:19 - Checking internet connection...
21:42:19 - Connected !
21:42:26 - Winget Version: v1.5.2201
21:42:26 - WAU current version: 1.17.7
21:42:26 - WAU uses Black List config
21:42:26 - Checking application updates on Winget Repository...
```

**Comment by KnifMelti** [comment]
This is what I get using the same OS/commands:
![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/102996177/b8d936dd-5614-40c4-94b9-d5464b05b8b1)

**Comment by KnifMelti** [comment]
Tips: `if ((([System.Security.Principal.WindowsIdentity]::GetCurrent().User) -eq "S-1-5-18") -or ($WingetPath))` can be shortened to `if (($null -eq ${env:=::}) -or ($WingetPath))`

**Comment by SirBeredan** [comment]
> I agree with @KnifMelti you should get an error with the `get-command winget.exe` under system context

I understand that it's not necessarily normal behaviour but as you can see above in my screenshot it can occur. 

However it doesn't necessarily make sense to pull the path that you intend to use under system context and then while under system context try pulling the get-command while under system context to begin with.

Suggested code above means it will never hit the unneeded get-command function if running under system. This is how I have fixed the issue on my system.

**Comment by Romanitho** [comment]
Yes, make sense. Feel free to PR your changes to get credited 👍🏻

**Comment by SirBeredan** [comment]
Fixed under https://github.com/Romanitho/Winget-AutoUpdate/pull/389
