### ISSUE TITLE
[Bug]: winget package is oudated (1.7.1 instead of 1.9.1)

### ISSUE THREAD

**Issue by the-project-group** [Romanitho/Winget-AutoUpdate#397]
### The problem

First of all thanks for the hard work!

I just installed WiGUI using winget install... But on start I get a notification about 1.9.1 being the current version.
So I assume the package is outdated?

![CleanShot 2023-09-15 at 13 41 10@2x](https://github.com/Romanitho/Winget-AutoUpdate/assets/127997549/442effa5-7691-447e-8057-0c042b04e034)

https://github.com/microsoft/winget-pkgs/tree/86ec240d7d66bf6835bdaff15bac28c8ce127fd4/manifests/r/Romanitho/WiGUI

### What version of WAU has the issue?

1.7.1

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 22H"

### What version of winget are you using?

v1.20.2201.0

**Comment by Romanitho** [comment]
Yes, package is outdated on Winget. But i'm not the maintainer of this :)

**Comment by FaserF** [comment]
Please use this issue template to report outdated winget apps:

Nevertheless, I am also not the maintainer of this (the great thing about winget is there is no real maintainer, so everyone can just update and submit new apps), but I have just updated the package at winget: 
https://github.com/microsoft/winget-pkgs/pull/122920

Once accepted by Microsoft you will recieve it automatically via Winget-AutoUpdate

**Comment by KnifMelti** [comment]
https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/Romanitho/WiGUI/1.9.1

**Comment by KnifMelti** [comment]
...but, I had to:

- Edit the Security on C:\Program Files\WinGet\Packages\Romanitho.WiGUI_Microsoft.Winget.Source_8wekyb3d8bbwe\WiGui.exe (adding Users R/W)
- Unblock WiGui.exe (downloaded from Internet

Seems like the Portable thing in WinGet isn't really there...
