### ISSUE TITLE
Error when installing (The conversion specified is invalid)

### ISSUE THREAD

**Issue by leochras** [Romanitho/Winget-AutoUpdate#4]
I started install.bat (as administrator) from the most recent version (1.4.0) and ran into this error. The error message says something like "The conversion specified is invalid"
Is this normal, or am I doing something wrong?

![image](https://user-images.githubusercontent.com/16163571/154839345-2812c2f3-9f25-4963-89e7-becd32099ba7.png)

**Comment by leochras** [comment]
Also, it tries to install VC_redist.x64 every time I run it? Shouldn't it be installed after the first time?

**Comment by leochras** [comment]
I don't know if the PowerShell script is supposed to do the same thing, but for me, it seems to:

![image](https://user-images.githubusercontent.com/16163571/154840193-1499ad39-536c-4bfd-8b2c-c0748055b418.png)

**Comment by Romanitho** [comment]
I tried to reinstall from install.bat and it worked for me.
Are you 32 or 64 bits ?

**Comment by Romanitho** [comment]
It looks like your powershell is not able to find some registry keys we try to get to detect if your system has MS Visual C++ 2019 already installed. That's why probably it runs the installation everytime.

**Comment by leochras** [comment]
> I tried to reinstall from install.bat and it worked for me. Are you 32 or 64 bits ?

I am on a 64 bit System

> It looks like your powershell is not able to find some registry keys we try to get to detect if your system has MS Visual C++ 2019 already installed. That's why probably it runs the installation everytime.

Is there a way to fix that?

**Comment by Romanitho** [comment]
Can you run this PowerShell command ?
`Get-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*`

**Comment by leochras** [comment]
same error

`Get-ItemProperty: Unable to cast object of type 'System.Int64' to type 'System.Int32'`

**Comment by Romanitho** [comment]
Something strange on your machine.

Could you try this one ?

`Get-Item HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*, HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Where-Object { $_.GetValue("DisplayName") -like "Microsoft Visual C++*2019*"}`

**Comment by leochras** [comment]
seems to run fine:


```
    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall

Name                           Property
----                           --------
{2c673fb6-3e65-4751-965d-33d30 BundleCachePath      : C:\ProgramData\Package
b68a8a6}                       Cache\{2c673fb6-3e65-4751-965d-33d30b68a8a6}\VC_redist.x64.exe
                               BundleUpgradeCode    : {{C146EF48-4D31-3C3D-A2C5-1E91AF8A0A9B}}
                               BundleAddonCode      : {}
                               BundleDetectCode     : {}
                               BundlePatchCode      : {}
                               BundleVersion        : 14.29.30139.0
                               BundleProviderKey    : VC,redist.x64,amd64,14.29,bundle
                               BundleTag            :
                               EngineVersion        : 3.10.4.4718
                               DisplayIcon          : C:\ProgramData\Package
                               Cache\{2c673fb6-3e65-4751-965d-33d30b68a8a6}\VC_redist.x64.exe,0
                               DisplayName          : Microsoft Visual C++ 2015-2019 Redistributable (x64) -
                               14.29.30139
                               DisplayVersion       : 14.29.30139.0
                               Publisher            : Microsoft Corporation
                               ModifyPath           : "C:\ProgramData\Package
                               Cache\{2c673fb6-3e65-4751-965d-33d30b68a8a6}\VC_redist.x64.exe" /modify
                               NoElevateOnModify    : 1
                               QuietUninstallString : "C:\ProgramData\Package
                               Cache\{2c673fb6-3e65-4751-965d-33d30b68a8a6}\VC_redist.x64.exe" /uninstall /quiet
                               UninstallString      : "C:\ProgramData\Package
                               Cache\{2c673fb6-3e65-4751-965d-33d30b68a8a6}\VC_redist.x64.exe"  /uninstall
                               Resume               : 3
                               Installed            : 1
```

**Comment by leochras** [comment]
That fixed the installation error, thanks!
