### ISSUE TITLE
[Feature Request]: Retry Install "Install-Prerequisites " and  "Install-WinGet" / fixing missing Config folder

### ISSUE THREAD

**Issue by user1722** [Romanitho/Winget-AutoUpdate#406]
### The request

I had 2 Problems and created fixes for it. 
I dont know if other had it and if it helps:

First because of missing firewall rules etc or bad connection sometimes some installations from the:
   	Install-Prerequisites
	Install-WinGet
In the Winget-AutoUpdate-Install.ps1 did not work probably so i did add them as extra general funktions and call them as error handling in:
Winget-Upgrade.ps1 

Also Other Problem

I had sometimes the Folder Config missing. 
So i did recreate it in the Confirm-Installation.ps1 

My code is not the best and other can Probably fix it up but maybe it can be added.

### Is your feature request related to a problem?

```txt
In Winget-Upgrade.ps1 at the end 
  else {
	Write-ToLog "Critical: Winget Komponenten Fehlen" "red"
   	Install-Prerequisites
	Install-WinGet
	$TestWinget = Get-WingetCmd
	if ($TestWinget) {

	Write-ToLog "Critical: Winget wurde Nachinstalliert und ist beim naechsten mal einsetzbar" "red"
	}

	else {

        Write-ToLog "Critical: Winget not installed or detected and couldnt be installed, exiting..." "red"
        New-Item "$WorkingDir\logs\error.txt" -Value "Winget not installed or detected and couldnt be installed" -Force
        Write-ToLog "End of process!" "Cyan"
        Exit 1
    	}



In Confirm-Installation.ps1 at the start

	$ConfigDir = Join-Path -Path $WorkingDir -ChildPath "Config"
	# Überprüfe, ob das Verzeichnis existiert
	if (-not (Test-Path -Path $ConfigDir -PathType Container)) {
    # Das Verzeichnis existiert nicht, also legen wir es an
    New-Item -Path $ConfigDir -ItemType Directory
    Write-Host "Das Verzeichnis $ConfigDir wurde erfolgreich erstellt."
	}
	else {
    Write-Host "Das Verzeichnis $ConfigDir existiert bereits."
	}
```

**Comment by user1722** [comment]
And a other Question :D 
In the Update-App.ps1  do we need now a --source winget  option ? or general source option 
In the other Winget-Install/winget-install.ps1 von Romanitho he added the -s winget to his script because sometimes Winget seems to have problems now without the source.

**Comment by KnifMelti** [comment]
> I had 2 Problems and created fixes for it.
> I dont know if other had it and if it helps:

Hello (and thanks for reporting/engaging in this project)!
To my knowledge, the `config `folder nowadays is only used to save the `notif.xml` for Toast messages and is automatically created when they appear.

The forcing of another try to install could be useful if the scenario you described is an issue (but I've never had/heard of anyone having that problem until now).
You could end a successful install with (to directly run `winget-upgrade.ps1` again):
```
               Write-ToLog 'Re-run WAU'
               Start-Process -FilePath powershell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Command `"$WorkingDir\winget-upgrade.ps1`""
               exit

```

As for the @user1722 question 👍:
https://github.com/Romanitho/Winget-AutoUpdate/pull/402#issuecomment-1727070453

**Comment by user1722** [comment]
Thanks for answering :D 
well the network Problems occured only in like 1-2 PC`s from 400-500 but it happend because they lost connection in a dumb moment etc. Or maybe VPN problems/Hotel internet ....
So i wanted it to fix itself in that case and run with the next scheduled task. what it did that way :D 
If i call it to fast maybe connection is not back so iam ok with waiting to try it over the next days till it gets a clean connection.
I think if more or bigger companies would use it that could happen also for them.

For the config folder it happend only because of problems with writing permissions in the User Context. But i dont find a script that creates the folder if its not in the initial install but maybe i also just dont see it :D

**Comment by Romanitho** [comment]
Hi,
It depends how you deploy WAU 😅
With SCCM or Intune for instance, you have detection method to check WAU installation. So if installation failed, it retries 😊

For the config folder, it was used in the past for the WAU config stuffs. Now, all is based in registry. As @KnifMelti said, it is only used for notification for users when WAU runs in **system** context. 
Basically, we could clean things up by remove that folder and put the notif xml at WAU root folder (or not at all if ServiceUI.exe is retained as another solution on next releases)

**Comment by user1722** [comment]
Thanks for answering :D yeah i could and should probably fix my Intune detection then if the other things are also installed.
