### ISSUE TITLE
[Bug]: Citrix Workspace App not being updated

### ISSUE THREAD

**Issue by hmorandell** [Romanitho/Winget-AutoUpdate#411]
### The problem

Hi,

this issue is not really related to Winet-AutoUpdate, it's more a winget/Citrix issue in my opinion...

Let me explain the problem.

When having devices with older Citrix Workspaces installed, there Id of the package is called "CitrixOnlinePluginPackWeb". 

```
Name				Id		                	Version            Available     Source

----------------------------------------------------------------------
Citrix Workspace 2010		CitrixOnlinePluginPackWeb		20.10.0.20
```

The newer versions of Citrix Workspace in the winget source is called "Citrix.Workspace"

when doing a "winget upgrade" the result is that there is no upgrade for Citrix available. 
Doing instead an explicit installation of Citrix Workspace "winget install --id Citrix.workspace --silent" it will do a correct upgrade and even keep all the Citrix store conmfiguration.

Citrix can be a real pain in the ass... 

do you think you might be able to handle this in the upgrade script as a special type of app and do a lookup for "CitrixOnlinePluginPackWeb" and in case if found update it via the above command or is this out of scope?

### What version of WAU has the issue?

1.17.8

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 22H2

### What version of winget are you using?

v1.6.2771

**Comment by KnifMelti** [comment]
That ID is internal on your client, it doesn't exist in any source.
You could try from the `_AppID-template.ps1` in `mods ` create a `CitrixOnlinePluginPackWeb-preinstall.ps1` (or create your own as that template is an example with deps to `_Mods-Functions.ps1`) and in that do what you want.

In that template I've provided an:
```
#Install App from Winget Repo, multiple: "appID1","appID2". Example:
#$WingetIDInst = @("Microsoft.PowerToys")
$WingetIDInst = @("")
```

**Comment by KnifMelti** [comment]
And, regarding Citrix.Workspace:
https://github.com/Romanitho/Winget-Install#use-winget-native-parameters

**Comment by KnifMelti** [comment]
...or, if that doesn't cut it (the ID not existing in any source) you could write your own global solution if that app is installed via:
https://github.com/Romanitho/Winget-AutoUpdate#custom-script-mods-for-wau

**Comment by Romanitho** [comment]
Totally agree.
We cannot customize WAU with all specific cases. It would become a mess.
Mods was created for that. You can adapt WAU regarding your context :)

**Comment by hmorandell** [comment]
OK thanks for the feedback. I agree, if we can have mods for that there should be no change to WAU!
