### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by JoostGelijsteen** [Romanitho/Winget-AutoUpdate#420]
### The request

We would like to add a feature that we can set a parameter to only install stable releases of the Winget-Autoupdate. because we are now getting updated to Nightly builds in a production environment. 

### Is your feature request related to a problem?

```txt
We want to test the releases before going into production
```

**Comment by JoostGelijsteen** [comment]
We traced some stuff, after cleaning version.txt the registry key WAU_UpdatePrerelease is 0. after this, it is not installing the update. would be great it is going to be a parameter we could set

**Comment by Romanitho** [comment]
The behaviour is:
If you install stable release, it configures WAU to update to stable release only.
If you install pre release, it enables pre release updates.
