### ISSUE TITLE
[Bug]: WAU_RunGPOManagement switces of but doesn'r switch on again from GPO managenet

### ISSUE THREAD

**Issue by KnifMelti** [Romanitho/Winget-AutoUpdate#421]
### The problem

When switching off **Activate WAU GPO Management** via GPO **WAU_RunGPOManagement** in registry is set to **0**, but switching it on again in GPO doesn't set it to **1** in registry

### What version of WAU has the issue?

1.17.9-1

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 22H2

### What version of winget are you using?

v1.6.2771

**Comment by Romanitho** [comment]
By the way, WAU_RunGPOManagement is updated once a day via the new scheduled task. Have you forced it?

**Comment by KnifMelti** [comment]
Yes, I've included it in my **_WAU-mods.ps1** too ❤️
https://github.com/Romanitho/Winget-AutoUpdate/pull/419#issuecomment-1762163451

**Comment by KnifMelti** [comment]
Ah, I see my _WAU-mods.ps1 only acts if it's 1...

**Comment by Romanitho** [comment]
In fact, the policy scheduled task runs once a day as it is mainly built to update settings that are not in the policy registry.
But, all other settings in the policy registry are applied at each WAU execution. So, just after a gpupdate, WAU uses policy settings ;)

**Comment by KnifMelti** [comment]
👌❤️

**Comment by Romanitho** [comment]
The switch is realised in Get-WAUConfig function, line 12 😇

**Comment by KnifMelti** [comment]
Changed my  **_WAU-mods.ps1**  https://github.com/Romanitho/Winget-AutoUpdate/pull/419#issuecomment-1762163451 👌
