### ISSUE TITLE
[Bug]: Unhandled error for missing file winget_system_apps.txt

### ISSUE THREAD

**Issue by ConfigConfused** [Romanitho/Winget-AutoUpdate#426]
### The problem

When running Winget-Upgrade.ps1 from terminal the following error is displayed.

Get-WingetOutdatedApps.ps1 error:

Get-Content : Cannot find path 'C:\ProgramData\Winget-AutoUpdate\winget_system_apps.txt' because it does not exist.
At C:\ProgramData\Winget-AutoUpdate\functions\Get-WingetOutdatedApps.ps1:71 char:23

Line 71 should be:
$SystemApps = Get-Content -Path "$WorkingDir\winget_system_apps.txt" -ErrorAction SilentlyContinue

### What version of WAU has the issue?

1.17.9-2

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 23H2

### What version of winget are you using?

1.6.2771

**Comment by Romanitho** [comment]
Hello. Thanks for your report. You can submit PR to get credited ;)
