### ISSUE TITLE
Update from apps failed even when theire finished.

### ISSUE THREAD

**Issue by iMonZ** [Romanitho/Winget-AutoUpdate#43]
11:00:40 - Updating VSCodium from 1.63.2 to 1.65.2...
11:00:44 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'VSCodium.VSCodium'   ##########
   -\ 
No applicable update found.
   - 
Found VSCodium [VSCodium.VSCodium] Version 1.65.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/VSCodium/vscodium/releases/download/1.65.2/VSCodiumUserSetup-x64-1.65.2.exe
   -\|/-\|/-\ 

  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 75.2 MB
  █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 75.2 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  15.0 MB / 75.2 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  24.0 MB / 75.2 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  34.0 MB / 75.2 MB
  █████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒  43.0 MB / 75.2 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  53.0 MB / 75.2 MB
  █████████████████████████▒▒▒▒▒  63.0 MB / 75.2 MB
  ████████████████████████████▒▒  71.2 MB / 75.2 MB
  ██████████████████████████████  75.2 MB / 75.2 MB
Successfully verified installer hash
Starting package install...
   -\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\| 
Successfully installed
11:01:38 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'VSCodium.VSCodium'   ##########
11:01:38 - VSCodium update failed.
11:01:42 - No new update.
11:01:42 - End of process!

**Comment by Romanitho** [comment]
Hi. It might be related to your app. `No applicable update found.` is probably indicating that Winget doesn't know how to handle the app. As a workaround, we put a `winget -install` behaviour.

What I would suggest is trying to uninstall your app manually, then install the 1.63.2 version with Winget, and try to update with WAU.

**Comment by iMonZ** [comment]
> 

All right thanks!

But it still got the error when I try updating winget-autoupdate.

**Comment by Romanitho** [comment]
is your app installed from EXE or MSI ?

**Comment by iMonZ** [comment]
> is your app installed from EXE or MSI ?

Thats a good question. I think its MSI since I prefer them.
But if i installed it over Winget they use exe

**Comment by Romanitho** [comment]
Maybe Winget doens't how to handle your app when installed as msi :(

**Comment by iMonZ** [comment]
> Maybe Winget doesn't how to handle your app when installed as msi :(

:(

But how can winget detect if an app is already installed?
Its over the same api that the old uninstall panel from control center is using.
And there you have the msi as well right?

**Comment by Romanitho** [comment]
i'm sorry but i'm note a Winget dev. So maybe open a case on Winget repo 🤷‍♂️

**Comment by Romanitho** [comment]
Currently having the same issue with VLC. But it's related to Winget or the way VLC is detected (even VLC dev problem maybe)

**Comment by Romanitho** [comment]
> Currently having the same issue with VLC. But it's related to Winget or the way VLC is detected (even VLC dev problem maybe)

https://github.com/microsoft/winget-pkgs/issues/58397
