### ISSUE TITLE
[Bug]: ServiceUI blocking updates

### ISSUE THREAD

**Issue by KnifMelti** [Romanitho/Winget-AutoUpdate#440]
### The problem

When **WAU AutoUpdate is Enabled**/`ServiceUI.exe` running and there is an WAU update to be downloaded/installed the running **ServiceUI** can't be overwritten causing an update fail (leaving the downloaded/unpacked zip in the filesystem).

### What version of WAU has the issue?

1.17.9-5

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 22H2

### What version of winget are you using?

1.6.2771

### Log information

```txt
########################################################
#     CHECK FOR APP UPDATES (System context with ServiceUI) - 2023-10-21
########################################################
03:30:52 - WAU Policies management Enabled.
03:30:52 - Notification Level: Full. Notification Language: English
03:30:52 - Checking internet connection...
03:30:53 - Connected !
03:31:02 - Winget Version: v1.6.2771
03:31:02 - WAU current version: 1.17.9-5
03:31:02 - WAU AutoUpdate is Enabled.
03:31:02 - WAU AutoUpdate Pre-release versions is Enabled
03:31:03 - WAU Available version: 1.17.9-6
03:31:07 - Downloading the GitHub Repository version 1.17.9-6
03:31:07 - Unzipping the WAU Update package
03:31:09 - Updating WAU...
03:31:12 - WAU Update failed
```

### Additional information

![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/102996177/4f216bfc-3bda-4152-8d78-4f62cd20b57c)

**Comment by Romanitho** [comment]
Thanks for report. I'll fix that this morning.

**Comment by KnifMelti** [comment]
Not morning yet!

**Comment by Romanitho** [comment]
I think we need to improve the update process. Instead of using an `Invoke-PostUpdateActions` it would be better to run the installer with specific switch for update. For example:
Fresh install:
`Winget-AutoUpdate-Install.ps1 -Silent -InstallUserContext -UpdatesAtLogon`
Update could be:
`Winget-AutoUpdate-Install.ps1 -Upgrade`

In the current process, we copy everything and then apply fixes with `Invoke-PostUpdateActions`.  
If we use an update from the installer, we can update and adjust things directly.

**Comment by KnifMelti** [comment]
Sounds solid if there is a way to start the upgrade process from under ServiceUI and then kill it self (not killing the upgrade process) so that the exe can be overwritten...

**Comment by Romanitho** [comment]
Moreover you've done hard work with the `-NoClean` that could be used as well :)

I'll test to start a new process that will not be loaded with ServiceUI
