### ISSUE TITLE
[Bug]: Error notification when upgrade fails but install succeeds

### ISSUE THREAD

**Issue by andreasbrett** [Romanitho/Winget-AutoUpdate#446]
### The problem

A package _upgrade_ of Zoom.Zoom did not work and WAU tried to upgrade by _installing_ instead. That installation succeeded but unfortunately the unsuccessful upgrade triggered a "Zoom could not be updated" notification popup. While logs indicate that the install was successful this will raise unnecessary support requests with the IT deploying WAU to the fleet.

Notification about package update success should not be popped until both methods were unsuccessful. In my case this happened in the user context.

### What version of WAU has the issue?

1.17.8

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 22H2

### What version of winget are you using?

1.6.2771

**Comment by KnifMelti** [comment]
Our solution (5000+ clients) to avoid unnecessary support questions:
`-NotificationLevel SuccessOnly`

**Comment by andreasbrett** [comment]
Good point but if there's a notification feature, it should notify correctly, don't you think?

**Comment by KnifMelti** [comment]
Absolutely, if so.
Could you please post the log for that complete run?
Maybe we can spot something.

**Comment by andreasbrett** [comment]
Sure thing. Here you go.

```
##################################################
#     CHECK FOR APP UPDATES - 25.10.2023
##################################################
14:55:08 - Running in System context
14:55:08 - Activated WAU GPO Management detected, comparing...
14:55:08 - Changed settings detected and applied
14:55:08 - Max Log Size reached: 5120 bytes - Rotated Logs
14:55:08 - Notification Level: Full. Notification Language: Deutsch
14:55:08 - Checking internet connection...
14:55:08 - Connected !
14:55:10 - Winget Version: v1.6.2771
14:55:10 - WAU current version: 1.17.8
14:55:10 - WAU AutoUpdate is Disabled.
14:55:10 - WAU uses External Lists from: GPO
14:55:10 - WAU uses White List config
14:55:10 - Checking application updates on Winget Repository...
-> Available update : Microsoft Visual C++ 2015-2022 Redistributable (x64) -. Current version : 14.32.31326.0. Available version : 14.38.32919.0.
14:55:11 - Microsoft Visual C++ 2015-2022 Redistributable (x64) - : Skipped upgrade because it is not in the included app list
14:55:11 - No new update.
14:55:14 - User logged on, get a list of installed Winget apps in System context...
14:55:17 - Starting WAU in User context

##################################################
#     CHECK FOR APP UPDATES - 25.10.2023
##################################################
14:55:17 - Running in User context
14:55:17 - Notification Level: Full. Notification Language: English
14:55:17 - Checking internet connection...
14:55:18 - Connected !
14:55:19 - Winget Version: v1.6.2771
14:55:19 - WAU current version: 1.17.8
14:55:19 - WAU uses White List config
14:55:19 - Checking application updates on Winget Repository...
-> Available update : Zoom. Current version : 5.15.12.21574. Available version : 5.16.5.24296.
14:55:21 - Updating Zoom from 5.15.12.21574 to 5.16.5.24296...
14:55:25 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Zoom.Zoom'   ##########
14:55:25 - -> Running: Winget upgrade --id Zoom.Zoom --accept-package-agreements --accept-source-agreements -h
                                                                                                                       
Found Zoom [Zoom.Zoom] Version 5.16.5.24296
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://cdn.zoom.us/prod/5.16.5.24296/x64/ZoomInstallerFull.exe
 
  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 80.6 MB
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  9.00 MB / 80.6 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  16.0 MB / 80.6 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  22.0 MB / 80.6 MB
  ███████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  30.0 MB / 80.6 MB
  ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  38.0 MB / 80.6 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  43.0 MB / 80.6 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  51.6 MB / 80.6 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  58.6 MB / 80.6 MB
  █████████████████████████▒▒▒▒▒  67.6 MB / 80.6 MB
  ███████████████████████████▒▒▒  73.6 MB / 80.6 MB
  ██████████████████████████████  80.6 MB / 80.6 MB
Successfully verified installer hash
Starting package install...
Successfully installed

14:56:09 - -> An upgrade for Zoom failed, now trying an install instead...
14:56:09 - -> Running: Winget install --id Zoom.Zoom --accept-package-agreements --accept-source-agreements --force -h

Found Zoom [Zoom.Zoom] Version 5.16.5.24296
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://cdn.zoom.us/prod/5.16.5.24296/x64/ZoomInstallerFull.exe

  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 80.6 MB
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  10.0 MB / 80.6 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  17.0 MB / 80.6 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  24.0 MB / 80.6 MB
  ███████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  32.0 MB / 80.6 MB
  ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  39.0 MB / 80.6 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  45.0 MB / 80.6 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  53.0 MB / 80.6 MB
  ██████████████████████▒▒▒▒▒▒▒▒  60.0 MB / 80.6 MB
  ████████████████████████▒▒▒▒▒▒  67.0 MB / 80.6 MB
  ███████████████████████████▒▒▒  74.6 MB / 80.6 MB
  ██████████████████████████████  80.6 MB / 80.6 MB
Successfully verified installer hash
Starting package install...
Successfully installed

14:56:50 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Zoom.Zoom'   ##########
14:56:50 - Zoom update failed.
14:56:53 - No new update.
14:56:53 - End of process!
```

I don't get why winget returned with "successfully installed" for the upgrade and then WAU thinks it was unsuccessful. See this snippet of above log.

```
Starting package install...
Successfully installed

14:56:09 - -> An upgrade for Zoom failed, now trying an install instead...
```

**Comment by Romanitho** [comment]
there is winget process, that sometimes success, but then, not detected by our detection in `Confirm-Installation.ps1`

**Comment by andreasbrett** [comment]
I checked the code for any issues but could not find any. The `Confirm-Installation` function (https://github.com/Romanitho/Winget-AutoUpdate/blob/824b3c54549550ed53a30d23e4449c8e5dab1232/Winget-AutoUpdate/functions/Update-App.ps1#L48) uses `winget export` and parses the JSON comparing versions. I manually ran `winget export -s winget --include-versions` and the App ID as well as the App Version in the JSON outut are as expected (Zoom.Zoom and 5.16.5.24296).

At first I thought it could've been a timing issue where winget did not yet reflect the new version after the update. But looking at the log shows that both times - after the upgrade and after the install - `Confirm-Installation` returned `false`. There was plenty of time between upgrade and install (~50 seconds).

**Comment by KnifMelti** [comment]
https://github.com/Romanitho/Winget-AutoUpdate/issues/433#issuecomment-1776720810
Does the folder `config` exist?

**Comment by andreasbrett** [comment]
> [#433 (comment)](https://github.com/Romanitho/Winget-AutoUpdate/issues/433#issuecomment-1776720810) Did/does the folder `config` exist (beforehand)?

The `config` folder does not exist (not even now). Looking at the later comments in that issue I assume this is already fixed and will be released in the coming version. I will close this issue.

**Comment by KnifMelti** [comment]
It is fixed.
Everything gets upgraded, but it fails according to WAU.
But the issue **can** result in a non existing installation, depending on the apps own install teqnique. 
For example `VLC media player` has this behaviour (at least in our environment), so my recommendation is to create the configure folder inte he meantime.
