### ISSUE TITLE
[Bug]: Zoom will not update when executed via task scheduler

### ISSUE THREAD

**Issue by jaredonair** [Romanitho/Winget-AutoUpdate#448]
### The problem

The Zoom app is not upgrading when the scheduled task is executed. It does update if I manually run the winget-upgrade.ps1  script from powershell

########################################################
#     CHECK FOR APP UPDATES (System context with ServiceUI) - 10/26/2023
########################################################
08:44:46 - Running Post Update actions:
08:44:46 - -> Checking if WinGet is installed/up to date
08:44:46 - -> WinGet is up to date: v1.6.2771
08:44:46 - -> Checking Mods Directory:
08:44:46 - -> The mods directory was already secured!
08:44:46 - -> C:\ProgramData\Winget-AutoUpdate\Version.txt removed.
08:44:49 - Post Update actions finished
08:44:49 - Notification Level: none. Notification Language: English
08:44:49 - Checking internet connection...
08:44:49 - Connected !
08:44:51 - Winget Version: v1.6.2771
08:44:51 - WAU current version: 1.18.0
08:44:51 - WAU AutoUpdate is Enabled.
08:44:51 - WAU AutoUpdate Pre-release versions is Enabled
08:44:52 - WAU is up to date.
08:44:52 - WAU uses Black List config
08:44:53 - Checking application updates on Winget Repository...
08:44:55 - An unusual thing happened (maybe all apps are upgraded):

   - 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 8.24 MB
  ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 8.24 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 8.24 MB
  ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 8.24 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 8.24 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  6.00 MB / 8.24 MB
  █████████████████████████▒▒▒▒▒  7.00 MB / 8.24 MB
  █████████████████████████████▒  8.00 MB / 8.24 MB
  ██████████████████████████████  8.24 MB / 8.24 MB
                                                                                                                        
No installed package found matching input criteria.

08:44:55 - No new update.
08:44:55 - End of process!

### What version of WAU has the issue?

1.18.0

### What version of Windows are you using (ex. Windows 11 22H2)?

Win 11 22H2

### What version of winget are you using?

1.6.2771

### Log information

```txt
########################################################
#     CHECK FOR APP UPDATES (System context with ServiceUI) - 10/26/2023
########################################################
08:44:35 - Notification Level: none. Notification Language: English
08:44:35 - Checking internet connection...
08:44:36 - Connected !
08:44:38 - Winget Version: v1.6.2771
08:44:38 - WAU current version: 1.17.9-9
08:44:38 - WAU AutoUpdate is Enabled.
08:44:38 - WAU AutoUpdate Pre-release versions is Enabled
08:44:41 - WAU Available version: 1.18.0
08:44:41 - Downloading the GitHub Repository version 1.18.0
08:44:41 - Unzipping the WAU Update package
08:44:43 - Updating WAU...
08:44:43 - Done. Cleaning temp files...
08:44:43 - WAU Update completed.
08:44:43 - Re-run WAU
 
########################################################
#     CHECK FOR APP UPDATES (System context with ServiceUI) - 10/26/2023
########################################################
08:44:46 - Running Post Update actions:
08:44:46 - -> Checking if WinGet is installed/up to date
08:44:46 - -> WinGet is up to date: v1.6.2771
08:44:46 - -> Checking Mods Directory:
08:44:46 - -> The mods directory was already secured!
08:44:46 - -> C:\ProgramData\Winget-AutoUpdate\Version.txt removed.
08:44:49 - Post Update actions finished
08:44:49 - Notification Level: none. Notification Language: English
08:44:49 - Checking internet connection...
08:44:49 - Connected !
08:44:51 - Winget Version: v1.6.2771
08:44:51 - WAU current version: 1.18.0
08:44:51 - WAU AutoUpdate is Enabled.
08:44:51 - WAU AutoUpdate Pre-release versions is Enabled
08:44:52 - WAU is up to date.
08:44:52 - WAU uses Black List config
08:44:53 - Checking application updates on Winget Repository...
08:44:55 - An unusual thing happened (maybe all apps are upgraded):

   - 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 8.24 MB
  ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 8.24 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 8.24 MB
  ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 8.24 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 8.24 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  6.00 MB / 8.24 MB
  █████████████████████████▒▒▒▒▒  7.00 MB / 8.24 MB
  █████████████████████████████▒  8.00 MB / 8.24 MB
  ██████████████████████████████  8.24 MB / 8.24 MB
                                                                                                                        
No installed package found matching input criteria.

08:44:55 - No new update.
08:44:55 - End of process!
```

**Comment by Romanitho** [comment]
2 options:
- enable WAU to run in User context too
- uninstall/reinstall zoom in system context to be managed by WAU without user context.
