### ISSUE TITLE
Update of specific apps fail

### ISSUE THREAD

**Issue by bebeidon** [Romanitho/Winget-AutoUpdate#45]
Hello, i wanted to inform you about some issues with the update of the following apps:

(I'm using the preview version of winget v1.18.431.0 and i know it is not supported but maybe this information is useful)

Microsoft.dotnet:
It fails with the script and when i update with a admin account on cmd with "winget upgrade --all" it will say installed successfully but if i list the apps with "winget upgrade" it's still the old version.

Cisco.WebexTeams
fails with the script and fails on cmd with exitcode 1638 "another version is already installed"

Microsoft.OpenJDK.11
fails with the script but successful on cmd. maybe it is important, that the old app will be uninstalled first:
```
(5/6) Gefunden Microsoft Build of OpenJDK with Hotspot 11 [Microsoft.OpenJDK.11] Version 11.0.14.101
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Downloading https://aka.ms/download-jdk/microsoft-jdk-11.0.14.1_1-31205-windows-x64.msi
  ██████████████████████████████   161 MB /  161 MB
Der Installer-Hash wurde erfolgreich überprüft
Paket-Deinstallation wird gestartet...
Erfolgreich deinstalliert
Paketinstallation wird gestartet...
Erfolgreich installiert
```

Python.Python.3
fails with the script but successful on cmd. here it will open a custom installer, maybe the script can't handle that?

**Comment by Romanitho** [comment]
Hi,

For Microsoft.dotnet, Cisco.WebexTeams and Microsoft.OpenJDK.11, it might be better to open a case on [Winget-cli](https://github.com/microsoft/winget-cli/issues).

Regarding Python, can you share the WAU logs please ?

**Comment by bebeidon** [comment]
yes sure:

```
08:55:44 - Updating Python 3 from 3.6.8150.0 to 3.10.4150.0...
08:55:48 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Python.Python.3'   ##########
   -\|/-\| 
Failed in attempting to update the source: winget
   - 
No installed package found matching input criteria.
   -\|/ 
Failed in attempting to update the source: winget
Found Python 3 [Python.Python.3] Version 3.10.4150.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.python.org/ftp/python/3.10.4/python-3.10.4-amd64.exe
   -\ 

  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0.00 B / 27.1 MB
  █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 27.1 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 27.1 MB
  ███████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  10.0 MB / 27.1 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  14.0 MB / 27.1 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  17.0 MB / 27.1 MB
  ██████████████████████████▒▒▒▒  24.0 MB / 27.1 MB
  ██████████████████████████████  27.1 MB / 27.1 MB
Successfully verified installer hash
   - 
Starting package install...
   -\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/- 
Successfully installed
   - 
   -\| 
Failed in attempting to update the source: winget
Found Python 3 [Python.Python.3] Version 3.10.4150.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.python.org/ftp/python/3.10.4/python-3.10.4-amd64.exe
   -\|/- 

  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0.00 B / 27.1 MB
  █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 27.1 MB
  ████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 27.1 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 27.1 MB
  ███████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  10.0 MB / 27.1 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  14.0 MB / 27.1 MB
  ████████████████████▒▒▒▒▒▒▒▒▒▒  18.1 MB / 27.1 MB
  ██████████████████████▒▒▒▒▒▒▒▒  20.1 MB / 27.1 MB
  █████████████████████████▒▒▒▒▒  23.1 MB / 27.1 MB
  ██████████████████████████████  27.1 MB / 27.1 MB
Successfully verified installer hash
   - 
Starting package install...
   -\|/-\|/-\|/-\| 
Installer failed with exit code: 1603
Installer log is available at: C:\WINDOWS\TEMP\WinGet\WinGet-Python.Python.3.3.10.4150.0-2022-04-08-08-58-53.067.log
08:59:02 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Python.Python.3'   ##########
08:59:02 - Python 3 update failed.
```


After the script it showed like this:

`Python 3                                   Python.Python.3            3.10.2150.0   3.10.4150.0   winget`

**Comment by bebeidon** [comment]
also regarding the Microsoft.OpenJDK.11 topic, have you seen the output i posted? it first uninstalls the old version and then installs the new one, maybe this is a script problem as it works on cmd?

**Comment by Romanitho** [comment]
For your issues, I don't really know what can happen, because we run the exact same Winget command in PowerShell script than in cmd.
We just need to keep in mind that when your run in cmd, you are under your user session. The ps1 script is run in System context. It might behave differently regarding apps.
Moreover, you run pre-release version. I plan to install it this weekend to start working with new features.

another thing that I can see in your logs is `Failed in attempting to update the source: winget`. I'll see if I can have same result with prerelease Winget version

**Comment by iMonZ** [comment]
Maybe a solution is to run the autoupdate script as user and system.
This could solve the problem.

**Comment by Romanitho** [comment]
it could be a solution if use has admin right.
If you use it in company context, there is no solution. If you use it personally and have admin right, you can change the scheduled task that run Winget-AutoUpdate to run with user context and admin rights.

Sorry for french screenshot, but change "System" by your user and tick the admin right box
![image](https://user-images.githubusercontent.com/96626929/162726132-8f7ec839-59a7-4aa0-b327-19e365d5302f.png)

**Comment by Romanitho** [comment]
I don't really agree, because the Winget Update task would be run twice, and generate errors or popups when run as user without admin rights.

for me, only one solution if you're admin : as mentioned, change the scheduled task to run with your account.

**Comment by bebeidon** [comment]
@iMonZ maybe you look up how to change a task by yourself as it's not that hard? and maybe open another issue as this is unrelated here please.

**Comment by iMonZ** [comment]
> uled task to run with your account.

What about its run over system first and then over user.
Then there will be no overlap at all!

**Comment by Romanitho** [comment]
in that case feel free to create your own scheduled tasks ;)
