### ISSUE TITLE
[Feature Request]: Apps Getting updated some are reinstalled and this resets the Windows Default Apps 

### ISSUE THREAD

**Issue by Jordan-Fielding** [Romanitho/Winget-AutoUpdate#450]
### The request

During deployment through Intune, we have noted that sometimes when apps are updated WinGet will reinstall the apps. Which is a normal function of Winget. This clears the app from the default apps. 

This is something that would help if the Auto Update was set to re-import the default apps each time it updates.

This looks like it can be dome using dism running in user context.

dism /online /Export-DefaultAppAssociations:"%UserProfile%\Desktop\MyDefaultAppAssociations.xml"

dism /online /Import-DefaultAppAssociations:"%UserProfile%\Desktop\MyDefaultAppAssociations.xml"

**Comment by KnifMelti** [comment]
![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/102996177/5ffd1601-b086-4ab0-91f3-9d7bc93efdff)

**Comment by Romanitho** [comment]
Moreover, it only concerns User context execution. Most of apps should be installed in system context for me.

**Comment by KnifMelti** [comment]
But, maybe:
```
reg export "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ApplicationAssociationToasts" "$env:USERPROFILE\Desktop\MyDefaultAppAssociations.xml"
reg import "$env:USERPROFILE\Desktop\MyDefaultAppAssociations.xml" /f

```
