### ISSUE TITLE
Also detect vcredist 2015-2022 installation

### ISSUE THREAD

**Issue by itsmeboy0** [Romanitho/Winget-AutoUpdate#48]
`install.bat` installs vcredist 2015-2019 even if I have 2015-2022 installed. I think that is redundant and there should also be a check for it.

**Comment by Romanitho** [comment]
I agree.  But during our first tests we observed that when 2022 was installed, I had an issue that I haven't with 2019. I need to check that again.

**Comment by Romanitho** [comment]
Ok, I did news tests and works. Maybe i did something wrong on first time.
