### ISSUE TITLE
[Bug]: normal user gets prompt to update apps

### ISSUE THREAD

**Issue by unclesam87** [Romanitho/Winget-AutoUpdate#482]
### The problem

hey,
we use ur script to update all the apps/programs on ur domain systems and to an certain level this works pretty good (thank u again for ur work)
sadly we encounter some apps that seems to prompt for admin credentials and we aren't sure how to fix it.
these are the parameters we used while installing:
 -UpdatesAtLogon -UpdatesInterval Daily -InstallUserContext -NotificationLevel None -Silent -DoNotUpdate

here is ur log file(sorry for the german log file):

### What version of WAU has the issue?

1.18.1

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 10 to Windows 11 22H2

### What version of winget are you using?

1.6.3133

### Log information

```txt
11:50:10 - Updating Dev Home from 0.600.297.0 to 0.601.297.0...
11:50:10 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.DevHome'   ##########
11:50:10 - -> Running: Winget upgrade --id Microsoft.DevHome -e --accept-package-agreements --accept-source-agreements -s winget -h

Gefunden Dev Home (Preview) [Microsoft.DevHome] Version 0.601.297.0
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Dieses Paket erfordert folgende Abhängigkeiten:
  - Pakete
Abhängigkeiten werden installiert:
(1/1) Gefunden Windows App Runtime [Microsoft.WindowsAppRuntime.1.3] Version 1.3.3
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Das Installationsprogramm fordert die Ausführung als Administrator an. Es wird eine Eingabeaufforderung erwartet.

Unerwarteter Fehler beim Ausführen des Befehls: 
0x800704c7 : Der Vorgang wurde durch den Benutzer abgebrochen.

11:53:52 - -> An upgrade for Dev Home failed, now trying an install instead...
11:53:52 - -> Running: Winget install --id Microsoft.DevHome -e --accept-package-agreements --accept-source-agreements -s winget -h --force

Gefunden Dev Home (Preview) [Microsoft.DevHome] Version 0.601.297.0
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.

Dieses Paket erfordert folgende Abhängigkeiten:
  - Pakete
Abhängigkeiten werden installiert:
(1/1) Gefunden Windows App Runtime [Microsoft.WindowsAppRuntime.1.3] Version 1.3.3
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Das Installationsprogramm fordert die Ausführung als Administrator an. Es wird eine Eingabeaufforderung erwartet.

Unerwarteter Fehler beim Ausführen des Befehls: 
0x800704c7 : Der Vorgang wurde durch den Benutzer abgebrochen.
```

**Comment by unclesam87** [comment]
looks like it is run under the user context: 
#     CHECK FOR APP UPDATES (User context) - 16.11.2023
########################################################
11:50:01 - Notification Level: None. Notification Language: Deutsch
11:50:01 - Checking internet connection...
11:50:01 - Connected !
11:50:03 - Winget Version: v1.6.3133
11:50:03 - WAU current version: 1.18.1
11:50:03 - WAU uses Black List config
11:50:03 - Checking application updates on Winget Repository...
-> Available update : Teams Machine-Wide Installer. Current version : 1.6.0.24078. Available version : 1.6.00.29964.
-> Available update : Dev Home. Current version : 0.600.297.0. Available version : 0.601.297.0.
11:50:05 - Updating Teams Machine-Wide Installer from 1.6.0.24078 to 1.6.00.29964...
11:50:05 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.Teams.Classic'   ##########
11:50:05 - -> Running: Winget upgrade --id Microsoft.Teams.Classic -e --accept-package-agreements --accept-source-agreements -s winget -h

Es wurde kein installiertes Paket gefunden, das den Eingabekriterien entspricht.
11:50:10 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Microsoft.Teams.Classic'   ##########
11:50:10 - Teams Machine-Wide Installer updated to 1.6.00.29964 !
11:50:10 - Updating Dev Home from 0.600.297.0 to 0.601.297.0...
11:50:10 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.DevHome'   ##########
11:50:10 - -> Running: Winget upgrade --id Microsoft.DevHome -e --accept-package-agreements --accept-source-agreements -s winget -h

Gefunden Dev Home (Preview) [Microsoft.DevHome] Version 0.601.297.0
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Dieses Paket erfordert folgende Abhängigkeiten:
  - Pakete
Abhängigkeiten werden installiert:
(1/1) Gefunden Windows App Runtime [Microsoft.WindowsAppRuntime.1.3] Version 1.3.3
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Das Installationsprogramm fordert die Ausführung als Administrator an. Es wird eine Eingabeaufforderung erwartet.

Unerwarteter Fehler beim Ausführen des Befehls: 
0x800704c7 : Der Vorgang wurde durch den Benutzer abgebrochen.

11:53:52 - -> An upgrade for Dev Home failed, now trying an install instead...
11:53:52 - -> Running: Winget install --id Microsoft.DevHome -e --accept-package-agreements --accept-source-agreements -s winget -h --force

Gefunden Dev Home (Preview) [Microsoft.DevHome] Version 0.601.297.0
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.

Dieses Paket erfordert folgende Abhängigkeiten:
  - Pakete
Abhängigkeiten werden installiert:
(1/1) Gefunden Windows App Runtime [Microsoft.WindowsAppRuntime.1.3] Version 1.3.3
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Das Installationsprogramm fordert die Ausführung als Administrator an. Es wird eine Eingabeaufforderung erwartet.

Unerwarteter Fehler beim Ausführen des Befehls: 
0x800704c7 : Der Vorgang wurde durch den Benutzer abgebrochen.

11:56:57 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Microsoft.DevHome'   ##########
11:56:57 - Dev Home update failed.
11:56:57 - 1 apps updated ! No more update.
11:56:57 - End of process!

**Comment by PZan** [comment]
I'm seeing the same for Microsoft.DevHome and some other store apps for Windows 11 (23H2). It seems like this app (AppX Package) is special somehow and isn't completely installed until being launch by the user. Not sure, but I added it to my excluded_apps.txt.

**Comment by KnifMelti** [comment]
Microsoft.Devhome in User context requires WindowsAppRuntime to be installed and that installation must be done elevated (System context)
https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/WindowsAppRuntime/1/3/1.3.3/Microsoft.WindowsAppRuntime.1.3.installer.yaml
You could install it first in System context.
