### ISSUE TITLE
[Feature Request]: GPO Log File Location

### ISSUE THREAD

**Issue by unclesam87** [Romanitho/Winget-AutoUpdate#489]
### The request

Hey,
it would be a nice feature when there would be the possibility to save the log files to an unc or other path in the network and distributed that per gpo.

**Comment by KnifMelti** [comment]
A lot of considerations regarding that.. ..too integrated in everything. A lot of work.

**Comment by Romanitho** [comment]
Use a custom script that daily copy logs where you want :)
