### ISSUE TITLE
[Feature Request]: UI without wscript.exe 

### ISSUE THREAD

**Issue by DanielBahr2** [Romanitho/Winget-AutoUpdate#496]
### The request

Hi, nice Job but are there alternative versions of the updater script without using the Windows Scripting Host?

### Is your feature request related to a problem?

```txt
company policies refuse to use Windows Scripting Host
```

**Comment by Romanitho** [comment]
It's in the pipe #465
We are looking for a good way to remove the vbs helper

**Comment by cquresphere** [comment]
Windows Script Host is going to be deprecated with VBS. 
https://learn.microsoft.com/en-us/windows/whats-new/deprecated-features
and it is recommended to disable WSH on hosts to mitigate many security threats. 

I hope you will find a good solution to substitute WSH with some PowerShell/.Net feature/assembly.
