### ISSUE TITLE
[Bug]: Invisible.vbs not digitally signed

### ISSUE THREAD

**Issue by StreamCalm** [Romanitho/Winget-AutoUpdate#514]
### The problem

The invisible.vbs script isn't signed and so is blocked by AppLocker/WDAC policies requiring scripts to be signed (eg. error below from AppLocker).

`Event 8007 %OSDRIVE%\PROGRAMDATA\WINGET-AUTOUPDATE\INVISIBLE.VBS was prevented from running.`

Would be good to sign these like the powershell scripts to avoid hash based rules which will break with any changesi

### What version of WAU has the issue?

1.04.0034

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 23H2

### What version of winget are you using?

1.6.3133

**Comment by Romanitho** [comment]
#465 
#496

**Comment by Romanitho** [comment]
It is not really a bug, as it is working with standard config. It's related to your security level...

**Comment by StreamCalm** [comment]
Thank you!

**Comment by AndrewDemski-ad-gmail-com** [comment]
I do not want to be devils advocate here but you can trust file by hash.
[Understanding the file hash rule condition in AppLocker](https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/applocker/understanding-the-file-hash-rule-condition-in-applocker)
I wouldn't expect a community-developed project to waste money on signing a single file for little or no profit.

If you have AppLocker in your company, it means that it is managed. The mouse doesn't bite. 
Going through the wizard to add a single file will take less time than writing in this thread.

**Comment by StreamCalm** [comment]
Thanks Andrzej. All the powershell scripts are signed so I thought it might be an accidental oversight. Sounds like there are plans to work around it which is great to hear, and I’m very grateful to the devs.

[cid:catapultlogorounded_8aad1756-eb17-49c1-9ea3-020002733930.png]


Daniel Heaton
Head of IT
DD: +44 1625 725217<callto:+44%201625%20725217>
Mobile: +44 7436 127511<callto:+44%207436%20127511>
***@***.***

[cid:twitter-icon-cirlce-30x30_a0f18b9f-8906-4081-bd32-c96bd18b2089.png]<https://twitter.com/MedDiscCat> [cid:linkedin-icon-cirlce-30x30_444ce194-1e2c-49df-82f9-534edc140a3d.png] <https://www.linkedin.com/company/meddisccat>  [cid:website-icon-cirlce-30x30_53baba98-a363-4e33-a43b-443f77411c55.png] <https://md.catapult.org.uk/>  [cid:youtube-icon-cirlce-30x30_fa299e2b-2897-4b8a-b765-547514fa6eaa.png] <https://www.youtube.com/channel/UC0YUefHzYkhmOhfCAjm-aaA>
________________________________

**Comment by StreamCalm** [comment]
Thanks Andrzej. All the powershell scripts are signed so I thought it might be an accidental oversight. Sounds like there are plans to work around it which is great to hear, and I’m very grateful to the devs.

Edit: Whoops, shouldn't reply to github comments with my email signatures on!

**Comment by AndrewDemski-ad-gmail-com** [comment]
eh.. wrong issue..

**Comment by andreasbrett** [comment]
> All the powershell scripts are signed so I thought it might be an accidental oversight.

They're actually not signed.

**Comment by AndrewDemski-ad-gmail-com** [comment]
Not by community, you would have to sign them by yourself or trust via AppLocker/WDAG rules.

**Comment by StreamCalm** [comment]
> They're actually not signed.

Thought I was going crazy for a second when I checked this morning - the one on my PC is signed, the one in the repo isn't!

I assume the [Winget AutoUpdate Intune](https://github.com/Weatherlights/Winget-AutoUpdate-Intune) is signing them (signing certificate matches that project's author).

Will raise it on that project, apologies for the confusion!

**Comment by Romanitho** [comment]
This project is a fork of our. And seams to be not maintained anymore. Still blocked on our 1.17 that contains security issue.

**Comment by StreamCalm** [comment]
Thanks for letting me know!

**Comment by StreamCalm** [comment]
Thanks Andrew, sage advice!
