### ISSUE TITLE
[Feature Request]: The installer will request to run as administrator, expect a prompt

### ISSUE THREAD

**Issue by MBstatsara** [Romanitho/Winget-AutoUpdate#518]
### The request

When this appears, users who are not admins, get prompted, sometimes repeatedly.
Can we stop this appearing but just report it as a log failure?

### Is your feature request related to a problem?

```txt
An example of this was dev.home, this was installed, potentially as an MS update, ive seen a few queries regarding this, but as we dont use this app, and there are potentially lots of other apps like this, we would like to log an event/log update, then stop the prompt.

The preceeding event in the log is 
The installer will request to run as administrator, expect a prompt.

This is a little problem, as we can exclude this one app, but im looking after so many machines it is causing me issues!
```

**Comment by Romanitho** [comment]
If you use black list, add this app in it.
This app needs admin right for dependencies.
Or, do not use the User context part of WAU

**Comment by Romanitho** [comment]
dev.home requests admin rights for dependencies, that's what winget says.
My suggestion is to black list the app as it is a MS Store app anyway.
