### ISSUE TITLE
[Feature Request]: Randomize update time

### ISSUE THREAD

**Issue by denelon** [Romanitho/Winget-AutoUpdate#525]
### The request

https://www.reddit.com/r/sysadmin/comments/18gl5xg/winget_and_network_traffic/

Give the option to randomize when updates are triggered.

### Is your feature request related to a problem?

```txt
> Hi,
> We have beed using the winget-autoupdate tool across the company, and it's been good to us... mostly.
> The problem is high traffic peak at the scheduled time when multiple computers load up the internet line.
> at some of our sites it's fine (the lines handle the load), but with others... it's an issue.

> Is there a solution like a lan cache / p2p solution (delivery optimization / branch cache and similar...) or a way to randomize the scheduled time?
```

**Comment by AndrewDemski-ad-gmail-com** [comment]
Hi @denelon 
have you considered using this option?
![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/75534654/ef051c79-2a31-4666-b16f-bf689fb84043)

It give you freedom to "flatten the curve" to several hours if necessary.
That randomization is controlled by system which started the task.

**Comment by MichalNSI** [comment]
This would be very useful! It would be great if we could set random delay for WAU task during installation
Of course if this isn't too complicated to implement

**Comment by soredake** [comment]
Not stale.

**Comment by Romanitho** [comment]
> Hi @denelon have you considered using this option? ![image](https://private-user-images.githubusercontent.com/75534654/289999145-ef051c79-2a31-4666-b16f-bf689fb84043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTExODgsIm5iZiI6MTcwODM1MDg4OCwicGF0aCI6Ii83NTUzNDY1NC8yODk5OTkxNDUtZWYwNTFjNzktMmEzMS00NjY2LWIxNmYtYmY2ODlmYjg0MDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDEzNTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYTg1MTYwZWRlNTcyNjM5NzMzNGE0M2MzODYzYjRmNDExZDE0NTExOWMyZjI4MmJlNGRjY2M1YjNmN2YyY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xS6FSkos9DuBHsnJFmpb_vYbu5TP__bt5A58nilPe40)
> 
> It give you freedom to "flatten the curve" to several hours if necessary. That randomization is controlled by system which started the task.
> 
> ..in the meantime I will take a look at the installation routine to see how to add that custom setting there.

You can even edit the install script to customize the way you want it to be installed

**Comment by soredake** [comment]
Not stale.

**Comment by soredake** [comment]
Not stale.
