### ISSUE TITLE
[Bug]: WAU Configurator throws permission errors on launch

### ISSUE THREAD

**Issue by soredake** [Romanitho/Winget-AutoUpdate#533]
### The problem

If you will try to launch WAU Configurator after installing WAU you will receive permission errors:
![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/5204968/9d3764d1-3e8a-4a89-950e-525a4d04d5f6)

### What version of WAU has the issue?

1.19.2-0

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 23H2

### What version of winget are you using?

v1.7.3452-preview

**Comment by AndrewDemski-ad-gmail-com** [comment]
@soredake I'd like to confirm one more thing before it gets investigated. That would limit the area of investigation.

It does not look like a problem with PS LanguageMode.
It can be verified by runnign this command:
`$ExecutionContext.SessionState.LanguageMode`

What is the Execution Policy for that PS context?
It can be checked by running this command:
`Get-ExecutionPolicy -List`

_Happy Xmas_

**Comment by soredake** [comment]
```
❯  $ExecutionContext.SessionState.LanguageMode
FullLanguage
❯  Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    RemoteSigned
 LocalMachine    RemoteSigned
```

**Comment by AndrewDemski-ad-gmail-com** [comment]
Thanks :)
WAU is not signed, You will be running it in system/machine context.

Please check if it works after changing the Local Machine policy to Bypass:
`Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope LocalMachine`

You may revert the change after the test back to previous state by running this command.
`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine`

>Word of caution:
relaxing execution policy may expose your system to potential risk when some process using PowerShell does something sinister without your attention.
More details [there](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies)

**Comment by soredake** [comment]
After uninstalling and installing WAU again i don't see WAU Configuration in start menu anymore so i think this can be closed.
