### ISSUE TITLE
[Bug]: `'C: \ProgramData \Winget-AutoUpdate\Invisible.vbs' is denied`

### ISSUE THREAD

**Issue by huyz** [Romanitho/Winget-AutoUpdate#534]
### The problem

When I run WAU Configurator 1.91.1 and then I check `Install WAU` and click `Install`:
![screenshot 2023-12-16T223454Z](https://github.com/Romanitho/Winget-AutoUpdate/assets/128394/63aa806a-2001-4f42-97f4-b505e7754064)

I get:

![screenshot 2023-12-16T223105Z](https://github.com/Romanitho/Winget-AutoUpdate/assets/128394/3097f5b6-0cda-420c-b9de-f82665f05e85)

### What version of WAU has the issue?

1.91.1

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 23H2

### What version of winget are you using?

v1.7.2782-preview

**Comment by huyz** [comment]
If I try to install with WiGui 1.9.2, I get:

![screenshot 2023-12-16T223454Z](https://github.com/Romanitho/Winget-AutoUpdate/assets/128394/135d0aba-ba27-45d1-a0f1-2e66389217b2)


(Btw, it's impossible for me to get a screenshot without that little WinGui 1.9.2 popup in the center in the way of the full error message. Plus, the Powershell window goes away very fast so it's hard try to find a mitigation.)

**Comment by huyz** [comment]
Never mind.

BitDefender was complaining about all of the files in there, denying access, and putting them into quarantine. Even after restoring files from quarantine, adding exceptions, re-downloading the zip file, and disabling BitDefender, I was still getting the above errors.

It turns out that BitDefender had put those paths or files in a bad state (locked from access). I had to reboot and then everything worked fine with my exceptions.

**Comment by Romanitho** [comment]
Thanks for your findings :)
