### ISSUE TITLE
[Bug]: yt-dlp removed from PATH after updating it with WAU

### ISSUE THREAD

**Issue by soredake** [Romanitho/Winget-AutoUpdate#542]
### The problem

After updating yt-dlp with WAU package path it's no longer present in PATH.

How to reproduce this bug in clean updated vm:
```
winget install -h -e --id yt-dlp.yt-dlp -v 2023.10.07
Invoke-WebRequest -Uri "https://github.com/Romanitho/Winget-AutoUpdate/archive/refs/heads/main.zip" -OutFile "$HOME/Downloads/Winget-AutoUpdate.zip"
Expand-Archive "$HOME/Downloads/Winget-AutoUpdate.zip" -DestinationPath "$HOME/Downloads"
Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned
Start-Process powershell -Verb runAs -ArgumentList '~\Downloads\Winget-AutoUpdate-main\Sources\WAU\Winget-AutoUpdate-Install.ps1 -StartMenuShortcut -Silent -InstallUserContext -NotificationLevel None -UpdatesInterval Weekly -DoNotUpdate -UpdatesAtTime 11AM'
C:\Windows\system32\wscript.exe "C:\ProgramData\Winget-AutoUpdate\Invisible.vbs" "powershell.exe -NoProfile -ExecutionPolicy Bypass -File """C:\ProgramData\Winget-AutoUpdate\user-run.ps1""
```

### What version of WAU has the issue?

1.19.2-1

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 23H2

### What version of winget are you using?

v1.7.3481-preview

### Log information

```txt
################################################################
#     12/27/2023 - CHECK FOR APP UPDATES (User context)
################################################################
15:56:26 - Notification Level: None. Notification Language: English
15:56:26 - Checking internet connection...
15:56:26 - Connected !
15:56:27 - Winget Version: v1.7.3481-preview
15:56:27 - WAU current version: 1.19.2-1
15:56:27 - WAU uses Black List config
15:56:27 - Checking application updates on Winget Repository...
-> Available update : yt-dlp. Current version : 2023.10.07. Available version : 2023.10.13.
15:56:31 - Updating yt-dlp from 2023.10.07 to 2023.10.13...
15:56:31 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'yt-dlp.yt-dlp'   ##########
15:56:31 - -> Running: Winget upgrade --id yt-dlp.yt-dlp -e --accept-package-agreements --accept-source-agreements -s winget -h


Found yt-dlp [yt-dlp.yt-dlp] Version 2023.10.13
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
(1/1) Found FFmpeg [Gyan.FFmpeg] Version 6.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
15:57:05 - -> An upgrade for yt-dlp failed, now trying an install instead... (1/2)
15:57:05 - -> Running: Winget install --id yt-dlp.yt-dlp -e --accept-package-agreements --accept-source-agreements -s winget -h --force

Found yt-dlp [yt-dlp.yt-dlp] Version 2023.10.13
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.

This package requires the following dependencies:
  - Packages
(1/1) Found FFmpeg [Gyan.FFmpeg] Version 6.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Path environment variable modified; restart your shell to use the new value.
Command line alias added: "ffmpeg"
Command line alias added: "ffplay"
Command line alias added: "ffprobe"
Successfully installed

Downloading https://github.com/yt-dlp/yt-dlp/releases/download/2023.10.13/yt-dlp.exe


  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 13.2 MB
  ███████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 13.2 MB
  ████████████████████▒▒▒▒▒▒▒▒▒▒  9.00 MB / 13.2 MB
  ██████████████████████████████  13.2 MB / 13.2 MB
  ██████████████████████████████  13.2 MB / 13.2 MB
Successfully verified installer hash
Starting package install...
Command line alias added: "yt-dlp"
Successfully installed
15:57:29 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'yt-dlp.yt-dlp'   ##########
15:57:29 - yt-dlp updated to 2023.10.13 !
15:57:29 - 1 apps updated ! No more update.
15:57:29 - End of process!
```

**Comment by soredake** [comment]
Same problem with these packages (probably all portable packages are affected): Gyan.FFmpeg lycheeverse.lychee

**Comment by AndrewDemski-ad-gmail-com** [comment]
According to information provided by manufacturer of that product, winget should register command alias for the tool, not modify the path.
https://github.com/microsoft/winget-pkgs/blob/ddf059befd5e72a070dbb0f0aa3188642e24d1e7/manifests/y/yt-dlp/yt-dlp/2023.12.30/yt-dlp.yt-dlp.installer.yaml#L7

That is seen in the log provided:

```
Starting package install...
Command line alias added: "yt-dlp"
Successfully installed
``` 
According to evidence provided it works as designed.

**Comment by soredake** [comment]
> According to information provided by manufacturer of that product, winget should register command alias for the tool, not modify the path.

If you install without admin rights in user scope it will modify the PATH, if you install with admin rights in user scope it will create an alias.

> Even manufacturer suggested ~8 months ago to add it manually to $PATH

This info is outdated.

**Comment by AndrewDemski-ad-gmail-com** [comment]
I see..
You are absolutely right.

In this respect, there have been some attempts to improve winget in this regard

Direct quote from authors:
>// If we fail to create a symlink, add install directory to PATH variable

https://github.com/microsoft/winget-cli/blob/96a7f678c38becd62e150199ecd1e9080f2622cc/src/AppInstallerCLICore/PortableInstaller.h#L35

Apparently some fix was added to solve the issue: https://github.com/microsoft/winget-cli/pull/3002
Yet it still remains open: https://github.com/microsoft/winget-cli/issues/549

Question remains open: if it is a "logic flaw" of winget itself, then how is that related to WAU?

The only solution which comes to my mind is adding post-install action(s) to suplement the installation workflow with desired configuration.
.. but that would have to be treated as patch for every identified product.

**Comment by soredake** [comment]
> Yet it still remains open: [microsoft/winget-cli#549](https://github.com/microsoft/winget-cli/issues/549)

This issue is more about broken installers that do not modify path (like 7zip/7zip-zstd/vim/llvm/proxinject/etc) when they should.

> then how is that related to WAU?

It is related to WAU, it does not happen when I just use `winget upgrade`, and upgrade is failing in WAU which is not the case with plain `winget upgrade`:
![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/5204968/aac79ce2-69d3-47c6-a6ea-e9a8ef43dfd2)

**Comment by KnifMelti** [comment]
> It is related to WAU, it does not happen when I just use `winget upgrade`, and upgrade is failing in WAU which is not the case with plain `winget upgrade`:
> ![image](https://private-user-images.githubusercontent.com/5204968/295033439-aac79ce2-69d3-47c6-a6ea-e9a8ef43dfd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NDc3NDcsIm5iZiI6MTcwNDc0NzQ0NywicGF0aCI6Ii81MjA0OTY4LzI5NTAzMzQzOS1hYWM3OWNlMi02OWQzLTQ3YzYtYTZlYS1lOWE4ZWY0M2RmZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMjA1NzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODYyMGE4NmQwMzFlMmVhNTVmYjU3YjhhYzliMWZiN2ZhZDgwMGQ1N2QzMGMzYmMxMmJkOWVmMmE0YTdjMDg1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kETFlIH5NkPZJruSKGXoCDAPV7hLZI2OQkjOwJGeMZc)

That's when WAU tries `winget upgrade`, after that it tries `winget install` and it then gets installed.

**Comment by soredake** [comment]
I retested this in vm again, and now it happens even without WAU, will report to winget repo then.
