### ISSUE TITLE
[Bug]: VisualStudio updating even though in excluded list because incorrect ID?

### ISSUE THREAD

**Issue by ztrhgf** [Romanitho/Winget-AutoUpdate#548]
### The problem

I don't understand how is this possible, but Visual Studio 2022 gets updated even though in excluded list. The reason for this is incorrect ID as can be seen on the following screenshot.

![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/2930419/ff4216e2-d613-44c6-9b83-89b3a5a70616)

### What version of WAU has the issue?

1.19.1

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 10 22H2

### What version of winget are you using?

v1.6.3482

**Comment by AusomeOllie10** [comment]
So we are in the process of doing this. We are having the same issue. WAU sees the blacklist but seems to action anyway. Apps affected is anything  that's blacklisted.

We are using WAU with GPO from intune.

**Comment by Romanitho** [comment]
This seems to be due to the "long" name that is truncated. You've probably blacklisted "Microsoft.VisualStudio.2022.Professional" but WAU sees "Microsoft.VisualStudio.2022.Professio".
This is probably a "winget" limitation on the consol output. We need to investigate furthermore, but I think this is the main reason.

**Comment by Romanitho** [comment]
With the latest pre-release you can put Microsoft.VisualStudio.2022.* in the list. That should fix it I guess

**Comment by ztrhgf** [comment]
When do you expect to release this version publicly?

**Comment by Romanitho** [comment]
I think we can now, it is stable enough.

**Comment by ztrhgf** [comment]
Lovely.

Dne po 25. 3. 2024 14:35 uživatel Romain ***@***.***> napsal:

**Comment by AusomeOllie10** [comment]
> With the latest pre-release you can put Microsoft.VisualStudio.2022.* in the list. That should fix it I guess

Can we use wildcards for example with docker and python also? Didn't notice they was supported.

**Comment by Romanitho** [comment]
Yes you can. Readme is maybe not up to date. Very busy at the moment 😅

**Comment by AndrewDemski-ad-gmail-com** [comment]
Something similar to [this](https://ss64.com/ps/syntax-consolesize.html) approach would be required to avoid wildcarded situation
