### ISSUE TITLE
Notification Options on Install

### ISSUE THREAD

**Issue by erik29gamer** [Romanitho/Winget-AutoUpdate#55]
Is it possible to have an install parameter that disables/modifies the notify function? I'm very interested in using this, but if even a single application install fails we will have tons of users call our helpdesk to complain.

Alternatively, being able to only show certain notifications (only show successful installs) and hiding others would be great!

**Comment by Romanitho** [comment]
Hello.
I was thinking about that too. We could have:
-Full (all notifications)
- SuccessOnly (only notify new success upgrades)
- None (no notification at all)

**Comment by Romanitho** [comment]
@erik29gamer this feature will be part of next release. You can test and report any bug if you want (currently in PR #63).

**Comment by erik29gamer** [comment]
@Romanitho Awesome, thank you for implementing that so quickly! I'll give it a try later this week if I manage to find some downtime!
