### ISSUE TITLE
[Bug]: WAU tries to upgrade Windows Desktop Runtime from 6.0.26 to 7.0.15 every day

### ISSUE THREAD

**Issue by sshockley** [Romanitho/Winget-AutoUpdate#551]
### The problem

This is probably related to #196 but I was hoping to get some clarification.

WAU thinks that Windows Destkop Runtime 6.0.26 should be upgraded to >7.  This is incorrect as 6.0.26 is the latest version of version 6, which is kinda-sorta a different product.

Log output:
```
06:00:05 - Checking application updates on Winget Repository...
-> Available update : Microsoft Windows Desktop Runtime - 6.0.26 (x64). Current version : < 7.0.0. Available version : 7.0.15.
06:00:10 - Updating Microsoft Windows Desktop Runtime - 6.0.26 (x64) from < 7.0.0 to 7.0.15...
06:00:15 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.DotNet.DesktopRuntime.7'   ##########
06:00:15 - -> Running: Winget upgrade --id Microsoft.DotNet.DesktopRuntime.7 -e --accept-package-agreements --accept-source-agreements -s winget -h
```
However, winget-upgrade doesn't show any needed updates.

Output from winget-upgrade.ps1 as an admin user:
```
PS C:\> C:\ProgramData\Winget-AutoUpdate\winget-upgrade.ps1

################################################################
#     1/19/2024 - CHECK FOR APP UPDATES (User context)
################################################################
09:30:58 - Notification Level: Full. Notification Language: English
09:30:58 - Checking internet connection...
09:30:58 - Connected !
09:30:58 - Metered connection detected.
09:30:58 - WAU is configured to force update checking on metered connection
09:30:58 - Winget Version: v1.6.3482
09:30:58 - WAU current version: 1.19.1
09:30:59 - WAU uses Black List config
09:30:59 - Checking application updates on Winget Repository...
09:31:00 - An unusual thing happened (maybe all apps are upgraded):

   -

No installed package found matching input criteria.
1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.

09:31:00 - No new update.
09:31:00 - End of process!
```

WAU is also not upgrading .Net 6 to the current version.  In both cases just doing 'winget upgrade --all' does what I expect.

### What version of WAU has the issue?

1.19.1

### What version of Windows are you using (ex. Windows 11 22H2)?

Server 2022

### What version of winget are you using?

1.6.3482

### Log information

```txt
See above
```

### Additional information

I can duplicate this on other Windows versions as well.

**Comment by sshockley** [comment]
I now see this is probably related to #539 as well, which has a pending PR.

**Comment by fergusstrachan** [comment]
Got the same problem. It's constantly popping up about updating Remote Desktop, says it's updated but it hasn't.


08:59:37 - Updating Remote Desktop from 1.2.4763.0 to 1.2.5112.0...
08:59:41 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.RemoteDesktopClient'   ##########
08:59:41 - -> Running: Winget upgrade --id Microsoft.RemoteDesktopClient --accept-package-agreements --accept-source-agreements -h

   - 
   \ 
   | 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.24 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.24 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.24 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.24 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.24 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.24 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.24 MB
  █████████████████████████▒▒▒▒▒  8.00 MB / 9.24 MB
  █████████████████████████████▒  9.00 MB / 9.24 MB
  ██████████████████████████████  9.24 MB / 9.24 MB
                                                                                                                        
No available upgrade found.
No newer package versions are available from the configured sources.
08:59:45 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Microsoft.RemoteDesktopClient'   ##########
08:59:45 - Remote Desktop updated to 1.2.5112.0 !

**Comment by Romanitho** [comment]
is the 1.2.4763.0 version installed with Winget ?

**Comment by fergusstrachan** [comment]
TBH I don't know how to find this out. Winget doesn't tell you, does it?

Can I assume that if it was installed by other means then it won't be upgraded by WAU?

**Comment by Romanitho** [comment]
WAU uses Winget to update apps. So if Winget knows how to update your app, WAU will do it.
In your case, maybe the way you installed the app the first time, Winget doesn't know the way to update it.
You can try to uninstall your app, and reinstall a previous version from winget. Then, check if the update works.

**Comment by sshockley** [comment]
@fergusstrachan, maybe try running winget upgrade --all from an elevated command prompt and see if winget without WAU will do the upgrade.  I have had some problems with winget when an appx is installed per-machine but not per-user, but that's not WAU's fault.

This particular bug is where I have both .Net 6.x and 7.x installed; WAU sees that .Net 6.x is installed and that there's a "newer" version (7.x) and wants to upgrade, but 7.x is already installed.

**Comment by Romanitho** [comment]
I stopped fighting with this kind of apps 😅 I put them in my blacklist... and from time to time, I try manually to see if things got fixed or not.

**Comment by fergusstrachan** [comment]
Interesting...

I had 2 versions of Remote Desktop installed (1.2.4... and 1.2.5...), so I assumed Winget didn't like the original and just installed its own alongside.

So I uninstalled both. Then installed 1.2.4... with Winget.

WAU came along and said it was updating RD, and what did I end up with? Both versions again. :-)

**Comment by AndrewDemski-ad-gmail-com** [comment]
The root cause can be traced back to winget itself
[Better support for Side by Side packages #2129](https://github.com/microsoft/winget-cli/issues/2129)
We recommend putting those products on a black list and maintain them using different tool/method.

**Comment by fergusstrachan** [comment]
Andrew, this article seems to be about handling multiple already existing versions of a package.

My scenario is that I start by installing **Microsoft.RemoteDesktopClient** (a previous version, using `Winget install`) then `winget update`, instead of upgrading that version, installs the new one alongside it.

But I guess I'll blacklist it as you say.

**Comment by Romanitho** [comment]
Unfortunately, we cannot handle all problematic apps. And sometimes it depends on the dev as well, so things that can be broken one day, can be fixed another day...
