### ISSUE TITLE
[Bug]: XAML update failed

### ISSUE THREAD

**Issue by gabriel-vanca** [Romanitho/Winget-autoupdate#554]
### The problem

Same update at every run. It always fails. Xaml 2.8 is already installed.

![2024-01-24_03-08-25](https://github.com/Romanitho/Winget-AutoUpdate/assets/16124883/e7132246-d79f-424e-963d-5d6a2cd1e66b)

### What version of WAU has the issue?

latest

### What version of Windows are you using (ex. Windows 11 22H2)?

11 22h2

### What version of winget are you using?

latest

**Comment by KnifMelti** [comment]
I added it to my blacklist, everything works as it should anyway.
This is what I have installed before:
![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/102996177/eacb0aad-1b12-43f7-a278-2ec10280d087)
