### ISSUE TITLE
[Bug]: Symlink to logfile no longer gets created

### ISSUE THREAD

**Issue by s016aq** [Romanitho/Winget-AutoUpdate#556]
### The problem

I noticed that the symlink to the logfile is not being created during install any more (from version 1.18.0?)
Instead it's being created when the scheduled task is triggered (Winget-Upgrade.ps1)
But it is not created!
If I run Winget-Upgrade.ps1 from Powershell_ise (as SYSTEM) it works. But not with the Scheduled task.
If I remove ServiceUI.exe it works. So it has something to do with the script is spawned again with ServiceUI

### What version of WAU has the issue?

from 1.18.0

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 23H2

### What version of winget are you using?

1.6.3482

**Comment by AndrewDemski-ad-gmail-com** [comment]
The existing logic expects to have full folder tree up to \Logs\WAU-update.log
if that folder structure is missing, then symlink is not created.
Was the folder present before WAU got installed?


https://github.com/Romanitho/Winget-AutoUpdate/blob/acee968e06298bbb932e460f4927bd2c01995bad/Sources/WAU/Winget-AutoUpdate/functions/Invoke-PostUpdateActions.ps1#L14-L18


https://github.com/Romanitho/Winget-AutoUpdate/blob/acee968e06298bbb932e460f4927bd2c01995bad/Sources/WAU/Winget-AutoUpdate/Winget-Upgrade.ps1#L338-L343

**Comment by KnifMelti** [comment]
Yes, full path present.
It's exactly as @s016aq describes it.

**Comment by JonasNjopOlsson** [comment]
Regarding issues with creating symbolic links and ServiceUI.exe from Microsoft Deployment Toolkit, you may want to check the following bug report in PSAppDeployToolkit for an exlanation of the issue: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/1053

**Comment by KnifMelti** [comment]
This is fixed by a workaround
