### ISSUE TITLE
Anyway to add a private repository and get software only by that

### ISSUE THREAD

**Issue by JZafarr** [Romanitho/Winget-AutoUpdate#559]
Hi there,

I have my own private repository created by Winget Pro, it gives me a uniqueURL which I can add as a source to winget. Is there anyway I can use that to install software instead of going via public repos.

**Comment by AndrewDemski-ad-gmail-com** [comment]
# description
WAU looks for updates using command invoked in this file: https://github.com/Romanitho/Winget-AutoUpdate/blob/acee968e06298bbb932e460f4927bd2c01995bad/Sources/WAU/Winget-AutoUpdate/functions/Get-WingetOutdatedApps.ps1#L12

Full explanation of that particular winget command is here: 
https://learn.microsoft.com/en-us/windows/package-manager/winget/upgrade#options

| Option | Description |
|--------|--------|
| -s, --source | Restricts the search to the source name provided. Must be followed by the source name. |

In default/initial configuration of winget sources are defines as this:

>- The default "winget" source includes packages in the [Windows Package Manager Community Repository](https://github.com/microsoft/winget-pkgs).
>- The default "msstore" source includes packages in the Microsoft Store.

source: official readme @ https://github.com/microsoft/winget-cli?tab=readme-ov-file#sources

# Solution
@JZafarr, you would need to redefine source identifier in that command to switch from official repository to your own.
For now, it was not considered a variable in the WAU logic, hence it was permanently encoded in the script file.

I hope everything has been clarified.

**Comment by AndrewDemski-ad-gmail-com** [comment]
The only workaround that comes to my mind is removing other sources and registering your own using "winget" name.
but that is a nasty workaround.

```
C:\>winget source
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Manage sources with the sub-commands. A source provides the data for you to discover and install packages. 
Only add a new source if you trust it as a secure location.

C:\>winget source
usage: winget source [<command>] [<options>]

The following sub-commands are available:
  add     Add a new source
  list    List current sources
  update  Update current sources
  remove  Remove current sources
  reset   Reset sources
  export  Export current sources
```

**Comment by JZafarr** [comment]
It's alright maybe a feature for the future, the ability to add custom repository. And ability to choose which repository is enabled and then install and update software only from the enabled repository.

I dont want to modify or remove the default winget public repository. I have already added my custom repository via 'winget source add' command and it works via command line without any issues. I just use the command:
"winget install <programname> -s <myreponame>" and it works.

**Comment by Romanitho** [comment]
We can try to thing about setting the info in a dedicated variable in the registry. This way, by default it will be configured to Winget, but admin could change it.
