### ISSUE TITLE
[Feature Request]: Digitally sign Powershell scripts

### ISSUE THREAD

**Issue by zxcvxzcv-johndoe** [Romanitho/Winget-AutoUpdate#562]
### The request

Hello,

We are using Applocker and it blocks running unknown powershell files from %programdata% (c:\programdata usually) where Winget-AutoUpdate seems to install it scripts.

So we get errors like EventId: 8007, EventTime: 2024-02-09T09:02:18Z, Source: Microsoft-Windows-AppLocker, Message: %OSDRIVE%\PROGRAMDATA\WINGET-AUTOUPDATE\FUNCTIONS\ADD-SCOPEMACHINE.PS1 was prevented from running.

Could you please digitally sign your scripts so we could whitelist them using a certificate? 

Or is there way to install the software and its scripts automatically under C:\program files\ (where only admins can write by default)? Of course whitelisting them by certificate is preferred option but this could be a workaround.

Thanks,

**Comment by AndrewDemski-ad-gmail-com** [comment]
Sort of a deja-vu. 
I lost track how many times it was requested.

Copy-pastes from #514
> I do not want to be devils advocate here but you can trust file by hash. [Understanding the file hash rule condition in AppLocker](https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/applocker/understanding-the-file-hash-rule-condition-in-applocker) I wouldn't expect a community-developed project to waste money on signing a single file for little or no profit.
> 
> If you have AppLocker in your company, it means that it is managed. The mouse doesn't bite. Going through the wizard to add a single file will take less time than writing in this thread.

**Comment by zxcvxzcv-johndoe** [comment]
> Sort of a deja-vu. I lost track how many times it was requested.
> 
> Copy-pastes from #514
> 
> > I do not want to be devils advocate here but you can trust file by hash. [Understanding the file hash rule condition in AppLocker](https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/applocker/understanding-the-file-hash-rule-condition-in-applocker) I wouldn't expect a community-developed project to waste money on signing a single file for little or no profit.
> > If you have AppLocker in your company, it means that it is managed. The mouse doesn't bite. Going through the wizard to add a single file will take less time than writing in this thread.

And just maybe if this gets requested so often shows how much better solution signing the files would be compared allowing file hashes.

**Comment by AndrewDemski-ad-gmail-com** [comment]
> And just maybe if this gets requested so often shows how much better solution signing the files would be compared allowing file hashes.

The product is covered by the MIT license, using it without an additional fee should be a sufficient nod to users asking for additional expenses related to the purchase of a certificate.
The moment the author asked for money to collect funds for the purchase of such a certificate, the same mouths that "ask" will fall silent.

**Comment by thenktor** [comment]
Is there any need, that `C:\ProgramData\Winget-AutoUpdate` is user writable? Having all scripts/EXEs in a directory, that is not writable by users, makes things much easier with AppLocker.

**Comment by AndrewDemski-ad-gmail-com** [comment]
Isn't the whole C:\ProgramData\ in RWX state for all users?
If yes, then C:\ProgramData\Winget-AutoUpdate inherits ACLs from parent container.

**Comment by KnifMelti** [comment]
> Isn't the whole C:\ProgramData\ in RWX state for all users?

That's correct.
Furthermore WAU makes sure every script/folder with scripts is only RX for users

**Comment by andreasbrett** [comment]
> Or is there way to install the software and its scripts automatically under C:\program files\ (where only admins can write by default)? Of course whitelisting them by certificate is preferred option but this could be a workaround.

You can install WAU in a location or your choice. First thing I did because I don't want stuff that is periodically run with system privileges to be modifiable by a normal user. 


https://github.com/Romanitho/Winget-AutoUpdate/blob/1b9b09b86b625d6b2befbdabdd6e6b5c952868ad/README.md?plain=1#L65

**Comment by zxcvxzcv-johndoe** [comment]
No, in ProgramData normal users get write permission only through CREATOR OWNER permission and they do not have write access to all files there. You should be able to see the examples from screenshot below

![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/124170934/83457696-cd30-4f24-a14e-6d75e50811cb)

**Comment by Romanitho** [comment]
You can choose the path for WAU installation
https://github.com/Romanitho/Winget-AutoUpdate?tab=readme-ov-file#advanced-installation
-WAUinstallPath
