### ISSUE TITLE
Get whitelist.txt from Private Azure Container using URL protected with SAS token

### ISSUE THREAD

**Issue by plyagent00** [Romanitho/Winget-AutoUpdate#584]
### Discussed in https://github.com/Romanitho/Winget-AutoUpdate/discussions/579

<div type='discussions-op-text'>

<sup>Originally posted by **plyagent00** March  4, 2024</sup>
Hello,

We use the approach to get the 3rd party software whitelist directly from Azure Public Blob Storage, we want to protect the URL with an SAS token and make our Container private.
Unfortunately, the protected SAS URL doesn't work with WAU and we receive such error: Couldn't reach/find/compare/copy from <URL with SAS token>

Is It possible to use It?
</div>

**Comment by KnifMelti** [comment]
Trying in #606
