### ISSUE TITLE
[Feature Request]: All Error Codes

### ISSUE THREAD

**Issue by unclesam87** [Romanitho/Winget-AutoUpdate#585]
### The request

Hey,
i have an rather unusual request or need an hint:
As i am writing an analyzer for the log files from all our winget auto update instances i would need an list of possible error codes and their meaning - so i was clicking trough our already existing logs files (sadly we run this script just in an very small group right now for testing so not that many examples) and wasn't finding that many error codes to get my self a good picture of how they are structured
so i was wondering: is there already an list? are the "error codes" the same as in winget (like this https://github.com/microsoft/winget-cli/blob/master/doc/windows/package-manager/winget/returnCodes.md) - sometimes they were translated to german so i was wondering if they coming out of winget

every little hint would be appreciated 
thanks

**Comment by AndrewDemski-ad-gmail-com** [comment]
Hey Sam,

the error codes are listed in winget source code [here](https://github.com/microsoft/winget-cli/blob/master/src/PowerShell/Microsoft.WinGet.Configuration.Engine/Exceptions/ErrorCodes.cs) and [here](https://github.com/microsoft/winget-cli/blob/master/src/AppInstallerSharedLib/Public/AppInstallerErrors.h)

Localized names come from winget itself. WAU does not translate texts. 
If successful upgrade/update cannot be confirmed, then it reports that fact using 
https://github.com/Romanitho/Winget-AutoUpdate/blob/04591eecd68ce9e5410fa1ab47165d5f1bd3f2f2/Sources/WAU/Winget-AutoUpdate/functions/Update-App.ps1#L122

And as a result, we may observe hiccups such as `Wenn ist das Nunstück git und Slotermeyer? Ja! Beiherhund das Oder die Flipperwaldt gersput! update failed.`

From what I've seen the list of errorcodes in winget project is still growing.
If you've seen this long list, you'll probably agree that maintaining and updating a parallel list in PowerShell scripts would be extremely tedious.
