### ISSUE TITLE
[Bug]: WAU-Configurator triggering anti-virus products (various)

### ISSUE THREAD

**Issue by Quitch** [Romanitho/Winget-AutoUpdate#590]
### The problem

Attempting to open the WAU-Configurator zip on Windows 11 with the latest definition files causes Windows Defender to block it, detecting it as Trojan:AndroidOS/ZkarletFlash.

VirusTotal shows that the following products also detect it as a trojan:

Aracit
BitDefender
Emsisoft
Fortinet
GData
Google
Ikarus
Lionic
MAX
Rising
SentinelOne (Static ML)
Trellix (FireEye)
VIPRE
Zoner

I also replicated this on Windows 10 using the latest definition files.

### What version of WAU has the issue?

1.19.1

### What version of Windows are you using (ex. Windows 11 22H2)?

11 23H2

### What version of winget are you using?

1.7.10661

**Comment by AusomeOllie10** [comment]
Yep, same issue here.

**Comment by martijnw1986** [comment]
This issue persists. It is still being detected as a Trojan virus (A serious threat) and automatically removed by Microsoft Defender.

**Comment by dominikmeier99** [comment]
The problem is also with SentinelOne

**Comment by dominikmeier99** [comment]
> This issue persists. It is still being detected as a Trojan virus (A serious threat) and automatically removed by Microsoft Defender.

What did you do as a solution? Exclusion with AV?

**Comment by KnifMelti** [comment]
WAU-Configurator.zip doesn't exist anymore. Use the current MSI

**Comment by dominikmeier99** [comment]
> WAU-Configurator.zip doesn't exist anymore. Use the current MSI

I must have missed something :) Where do you get them from?

**Comment by KnifMelti** [comment]
https://github.com/Romanitho/Winget-AutoUpdate/releases or:
`winget install Romanitho.Winget-AutoUpdate`
https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/Romanitho/Winget-AutoUpdate/2.0.0
