### ISSUE TITLE
[Bug]: -WAUWhitelist doesn't work if included_apps.txt does not already exist

### ISSUE THREAD

**Issue by ITistheworst** [Romanitho/Winget-AutoUpdate#605]
### The problem

When installing WAU with the switch '-UseWhiteList' and then running 'Winget-Install' for an app with the '-WAUWhitelist' switch, the app does not get added to the whitelist. 'included_apps.txt' does not seem to exist in the WAU folder by default and is not created if not present when using the '-WAUWhitelist'.

If you manually create a blank 'included_apps.txt' and then run the same command with 'Winget-Install' the whitelist gets updated as expected.

### What version of WAU has the issue?

1.20.0

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 10 22H2

### What version of winget are you using?

1.7.10861

**Comment by Romanitho** [comment]
Thanks for reporting. I'll check that when I have time ;)
