### ISSUE TITLE
[Bug]: The 'msstore' source requires you view the following agreements...

### ISSUE THREAD

**Issue by woodyinwoodley** [Romanitho/Winget-AutoUpdate#617]
### The problem

On a new device the updates log shows "The source requires the current machine's 2 lettter geographic region to be sent to the backend service to function properly (e.g. US)"

### What version of WAU has the issue?

1.17.8

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 10 22H2

### What version of winget are you using?

1.7.10861

### Additional information

I'm using the "Winget-AutoUpdate-aaS" but I think the actual work is done by (and log written by) pure 'Winget-AutoUpdate". Unsure if this is a real problem or just cosmetic, but I'd rather not have things in the log that look like problems either way.

**Comment by KnifMelti** [comment]
You're 5 pages back in the Release history with the 1.17.8 version from the fork [Winget-AutoUpdate-aaS](https://github.com/Weatherlights/Winget-AutoUpdate-Intune):
https://github.com/Romanitho/Winget-AutoUpdate/releases?page=5
Are you sure it is like that with the current WAU version?
Logs?

**Comment by Romanitho** [comment]
similar to #609
Two different solutions at the end.

**Comment by mtylich** [comment]
Sorry for jumping in but I had similar problem. Try to use only Romanitho solution because they already have GPOs and you are using only one installed app not two. From security perspective also better
