### ISSUE TITLE
[Feature Request]: Extend mods functionality with proxy support

### ISSUE THREAD

**Issue by soredake** [Romanitho/Winget-AutoUpdate#623]
### The request

Extend mods functionality with proxy support, how this will look:

You create `AIMP.AIMP-proxy` with these contents:
```
http://127.0.0.1:8118
```

And, WAU will use this proxy `--proxy http://127.0.0.1:8118` when updating AIMP.

### Is your feature request related to a problem?

```txt
All russian ips are blocked in my country, so I need to use proxy for installing/updating AIMP, for installing I can already use `--proxy`, but not for updating.
```

### Additional information

Requested before: https://github.com/Romanitho/Winget-AutoUpdate/issues/347

Proxy support can be enabled with `winget settings --enable ProxyCommandLineOptions`

https://github.com/microsoft/winget-cli/discussions/4428

**Comment by AndrewDemski-ad-gmail-com** [comment]
Hi,
if I read it right, the proxy feature is available in PR version of winget.
WAU operates on top of winget.
It would be up to @Romanitho to decide if preview features should be implemented into WAU.
Before winget folks do their bidding, there is still plenty of time to define that FR in detail. How it should be set up in advance? How to store/pass the reference to proxy etc.
How to terminate that on-demand(?) proxy?

WAU is capable of proxy awareness in its own context (by telling PS to use system proxy), but winget must have it implemented in all use cases to make any sense of it. Install-- proxy is not enough.
I would like to see the winget code for commandline handling with proxy switches on a bigger screen before passing my final judgment. That won't happen before 2024-05-11.
________________________________
From: soredake ***@***.***>
Sent: 06 May 2024 20:37
To: Romanitho/Winget-AutoUpdate ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Romanitho/Winget-AutoUpdate] [Feature Request]: Extend mods functionality with proxy support (Issue #623)


The request

Extend mods functionality with proxy support, how this will look:

You create AIMP.AIMP-proxy with these contents:

http://127.0.0.1:8118


And, WAU will use this proxy --proxy http://127.0.0.1:8118 when updating AIMP.

Is your feature request related to a problem?

All russian ips are blocked in my country, so I need to use proxy for installing/updating AIMP, for installing I can already use `--proxy`, but not for updating.

Additional information

Requested before: #347<https://github.com/Romanitho/Winget-AutoUpdate/issues/347>

Proxy support can be enabled with winget settings --enable ProxyCommandLineOptions

microsoft/winget-cli#4428<https://github.com/microsoft/winget-cli/discussions/4428>

**Comment by KnifMelti** [comment]
You could write your own upgrade string in an `AppID-preinstall.ps1` using winget with `--proxy http://127.0.0.1:8118`. 
Runs before trying to upgrade/install the APPID. 
All the variables/values are there when the mod IS called.

**Comment by Romanitho** [comment]
I think @KnifMelti's solution is the best approach for this type of issue. Otherwise, WAU would become overly complex for all these kinds of cases.

**Comment by soredake** [comment]
Closing for now, thanks for answers!
