### ISSUE TITLE
[Feature Request]: Able to install via winget

### ISSUE THREAD

**Issue by G0rocks** [Romanitho/Winget-AutoUpdate#625]
### The request

Requesting that WAU can be installed with winget, see this PR: https://github.com/microsoft/winget-pkgs/pull/152510

**Comment by Romanitho** [comment]
We are currently working on a MSI installer. I think it will be easier to manage WAU with winget after that.

**Comment by soredake** [comment]
Not stale.

**Comment by KnifMelti** [comment]
https://github.com/Romanitho/Winget-AutoUpdate/discussions/582#discussioncomment-10112654

**Comment by soredake** [comment]
Not stale.

**Comment by soredake** [comment]
Not stale.

**Comment by soredake** [comment]
Not stale.

**Comment by Romanitho** [comment]
https://github.com/microsoft/winget-pkgs/pull/182735
