### ISSUE TITLE
[Bug]: logs are not in C:\ProgramData\Microsoft\IntuneManagementExtension\Logs

### ISSUE THREAD

**Issue by mtylich** [Romanitho/Winget-AutoUpdate#627]
### The problem

Hi,

Please I found out that logs are not copied or linked to Intune logs folder.. C:\ProgramData\Microsoft\IntuneManagementExtension\Logs

logs are located in C:\ProgramData\Winget-AutoUpdate\Logs but not linked to intune logs
![Screenshot 2024-05-16 140421](https://github.com/Romanitho/Winget-AutoUpdate/assets/166599533/e9032f00-bd51-4e4f-b9da-eec033ba2a11)
![Screenshot 2024-05-16 140504](https://github.com/Romanitho/Winget-AutoUpdate/assets/166599533/a44e2c9e-b812-4407-885c-5777de429bfc)

### What version of WAU has the issue?

1.20.0

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 23H2

### What version of winget are you using?

1.7.11261

**Comment by KnifMelti** [comment]
Linked to: #556 
This came after ServiceUI was introduced managing the execution for System context - Connected user
The SymLink never gets created under ServiceUI.
If Winget-Upgrade.ps1 runs before a user logon the SymLink is created.

**Comment by mtylich** [comment]
I do not understand. we are using that in silent mode without any UI for periodic check of updates.

**Comment by KnifMelti** [comment]
As long as an user is logged on it runs under system via ServiceUI.
It's a bug depending of ServiceUI - nothing I know how to handle.
Everyting except creating SymLinks functions under ServiceUI.

**Comment by mtylich** [comment]
you are not able to implement it in Winget-AutoUpdate-Install.ps1 in install phase?

**Comment by KnifMelti** [comment]
Yes, as pointed out in #556

**Comment by mtylich** [comment]
ok, will it be fixed in new WAU version ?

**Comment by KnifMelti** [comment]
No on have the time...

**Comment by JonasNjopOlsson** [comment]
Regarding issues with creating symbolic links and ServiceUI.exe from Microsoft Deployment Toolkit, you may want to check the following bug report in PSAppDeployToolkit for an exlanation of the issue: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/1053

**Comment by KnifMelti** [comment]
This is fixed by a workaround
