### ISSUE TITLE
[Feature Request]: Version in whitelist

### ISSUE THREAD

**Issue by MRenem** [Romanitho/Winget-AutoUpdate#631]
### The request

Hi all,

it would be incredible if we could use versioning in whitelist. 

### Is your feature request related to a problem?

```txt
As a company we sometimes need to review newer versions of certain applications to check if the newer version overwrites something from our Intune installation. By now the tool is installing always the newest version. It would be great if you could develop the possibility to work with versions.
```

**Comment by Romanitho** [comment]
https://github.com/Romanitho/Winget-AutoUpdate/issues/313

**Comment by MRenem** [comment]
Thank you. I see the problem. Maybe we also try it with your mentioned solution.
