### ISSUE TITLE
Configurable updates interval

### ISSUE THREAD

**Issue by soredake** [Romanitho/Winget-AutoUpdate#64]
Would be nice to have install option to configure update interval like `-UpdatesInterval Weekly/BiWeekly/Monthly`

**Comment by Romanitho** [comment]
Was in my mind as well. Something like this maybe ?
`-UpdatesInterval Daily/Weekly/Monthly`
`-UpdatesOnLogon True/False`

**Comment by soredake** [comment]
Yeah, option to configure updates at logon will be nice as well.
