### ISSUE TITLE
Possible improvement - Send logs to sharepoint/teams channel

### ISSUE THREAD

**Issue by Snakeulescu** [Romanitho/Winget-AutoUpdate#65]
Great work first of all.

I had an idea that I think would work wonders in a corp environment, to append the hostname in front of the log file & publish them to teams/sharepoint.

The easy part i've already done: $Script:LogFile = "$LogPath\$($DeviceName)_updates.log" - in the "Start-Init.pst" file

Now am looking for a way to publish them. Will update if I find anything, but please share if you have an idea.

**Comment by Snakeulescu** [comment]
The easiest way that comes to mind (haven't tested yet) would be to create a sharepoint folder and give everyone in the org. access to it. After that just change the location where the script is created to that sharepoint page. Tried this approach for something different, and it work. Might as well try for this.

Another approach that I found would be this: https://scloud.work/en/powershell-win32-log-to-teams-intune/#webhook-in-teams-einrichten . It is somewhat different from what I would like, but worth a try.

Was thinking about power automate as well, but I am a noob there and will take a while.

**Comment by Romanitho** [comment]
Have you tried to implement ?

**Comment by Snakeulescu** [comment]
Yes I've tried, the sharepoint option is not working due to the script being run as system. You can close this for now as I am not able to the the teams webhooks yet.

**Comment by Romanitho** [comment]
thanks for your feedback ;)
We could maybe use a scheduled task that periodically send the log ta the centralized place as connected user ?!

**Comment by Snakeulescu** [comment]
I'll check this week if I find the bandwidth

**Comment by mtengmo** [comment]
Send logs to OMS Log Analytics with a HTTP POST ?

**Comment by Romanitho** [comment]
Why not. haven't had time to investigate yet.
