### ISSUE TITLE
Override arguments for specific packages

### ISSUE THREAD

**Issue by sitiom** [Romanitho/Winget-AutoUpdate#66]
I would like to have overridden arguments for specific packages using the `--override` flag. How can I do this for WAU?

**Comment by Romanitho** [comment]
Not supported yet as it depends on packages and we run WAU for all installed ones (expect black listed apps).

**Comment by sitiom** [comment]
bump

**Comment by sitiom** [comment]
bump

**Comment by sitiom** [comment]
Bump

**Comment by sitiom** [comment]
Bump
