### ISSUE TITLE
But, thinking about it a little more (empty lists) 

### ISSUE THREAD

**Issue by KnifMelti** [Romanitho/Winget-AutoUpdate#667]
But, thinking about it a little more...
...a situation where you don't want to exclude/include anything needs an empty list.
Maybe we should let an empty list be downloaded from GitHub (it's written the way it is as a check because GitHub doesn't supply any date/time in the header like a standard web server)?

_Originally posted by @KnifMelti in https://github.com/Romanitho/Winget-AutoUpdate/discussions/665#discussioncomment-10479590_

**Comment by Romanitho** [comment]
- what about eTag in header ?
- or downloading file on each run, after all it should be few ko only

**Comment by KnifMelti** [comment]
Yes, I think so too (second choice)

**Comment by Romanitho** [comment]
let's go for downloading on each run. It's safer and should not affect that much 😇
