### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by bradgillap** [Romanitho/Winget-AutoUpdate#669]
### The request

MSI installer.

### Is your feature request related to a problem?

```txt
Being able to install the client through windows domain application installer makes a lot of sense for systems that don't have it built into the windows deploy image.
```

**Comment by bradgillap** [comment]
Dude I'm stoked. You rule. I see the latest release.

**Comment by Romanitho** [comment]
A lot of work has been accomplished. Hopefully, there are no bugs. It's still in beta though!

**Comment by Romanitho** [comment]
Done
