### ISSUE TITLE
Configurable update time option

### ISSUE THREAD

**Issue by soredake** [Romanitho/Winget-AutoUpdate#68]
Would be nice to have this option, because i don't start my pc at 6am so with `-StartWhenAvailable` used it will start at user logon even though i've not used `-UpdatesAtLogon` option when installing.

**Comment by Romanitho** [comment]
You can still edit the scheduled task once set. WAU update won't change any settings on the scheduled task.

**Comment by soredake** [comment]
Not stale

**Comment by soredake** [comment]
Not stale.

**Comment by soredake** [comment]
Not stale

**Comment by soredake** [comment]
@Romanitho thanks!

**Comment by Romanitho** [comment]
Let us know if it helps and if it works as expected 😊

**Comment by soredake** [comment]
Tested with `-UpdatesAtTime 11AM`, works as expected.
