### ISSUE TITLE
[Bug]: Docker Desktop disapears after auto update

### ISSUE THREAD

**Issue by nortonrome** [Romanitho/Winget-AutoUpdate#685]
### The problem

Hi, I was wondering if someone else has observed that Docker Desktop occasionally disappears after auto updates take place. Some of our users complain that sometimes the app is even gone for a while. Does someone know if that has something to do with the Docker Desktop app or is this a WAU issue?

Greets

### What version of WAU has the issue?

1.20.0

### What version of winget are you using?

v1.8.1911

**Comment by AndrewDemski-ad-gmail-com** [comment]
The investigation would most likely lead to microsoft pkgs repo of all packages known to winget tool and that manifest will most likely state that docker desktop must be uninstall to install latest version.
________________________________
From: J ***@***.***>
Sent: 03 September 2024 15:31
To: Romanitho/Winget-AutoUpdate ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Romanitho/Winget-AutoUpdate] [Bug]: Docker Desktop disapears after auto update (Issue #685)


The problem

Hi, I was wondering if someone else has observed that Docker Desktop occasionally disappears after auto updates take place. Some of our users complain that sometimes the app is even gone for a while. Does someone know if that has something to do with the Docker Desktop app or is this a WAU issue?

Greets

What version of WAU has the issue?

1.20.0

What version of Windows are you using (ex. Windows 11 22H2)?

No response

What version of winget are you using?

v1.8.1911

Log information

No response

Additional information

No response

**Comment by nortonrome** [comment]
can you tell me how to check if that's the actual case? i haven't found any information for docker desktop in that regard

**Comment by AndrewDemski-ad-gmail-com** [comment]
The YAML manifest seems ok in that regard.
`UpgradeBehavior: install`
https://github.com/microsoft/winget-pkgs/blob/68173d36158b987092c2360f2686d4958eac3f5d/manifests/d/Docker/DockerDesktop/4.34.0/Docker.DockerDesktop.installer.yaml#L16

The logic which removes older version might be hidden in the "Docker Desktop Installer.exe"
That wont be easy to extract in human-readable form.
