### ISSUE TITLE
Doesn't work anymore..

### ISSUE THREAD

**Issue by leochras** [Romanitho/Winget-AutoUpdate#70]
v1.9.0 on Windows 11

I don't know why, but recently, the tool always says something like "No internet connection" even though I'm connected and don't use a proxy/VPN/custom DNS. (winget works fine when I use it "standalone") I tried reinstalling and now I get this error:

![image](https://user-images.githubusercontent.com/16163571/166211966-2b4fa634-3b66-4a58-9eb3-668f61c1fe65.png)

Also, the message doesn't make much sense because it says the installation succeeded?!

edit: I don't get any error messages when running the .bat file, but that could be because of the program itself.

**Comment by leochras** [comment]
It was an issue with my network configuration, sorry.

**Comment by Romanitho** [comment]
not worries 😉  happy that it still works 😅
