### ISSUE TITLE
why there is no automatic extract archive files when updating WAU-Configurator

### ISSUE THREAD

**Issue by candrapersada** [Romanitho/Winget-AutoUpdate#703]
Will there be a feature to automatically extract `WAU-Configurator.zip` when updating `WAU-Configurator` version?

**Comment by Romanitho** [comment]
a MSI version will soon be released.

**Comment by candrapersada** [comment]
Can I use bat without `WAU-Configurator` to change Configuration?

**Comment by Romanitho** [comment]
not sure to understand, but the bat is the configurator

**Comment by Romanitho** [comment]
MSI soon
