### ISSUE TITLE
[Bug]: after WAU upgrade the "default_excluded_apps" file was overided to default enteries

### ISSUE THREAD

**Issue by ilyak83** [Romanitho/Winget-AutoUpdate#706]
### The problem

It was happened twice, after upgrade to the after 1.21.5 and the second time 1.21.6. The "default_excluded_apps" have been reset to the default values or overrides by them. So that was an annoying to restore form the backup of excluding list after every app upgrade.

### What version of WAU has the issue?

1.21.6

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 23H2

### What version of winget are you using?

v1.8.1911

### Log information

```txt
#################################################################
#	9/19/2024 - CHECK FOR APP UPDATES (System context - Connected user)
#################################################################
06:55:59 - Notification Level: Full. Notification Language: English
06:55:59 - Checking internet connection...
06:55:59 - Connected !
06:55:59 - Winget Version: v1.8.1911
06:55:59 - WAU current version: 1.21.6
06:55:59 - WAU AutoUpdate is Enabled.
06:55:59 - WAU is up to date.
06:55:59 - WAU uses Black List config
06:56:00 - -> Successsfully loaded default excluded apps list.
```

**Comment by Romanitho** [comment]
The default is the default. Normal behavior. 
If you want to use a blacklist, you have to bring your own excluded_apps.txt file.

**Comment by ilyak83** [comment]
Hi Romanitho,
That what I exactly did, and its worked well for Me until last updates. But I just want to clarify, maybe something changed in the way how the app work, because the folder directory was changed? I mean, if I'll put the excluded_apps.txt into the "C:\ProgramData\Winget-AutoUpdate\config" folder, it should be work. and after next update of app it will be work properly?
Best Regards,

**Comment by Romanitho** [comment]
Nope. Nothing has changed. We just crated a default file to config folder, but your list should remain in the root directory.

**Comment by ilyak83** [comment]
Thanks
