### ISSUE TITLE
how to use `--skip-dependencies` in `Winget-AutoUpdate`?

### ISSUE THREAD

**Issue by candrapersada** [Romanitho/Winget-AutoUpdate#717]
how to use custom arguments for Skips processing package dependencies in `Winget-AutoUpdate`?

**Comment by Romanitho** [comment]
at the moment this is not natively supported. You have to use mods and pass the arguments:
https://github.com/Romanitho/Winget-AutoUpdate/tree/main/Sources/Winget-AutoUpdate/mods#winget-native-parameters

@KnifMelti to confirm :)

**Comment by candrapersada** [comment]
* https://github.com/microsoft/winget-cli/issues/4880
