### ISSUE TITLE
[Bug]: DOSBox installation successful but WinGet-AutoUpdate returns that the installation had failed

### ISSUE THREAD

**Issue by ES-PSH** [Romanitho/Winget-AutoUpdate#728]
### The problem

After installing DOSBox WinGet-AutoUpdate returns the status Installation failed! The application is installed successful. 

Did also test the winget command. winget install --id DOSBox.DOSBox. This installation is successful.

### What version of WAU has the issue?

1.21.13

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 23H2

### What version of winget are you using?

1.8.1911

### Log information

```txt
13:20:07 - Start DOSBox.DOSBox processing...
13:20:09 - -> DOSBox.DOSBox exists on Winget Repository.
13:20:10 - -> Installing DOSBox.DOSBox...
13:20:10 - -> Running: "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.23.1911.0_x64__8wekyb3d8bbwe\winget.exe" install --id DOSBox.DOSBox -e --accept-package-agreements --accept-source-agreements -s winget -h 

Found DOSBox [DOSBox.DOSBox] Version 0.74-3
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://sourceforge.net/projects/dosbox/files/dosbox/0.74-3/DOSBox0.74-3-win32-installer.exe/download


  █████████████████████▒▒▒▒▒▒▒▒▒  1024 KB / 1.42 MB
  ██████████████████████████████  1.42 MB / 1.42 MB
Successfully verified installer hash
Starting package install...

Successfully installed
13:20:21 - -> DOSBox.DOSBox installation failed!
13:20:21 - DOSBox.DOSBox processing finished!

13:20:22 - ###   END REQUEST   ###
```

**Comment by Romanitho** [comment]
Can you check that the previous version successfully uninstalled ?

**Comment by ES-PSH** [comment]
This was a clean installation on Windows Sandbox.

**Comment by Romanitho** [comment]
??
I just asked if, after WAU updates the app, the previous version is still seen as installed.

**Comment by KnifMelti** [comment]
It looks from the log that this isn't **WAU** updating, but you're installing via `Winget-Install.ps1` 

This seems to be an **DOSBox** fault.
I can't find any registry saying **DOSBox** is installed and nothing in **Uninstall or change a program** in the **Control panel** says it's installed. And **WAU** can't see it's installed.

It' a nullsoft installation https://github.com/microsoft/winget-pkgs/blob/master/manifests/d/DOSBox/DOSBox/0.74-3/DOSBox.DOSBox.installer.yaml, but doesn't seem follow the standard in registring itself as installed in Windows.

It installs alright, but when `Winget-Install.ps1` checks if it is installed via `winget export -s winget -o $JsonFile --include-versions` and then search in that file after `DOSBox.DOSBox` it doesn't find it, hence the:
```
Successfully installed
13:20:21 - -> DOSBox.DOSBox installation failed!
```

**Comment by ES-PSH** [comment]
Thanks for the info.

I build a workaround with a modification (DOSBox.DOSBox-install.ps1) to place dummy keys in the uninstall section in the registry.  This way WinGet will detect the application is installed and the error is gone.
