### ISSUE TITLE
how to add or update `excluded_apps.txt` if use `winget` to install `WAU`?

### ISSUE THREAD

**Issue by candrapersada** [Romanitho/Winget-AutoUpdate#731]
![image](https://github.com/user-attachments/assets/c3e85ce7-1d50-44b6-8f2d-16e19fd90c9c)

**Comment by Romanitho** [comment]
There are a few ways to do it. You can use GPO, a script, or manually replace the file in the installation directory.

**Comment by candrapersada** [comment]
> However, with the MSI, it's easy to update your list.

how to use `excluded_apps.txt` if `Use winget to install WAU`?

**Comment by Romanitho** [comment]
Currently, you can't. You have to do it manually.
You can use GPO if you're an admin, or use the ListPath setting.
