### ISSUE TITLE
[Bug]: Even if WAU AutoUpdate is disabled, it updates itself.

### ISSUE THREAD

**Issue by chrhaudum** [Romanitho/Winget-AutoUpdate#750]
### The problem

10:47:40 - Notification Level: Full. Notification Language: Deutsch
10:47:40 - Checking internet connection...
10:47:40 - Connected !
10:47:41 - Winget Version: v1.8.1911
10:47:41 - WAU current version: 1.20.1
10:47:41 - WAU AutoUpdate is Disabled.
10:47:41 - WAU uses Black List config
10:47:41 - Checking application updates on Winget Repository...
-> Available update : Microsoft 365 Apps for Enterprise - de-de. Current version : 16.0.17928.20216. Available version : 16.0.18025.20140.
-> Available update : Winget-AutoUpdate (WAU). Current version : 1.20.1. Available version : 2.0.0.
-> Available update : Teams Machine-Wide Installer. Current version : 1.5.0.8070. Available version : 1.7.00.27855.
10:47:44 - Microsoft 365 Apps for Enterprise - de-de : Skipped upgrade because it is in the excluded app list
10:47:45 - Updating Winget-AutoUpdate (WAU) from 1.20.1 to 2.0.0...
10:47:50 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Romanitho.Winget-AutoUpdate'   ##########
10:47:50 - -> Running: Winget upgrade --id Romanitho.Winget-AutoUpdate -e --accept-package-agreements --accept-source-agreements -s winget -h

![WAU](https://github.com/user-attachments/assets/95c1c853-149d-40cd-b4fd-fedcf5f97640)

### What version of WAU has the issue?

1.20.1

### What version of Windows are you using (ex. Windows 11 22H2)?

W11 23H2

### What version of winget are you using?

1.8.1911

**Comment by Romanitho** [comment]
that's because WAU v2 is now on Winget. Add Romanitho.Winget-AutoUpdate in your Blacklist.

**Comment by chrhaudum** [comment]
it would be great if **Romanitho.Winget-AutoUpdate** is automatically added in Blacklist when I check **Disable WAU AutoUpdate**

**Comment by Romanitho** [comment]
It will be included by default in the next releases. However, we can't force it into the blacklist since some people might prefer to update WAU through winget rather than WAU itself. Who knows :)

**Comment by STRIF-007** [comment]
Hello, The winget app does not autoupdate...

Available update : Winget-AutoUpdate (WAU). Current version : 1.21.13. Available version : 2.1.0.
13:24:28 - Winget-AutoUpdate (WAU) : Skipped upgrade because it is not in the included app list

it ist thow in the included app list....
