### ISSUE TITLE
Update Winget version for existing WAU deployments

### ISSUE THREAD

**Issue by SkipToTheEndpoint** [Romanitho/Winget-AutoUpdate#78]
While #77 fixes/updates Winget at WAU install time, there's no functionality currently to update an existing WAU install with an updated version of winget if a minimum version number wasn't met. We could utilise the same Get-AppxProvisionedPackage check as the installer and perhaps keep a version number in an xml?

I'm going to investigate writing another function that could potentially achieve this, as while installing preview versions may be occasionally useful, it would be good to be able to revert to a milestone version if/when available.

**Comment by Romanitho** [comment]
The thing is, we didn't want to force users to use "preview" version when WAU was already installed. So only new install are concerned. As Winget should get updated by itself with MSStore, we expected Winget Team to release a new stable version soon.
But maybe we should use these latest preview version as it embeds new features

**Comment by SkipToTheEndpoint** [comment]
Totally agree, but there is the potential to want to change the installed version if there's a breaking bug or feature (like this) that could be massively beneficial, and being able to control that functionality could be really useful. I did some initial work pulling out the WAU update links to a new update.xml file in the config folder and I'm working on a function for the winget version. The change to the links file makes forked testing or custom deployments easier.
