### ISSUE TITLE
[Bug]: White/Black List doesn't exist

### ISSUE THREAD

**Issue by miketunes** [Romanitho/Winget-AutoUpdate#788]
### The problem

Trying to just block autoupdate itself but getting an error:
09:34:09 - WAU uses External Lists from: https://www.innovateusa.com/default_excluded_apps.txt
09:34:09 - Couldn't reach/find/compare/copy from https://www.innovateusa.com/default_excluded_apps.txt...
09:34:09 - PATH must end with a Directory, not a File...
09:34:09 - Critical: White/Black List doesn't exist, exiting...

### What version of WAU has the issue?

 2.1.0

### What version of Windows are you using (ex. Windows 11 22H2)?

Win10 22H2

### What version of winget are you using?

1.9.25200

### Log information

```txt
#################################################################
#    12/6/2024 - CHECK FOR APP UPDATES (System context - Connected user)
#################################################################
09:23:07 - Notification Level: SuccessOnly. Notification Language: English
09:23:07 - Checking internet connection...
09:23:30 - Connected !
09:23:33 - Checking prerequisites...
09:23:50 - -> WinGet is up to date: v1.9.25200
09:23:50 - Prerequisites checked. OK
09:23:50 - WAU current version: 2.1.0
09:23:50 - WAU AutoUpdate is Enabled.
09:23:50 - WAU is up to date.
09:23:50 - WAU uses External Lists from: https://www.innovateusa.com/default_excluded_apps.txt
09:23:52 - Couldn't reach/find/compare/copy from https://www.innovateusa.com/default_excluded_apps.txt...
09:23:52 - PATH must end with a Directory, not a File...
09:23:52 - Critical: White/Black List doesn't exist, exiting...
```

**Comment by wesleyderooij** [comment]
if i configure blacklist with admx then default excluded apps are the default, is there a possibilty that default execluded apps is empty and only when you push excluded apps this is working?

**Comment by miketunes** [comment]
I'm not sure, the error appears to have gone away now.
